### ISSUE TITLE
invisible windows cause the tiling to scroll

### ISSUE THREAD

**Issue by notpeelz** [paperwm/PaperWM#466] opened 2023-01-19 04:03 UTC
If you have enough windows in your workspace (enough so you can scroll), running `wl-copy` will cause the workspace to scroll slightly to the right.

How to reproduce:
1. Open 3 terminal windows
2. Focus the 2nd one (the one touching the right edge of the screen)
3. `echo test | wl-copy`
That should be enough to trigger the behavior. You should notice the tiling scroll slightly to the right.

I'm assuming this is because wl-clipboard spawns an invisible window (which steals focus) so it can interact with the clipboard.
I've tried forcing it to the scratch layer with a winprop rule matching [`wl-clipboard`](https://github.com/bugaevc/wl-clipboard/blob/aa4633b894c3c5ae6053026529ec9288566060a6/src/types/shell-surface.c#L69). I've also tried adding a call to `wl_shell_surface_set_class` in wl-clipboard, but that didn't work either.

**Comment by jtaala** [comment] 2023-01-21 07:25
Thanks @notpeelz, so, I was able to reproduce this ~~but did solve it with a winprop using `wm_class` = `Gnome-shell` and `scratch_layer` = true.  It seems `wl-copy` does create invsible/untracked windows of that class.~~
_Scrap that - still happens (just didn't notice it since the terminal windows wasn't up against the right side..._

~~I've implemented `winprops` in the settings ui with PR #463 and in the [PaperWM-redux](https://github.com/PaperWM-redux/PaperWM) fork.  Here's the settings I used:~~

Just a thought, I note that [`wl-clipboard`](https://github.com/bugaevc/wl-clipboard/blob/aa4633b894c3c5ae6053026529ec9288566060a6/src/types/shell-surface.c#L69) sets the title.  Have you tried setting `title` in winprop to `wl-clipboard`?

**Comment by jtaala** [comment] 2023-01-21 10:20
Okay @notpeelz, this works in my testing:  setting winprop `title` = `wl-clipboard` and `scratch_layer` = true.

I've also updated #463 and the [PaperWM-redux](https://github.com/PaperWM-redux/PaperWM) fork to now have `title` in the winprops extension settings ui to make it much easier to set winprops `title` property.  Here's the settings I used that worked for me:

![image](https://user-images.githubusercontent.com/30424662/213862546-07c41248-7fac-4c0d-8907-5c12964da01a.png)

**Comment by notpeelz** [comment] 2023-01-21 14:08
Yup, that seems to work, thanks! Not sure why matching the class didn't work. Maybe ([`wl_shell_surface_set_class`](https://wayland-client-d.dpldocs.info/wayland.client.protocol.wl_shell_surface_set_class.html)) wasn't the correct Wayland call? Not sure, I don't know much about low-level rendering stuff.

Although, I also have this problem with other invisible windows (e.g Wine/Proton games/programs -- all their windows usually have the same class or have an unreliable title). Do you know if it's possible to match for dimensions in `user.js`, or would I have to patch the code?

**Comment by jtaala** [comment] 2023-01-22 04:20
> Although, I also have this problem with other invisible windows (e.g Wine/Proton games/programs -- all their windows usually have the same class or have an unreliable title). Do you know if it's possible to match for dimensions in `user.js`, or would I have to patch the code?

I'm not quite sure what you're trying to do, but `user.js` is essentially a javascript module with it's `init`, `enable`, `disable` functions run at certain times.  So, in theory you could have something there that picks up a signal (e.g the `show` signal?) that is emitted whenever windows are rendered (and get activated window dimensions)... although that approach will likely be messy etc.

Forking and working on that would likely be easier.  If you get somewhere with it, and think it would be useful for others definitely feel to to create a PR.

**Comment by jtaala** [comment] 2023-01-31 11:33
Closing as original issue was resolved.

**Closed as completed by jtaala** 2023-01-31 11:33 UTC
