### ISSUE TITLE
Anki window content disappear when switching to the other monitor/workspace

### ISSUE THREAD

**Issue by hipnoizz** [paperwm/PaperWM#296] opened 2020-05-01 13:40 UTC
How to reproduce:
- open Anki (https://apps.ankiweb.net/),
- move the cursor to the second monitor/workspace.

Then content of Anki window will disappear. It will re-appear when the cursor goes back to the workspace displaying Anki.

See [screencast_anki.zip](https://github.com/paperwm/PaperWM/files/4564400/screencast_anki.zip).

Anki was installed from the stock Ubuntu package. It is a KDE/QT application - I'm not sure if it matter. I check Krita, which is KDE/QT app, but it looks ok.

**Comment by hedning** [comment] 2020-05-01 14:50
Sounds like https://github.com/paperwm/PaperWM/issues/270. I'm guessing anki uses a webview?

**Comment by hipnoizz** [comment] 2020-05-02 12:57
It is possible. I'm not familiar with the Anki codebase nor QT, but I think that the main Anki window that is disappearing in my screencast is implemented in https://github.com/ankitects/anki/blob/master/qt/aqt/deckbrowser.py and I see various references to HTML there.

**Comment by hedning** [comment] 2020-06-12 22:13
fairly certain this is a duplicate of #270

**Closed by hedning** 2020-06-12 22:13 UTC
