### ISSUE TITLE
Easy to customize shortcuts?

### ISSUE THREAD

**Issue by DanielJoyce** [paperwm/PaperWM#375] opened 2021-03-15 16:12 UTC
More and more seem to be breaking or getting co-opted by gnome/pop-os.

**Comment by DanielJoyce** [comment] 2021-03-15 16:13
super-t no longer seems to work

**Comment by hedning** [comment] 2021-04-05 10:32
Probably need more info, but if IIRC PopOS supplies it's own tiling extension that we have no plans of supporting. To get paperwm working as intended you most likely have to disable the built in tiling extension pop provides.

Closing for now.

**Closed by hedning** 2021-04-05 10:32 UTC
