### ISSUE TITLE
Performance issues on Fedora 31

### ISSUE THREAD

**Issue by evelineraine** [paperwm/PaperWM#215] opened 2019-12-29 14:11 UTC
Hi,

I am using PaperWM on Fedora 31 (Wayland) on my MacBook Pro 2015.
The app I'm using the most is Firefox (Wayland version). With plain Gnome everything works very smoothly - navigating pages and video playback (with the new Firefox renderer, even macOS-level smooth).

As soon as I enable PaperWM, scrolling becomes much laggier and skips frames, and when playing HTML5 video (YT, Netflix) there is noticeable video jitter and in a minute even the fan starts spinning loudly to prevent overheating. 
No other extensions are enabled.

Is this a known side effect of running PaperWM on an old-ish laptop?
I would gladly provide more details, but I would need instructions (I have no idea how to profile Gnome).

Thanks!

**Versions**

| Component | Version |
| - | -: |
| OS | Fedora Workstation 31 |
| Gnome | 3.34.2 |
| PaperWM | develop (b8a5d74) |

**Comment by hedning** [comment] 2019-12-29 22:24
> Is this a known side effect of running PaperWM on an old-ish laptop?

Nope, not that I know of, but sounds like there's a problem somewhere.

I'm currently using X11 at the moment, but I did a quick test in a nested session and wasn't able to see any obvious difference between plain gnome-shell and paperwm, will test next time I log into a wayland session.

You should be able to profile using sysprof: https://www.youtube.com/watch?v=eDs-tx4gbeU

In the meantime, this is a random guess that might help: https://github.com/paperwm/PaperWM/tree/peformance-test

**Comment by evelineraine** [comment] 2019-12-30 11:02
Tested the `performance-test` branch and it's the same.
In fact when GPU acceleration is enabled for videos, it plays great regardless of PaperWM. The activities that lag are the purely-CPU ones.

I'm running it on my not-so-new MacBook Retina, so it's much more sensitive to graphical performance overhead than any recent desktop / laptop would be. Maybe this is why I'm the first one to report such issue.

I'll take a look at sysprof once I have more free time and reply back if I see anything useful.

Thank you!

**Comment by hedning** [comment] 2020-01-12 14:17
I'm guessing you're seeing the effect of the window always having an active clone (which is integral to how paperwm does animations).

Specifically I'm able to reproduce a consistent overhead in the gnome-shell process by having a video playing on a hidden workspace, which disappears when I kill the clone (or set its source to `null`).

Killing and creating clones on demand is probably not viable, but setting the clone's source might be cheaper, so I'll try experimenting with that.

**Comment by hedning** [comment] 2020-01-13 13:15
OK, not sure if this does everything, but it should reduce the overhead due to clones: https://github.com/paperwm/PaperWM/tree/reduce-clone-overhead

**Comment by jfmcbrayer** [comment] 2020-01-22 18:43
I am also using PaperWM on Gnome on Fedora 31, on Wayland, and while I haven't seen performance issues as such, I have seen worse battery life. Could this be related?

**Comment by hedning** [comment] 2020-01-22 20:18
Somewhat reduced battery is probably to be expected at the very least due to all the animations etc. that are being done.

I'll push the above branch to develop soon, which should reduce some unnecessary overhead when of windows rendering in the background.

**Comment by jtaala** [comment] 2023-03-03 09:43
Closing as things have moved on since PR was submitted (including animation/tween changes).  Please comment if you are still noticing the same performance issues and we'll reopn.

**Closed by jtaala** 2023-03-03 09:43 UTC
