### ISSUE TITLE
Selecting a menu in an inactive window.

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#250] opened 2020-02-15 03:46 UTC
When clicking a drop-down in non-active window, it gets selected and then a moment later (when the view is switched to the window), deselected.

**Comment by hedning** [comment] 2020-02-15 04:51
Hmm, I'm unable to reproduce on gnome-shell 3.34.3 Wayland. What shell version are you on?

Note if the window isn't fully visible, and therefor moved when focused, this is somewhat expected and there's not necessarily that much we can do about it (though this case also seems to work in eg. nautilus/files in wayland).

**Comment by hedning** [comment] 2020-02-15 04:51
Hmm, I'm unable to reproduce on gnome-shell 3.34.3 Wayland. What shell version are you on?

Note if the window isn't fully visible, and therefor moved when focused, this is somewhat expected and there's not necessarily that much we can do about it (though this case also seems to work in eg. nautilus/files in wayland).

**Comment by jtagcat** [comment] 2020-02-15 05:21
GNOME Shell 3.34.3 Wayland.
When I click the option menu, it just slides over, but in the screen capture, it glitches out a bit.
https://sh.c7.ee/12ujg2/Screencast%20from%2015.02.2020%2007:19:39.webm

**Comment by jtagcat** [comment] 2020-02-15 05:24
How I see it: https://sh.c7.ee/51PVC/VID_20200204_203720~2.mp4

**Comment by jtagcat** [comment] 2020-02-15 05:27
How I see it: https://sh.c7.ee/F8Pf2/VID_20200215_072256.mp4

btw is there any place PaperWM stores logs?

**Comment by hedning** [comment] 2020-02-15 05:46
Right, I doubt there's that much we can do about that edge case. It's to a large extent up to the application to handle it «correctly» (eg. in tilix the context menu will pop up where the right button press was triggered, while in nautilus the context menu doesn't open).  

If you're on systemd distro you should be able to do something like this: `journalctl --user-unit=gnome-shell-wayland.service` (we also ship a `debug` script which will follow the approriate log).

**Comment by jtagcat** [comment] 2020-02-15 07:09
It was gnome tweaks (I think I threatened to open paperwm settings), gnome things should at least work...

**Comment by jtaala** [comment] 2023-04-08 04:23
Haven't seen this (tried a few times to reproduce unsuccessfully).  Let us know if it's still valid (i.e. seeing it in a recent version of PaperWM or can reliably reproduce it).

Planning on closing this in a month or so.

**Comment by jtaala** [comment] 2023-05-15 19:25
Closing as stipulated in previous comments (have received no further feedback in more than a month).

**Closed by jtaala** 2023-05-15 19:25 UTC
Labels: bug, no longer valid?, can't reprodurce
