### ISSUE TITLE
PaperWM crashed SyntaxError: import declarations may only appear at top level of a module - unable to  relaunch

### ISSUE THREAD

**Issue by fumbles** [paperwm/PaperWM#626] opened 2023-10-12 13:20 UTC
**Describe the bug**

**To Reproduce**
1. Did git pull for branch release
2. PaperWM and DE crashed
3. Extensions menu says `SyntaxError: import declarations may only appear at top level of a module`

**Expected behavior**
Not crashing.

**Screenshots**
```
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
![image](https://github.com/paperwm/PaperWM/assets/90968/8171bc7b-748f-46e5-ac3b-8750913b36d8)

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Fedora 38
GNOME Shell 44.5
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: 473f4da3b0f2e72c12d41074a88878ec8232816b
Enabled extensions:
- drive-menu@gnome-shell-extensions.gcampax.github.com
- clipboard-indicator@tudmotu.com
- utcclock@injcristianrojas.github.com
- caffeine@patapon.info
- places-menu@gnome-shell-extensions.gcampax.github.com
- appindicatorsupport@rgcjonas.gmail.com
- apps-menu@gnome-shell-extensions.gcampax.github.com
- dash-to-dock@micxgx.gmail.com
- background-logo@fedorahosted.org

```

**Additional context**

**Comment by fumbles** [comment] 2023-10-12 13:21
I'll note I removed PaperWM from extensions and redid the git clone and ./install. Same behavior

**Comment by jtaala** [comment] 2023-10-12 19:25
Hey Daniel, `release` and `develop` branch are now on gnome 45.

You're still on gnome 44.  As outlined in the readme, please use the `gnome-44` branch.

**Comment by jtaala** [comment] 2023-10-12 19:26
Or install via https://extensions.gnome.org/extension/6099/paperwm/ (which can check your gnome-shell version)

**Comment by jtaala** [comment] 2023-10-12 19:29
P.S. there's no compatibility between gnome 44 and gnome 45 extensions as 45 moved to ESM modules (meaning all extensions need to be updated for 45).

**Comment by jtaala** [comment] 2023-10-12 19:30
Closing as you're just on the wrong branch.

Please see the big notice at top of the readme.

**Closed as completed by jtaala** 2023-10-12 19:30 UTC

**Comment by fumbles** [comment] 2023-10-12 20:21
Ah I see. That would be my bad… I was on release for some reason(maybe that’s where 44 was a while back) and just did a git pull 😅 Everything is good now after checking out the gnome-44 branch. Ignore this issue…. Sent from my iPhoneOn Oct 12, 2023, at 14:26, jtaala ***@***.***> wrote:﻿
Or install via https://extensions.gnome.org/extension/6099/paperwm/

**Comment by jtaala** [comment] 2023-10-12 21:15
All good!  Yeah, we only recently moved the `release` and `develop` branches to gnome-45 given it's the official gnome release now.

P.S. please do another `git pull` on `gnome-44` branch as I just pushed up a fix for a small regression we recently had.

Cheers!

**Comment by jtaala** [comment] 2023-10-12 21:18
Lastly, installing via https://extensions.gnome.org/extension/6099/paperwm/ is a good option if you just want the latest / tested version for your gnome-shell.  Gnome will let you know when a new PaperWM extension version is out and install it on the next logout/login.

**Comment by Boris00035** [comment] 2023-11-09 13:55
I got this same error now while installing via the [Gnome Extensions](https://extensions.gnome.org/extension/6099/paperwm/) page, and being on gnome 45. 

This is the stack trace:
  @file:///home/boris/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/prefs.js:1:24
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by jtaala** [comment] 2023-11-09 13:58
Looks like you installed the gnome 44 version.  Did you download it manually on ego?

**Comment by Boris00035** [comment] 2023-11-09 14:04
No, just clicked toggle on the extension website. I can try manually building to see if that works?

**Comment by jtaala** [comment] 2023-11-09 14:04
Mainloop is a gnome 44 (and below) method which isn't in the things 45 version.  Double check you downloaded the right shell version.

**Comment by jtaala** [comment] 2023-11-09 14:09
Hmmm, that's weird.  Try installing manually or by source (clone repo, checkout release branch and run `./install.sh`).

**Comment by jtaala** [comment] 2023-11-09 14:10
Did you just update to gnome 45?

**Comment by Boris00035** [comment] 2023-11-09 14:18
I double checked if I had the 45 version selected, and it still gave the same issue. Installing manually worked without issues. I then removed that again, and tried installing via the website and then it instructed me to relog, which made it work. Could/should have tried to relog after installing first time around.

I have been on gnome 45 for a bit now, definitely had a relog before upgrading.
Thanks for the quick response!

**Comment by jtaala** [comment] 2023-11-09 14:21
Interesting, seems ego got a bit confused.  Glad you got it working.
