### ISSUE TITLE
Touch Screen support?

### ISSUE THREAD

**Issue by GorrillaRibs** [paperwm/PaperWM#114] opened 2019-05-18 18:03 UTC
Hey! Firstly, this extension is _fantastic_ , thanks for all of your work! I've encountered an issue though, at least on xorg (I haven't got a chance to test with a wayland session yet) - on my laptop, which also has a touch screen, if I try to drag a windows titlebar (which with the mouse scrolls windows left or right) it moves the window away from it's spot (Maybe because gnome has a different event for moving with touch vs. mouse?). After this, mouse/keyboard bindings won't work until I open the activities overview. If there's any relevant logs or the like I should post, please let me know!

**Comment by hedning** [comment] 2019-05-19 15:18
Cheers, glad you like it :)

I'm indeed getting some really strange behavior when touch grabbing client side decorated windows on X11 (3.32.1), eg. `gedit`. The window is popped from its place as you say (to the right when I tested) and no longer respond to the dragging at all. We weren't able to reproduce the binding problem afterwards reliably though.

When windows are grabbed they're supposed to trigger `grab-op-begin`, but that simply doesn't happen with CSD windows it seems. Things work as expected, modulo screen keyboard weirdness, for server side decorated windows (eg. `xterm`) on X11 and all windows on wayland.

Without the proper signal being sent there's not necessarily much we can do, though I'll try to look into it some more.

**Comment by GorrillaRibs** [comment] 2019-05-20 15:43
Would there be any sort of logs/debugging for mutter so I can see what signal does sent when CSD windows are grabbed? I'm wondering if I'd be able to work out my own patch until this is fixed upstream

**Comment by olejorgenb** [comment] 2019-05-20 16:02
Mutter's log verbosity can be controlled dynamically by evaluating this javascript snippet: 

```javascript
Meta.add_verbose_topic(Meta.DebugTopic.*)
```

Use `F2 lg` (looking glass) or [gnome-shell-mode](https://github.com/paperwm/gnome-shell-mode).

`remove_verbose_topic` to "undo".

Possible values for `*`:
```
VERBOSE
FOCUS
WORKAREA
STACK
THEMES
SM
EVENTS
WINDOW_STATE
WINDOW_OPS
GEOMETRY
PLACEMENT
PING
XINERAMA
KEYBINDINGS
SYNC
ERRORS
STARTUP
PREFS
GROUPS
RESIZING
SHAPES
COMPOSITOR
EDGE_RESISTANCE
DBUS
```

The output usually ends up in systemd's log: `journalctl /usr/bin/gnome-shell --follow`

I'm not sure if gobject allows connecting to a "catch-all" signal. If so we should do that on a CSD window and see if something "hidden" happens.

**Comment by olejorgenb** [comment] 2019-05-20 16:15
One possibility is that the client moves the window by itself on X11.

In that case (or in either case really) we should get a `position-changed` signal on the window. We ignore this signal outside grabs for various reasons atm.

**Comment by GorrillaRibs** [comment] 2019-05-20 16:38
From what I can tell (from a few minutes debugging) is a successful grab-op happens when I touch a window with SSD (in my case firefox, evolution) as expected, but when I touch & drag a CSD window it only gets raised (i.e. `WINDOW_OPS: Raising window 0x2200003, ancestor of 0x2200003`). I'll look around and see if I can do anything with that for now

**Comment by olejorgenb** [comment] 2019-05-20 17:04
I digged a bit in mutters code and I think it's around [here](https://gitlab.gnome.org/GNOME/mutter/blob/master/src/x11/window-x11.c#L2753) things happen. 

The initial event must necessarily be handled by the client which then is supposed to(?) send a [_NET_WM_MOVERESIZE](https://standards.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472664672) message to the window manager.

Maybe GTK does not do this and simply moves the window instead. 

Not sure what touch events looks like in X11, but if the subsequent events (after a grab, which seems to be handled directly by the window manger) is not sufficient mouse-like it's not given that all window mangers will be able to cope.

Still - it's weird that that you experience the input issues.. could you describe in more detail exactly what happens to the dragged window? Is it moved as expected or does it jump?

And last - just to be sure :smiley: : it works without issues in gnome without paperwm enabled?

**Comment by GorrillaRibs** [comment] 2019-05-20 19:41
Without paperwm enabled, using touch to move the windows does work just fine :). With it enabled, touching/dragging windows with SSD works just like the mouse does, but touching a CSD window (even if it's the body of the window, as opposed to the titlebar) seems to freeze input until I open the activities overlay & close it. If I drag the CSD window, it moves around like normal w/o the extension enabled, but then when I let go has the same behaviour as just tapping the window. On wayland, I've confirmed, it works exactly as the mouse does.

**Comment by olejorgenb** [comment] 2019-05-20 20:42
Thanks :)

- I assume all input is frozen? (both input to the focused window and mutter/paperwm shortcuts)
- How do you activate the overlay? (button or keyboard shortcut?)
- Which gnome-shell version are you using (`gnome-shell --version`)?
- Does an on-screen-keyboard pop up when you use the touchscreen?
- Did you see any `JS ERROR`s in the log?
- After touching an unfocused window and activating the overlay to unfreeze again - has the new window received focus?

As @hedning  said we didn't manage to reproduce the exact issue using his touch-screen laptop, but maybe it's a gnome-shell version specific bug.

If you want you could try this patch that adds some extra logging:

```patch
diff --git a/tiling.js b/tiling.js
index 127d1c7dd..89eb27407 100644
--- a/tiling.js
+++ b/tiling.js
@@ -1770,6 +1770,7 @@ function destroyHandler(actor) {
 }
 
 function resizeHandler(metaWindow) {
+    print("resizeHandler", metaWindow.title);
     let f = metaWindow.get_frame_rect();
     let needLayout = false;
     if (metaWindow._targetWidth !== f.width || metaWindow._targetHeight !== f.height) {
@@ -2191,6 +2192,7 @@ function move_to(space, metaWindow, { x, y, transition, force }) {
 
 var inGrab = false;
 function grabBegin(metaWindow, type) {
+    print("grabBegin", metaWindow && metaWindow.title, type);
     // Don't handle pushModal grabs and SCD button (close/minimize/etc.) grabs
     if (type === Meta.GrabOp.COMPOSITOR || type === Meta.GrabOp.FRAME_BUTTON)
         return;
@@ -2208,6 +2210,7 @@ function grabBegin(metaWindow, type) {
 }
 
 function grabEnd(metaWindow, type) {
+    print("grabEnd", metaWindow && metaWindow.title, type);
     if (type === Meta.GrabOp.COMPOSITOR)
         return;
     grabSignals.destroy();
@@ -2247,7 +2250,7 @@ function getGrab(space, anchor) {
 
 // `MetaWindow::focus` handling
 function focus_handler(metaWindow, user_data) {
-    debug("focus:", metaWindow.title, utils.framestr(metaWindow.get_frame_rect()));
+    print("focus:", metaWindow.title, utils.framestr(metaWindow.get_frame_rect()));
 
     if (metaWindow.fullscreen) {
         TopBar.hide();
```

**Comment by GorrillaRibs** [comment] 2019-05-20 23:38
To respond to each point:
- I'd thought it was all input (I originally tested it with nautilus, so I didn't see keyboard input to the window still worked) It seems like keyboard input to the selected window still works after touching it, but touch and mouse input are frozen until I either open the overview or change window (super+arrows, alt-tab)
- I can open the overview either with the super key or a shortcut (super+s)
- I'm on gnome-shell 3.32 (on archlinux if that matters, though I don't think they modify gnome too much)
- I normally don't have a keyboard popup (my understanding is it isn't automatic on X11, but it is on Wayland)
- I don't see any JS  ERRORS in the log
- The new window is focused after opening and closing the overview

I couldn't reproduce it either on a wayland session, so it seems like it might be X11 specific. I do notice with the logging patch that when I touch a window a with SSD (or any window on wayland) I get grabBegin and grabEnd lines with the name of the window focused, but not with CSD windows on X. Maybe the X server itself would generate a signal that could be used?

**Comment by hedning** [comment] 2019-05-20 23:47
Right, that mirrors what we saw too (modulo the virtual keyboard, which in my experience is just extremely buggy), ie. the mouse being buggy, but keyboard input still working. We should probably make an issue with upstream (though, not entirely sure if it's mutter or gtk which is at fault here).

**Comment by GorrillaRibs** [comment] 2019-05-21 01:15
Since none of mutter's log levels seem to have anything useful, maybe the toolkit is requesting [this](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-move) or something similar? It might be worth asking someone on the gnome/GTK teams where would be the best place to report the discrepancy between wayland/X11 (or if it's the intended behaviour)

**Comment by olejorgenb** [comment] 2019-05-21 15:59
Well, the input doesn't get buggy in vanilla gnome, so it must be *something* we do? But we don't do much when simply activating a fully-visible tiled window. And we don't do *anything* when an already focused window is clicked..

Does it affect scratch windows too?

> modulo the virtual keyboard, which in my experience is just extremely buggy

If the keyboard somehow tracked the whole screen it would explain the freeze. But it should have a max height and it doesn't even show for gorrillaribs.. 

PS: It looks like that the keyboard might move (with animation) the focus window.

**Comment by jtaala** [comment] 2023-12-09 04:59
Closing as basic touchscreen support was added by #643 and #660 (including swiping to scroll/move the tiling viewport).

**Closed by jtaala** 2023-12-09 04:59 UTC
Labels: bug, upstream

**Comment by jinek** [comment] 2024-03-13 22:43
Still not much usable. Can we bring back this topic? @jtaala

**Comment by jtaala** [comment] 2024-03-13 22:50
> Still not much usable. Can we bring back this topic? @jtaala

I don't have a touchscreen and can't test/work on this one.  @Thesola10 does and I know he uses PaperWM with touchscreen and has some PRs which were merged recently re touchscreen dragging etc.

@Thesola10, feel free to reopen this one and/or create a new issue with updated info related to touchscreen use/issues.

**Comment by Thesola10** [comment] 2024-03-14 07:24
@jinek feel free to open a new issue clarifying what you feel is missing from PaperWM's touchscreen support.

**Comment by jinek** [comment] 2024-04-16 16:55
https://github.com/paperwm/PaperWM/issues/828
