### ISSUE TITLE
Stop moving mouse between monitors to "steal" focus

### ISSUE THREAD

**Issue by sound-friend** [paperwm/PaperWM#933] opened 2024-08-23 20:51 UTC
**Is your feature request related to a problem? Please describe.**
not sure if this is intended behaviour, but it's aggravating when i have multiple monitors that when i switch between them, my focus is automatically switched to that monitor and the last window open. i typically select an item to copy, and copy it as i'm moving to the other monitor. this makes me miss a lot of copies, as well as other motions.

**Describe the solution you'd like**
a togglable switch to "change focus to current monitor only when clicked"

i didn't see a current option in there, but if there is, i'll close this issue. thanks for such an innovative way of managing the desktop?

**Comment by jtaala** [comment] 2024-08-24 04:14
Unfortunately, this is a constraint for implementing for "per monitor workspaces" (note: gnome doesn't do per monitor workspaces).  You can read about this constraint here https://github.com/paperwm/PaperWM/issues/389#issuecomment-1911089672.

Closing this issue as a duplicate of #389.

In short, the only way to disable this would be to not do "per monitor workspaces" (and would mean a pretty much a rewrite / reimplementation of many paperwm concepts).  Unfortunately, multi-monitor support still has issues in PaperWM (and is currently paperwm's archilles heel).  Interestingly, this was one of the reasons (gnome, or more specifically mutter, workspace/monitor constraints) niri dev was started.

Closing as duplicate of #389.

**Closed as completed by jtaala** 2024-08-24 04:14 UTC
Labels: enhancement

**Comment by sound-friend** [comment] 2024-08-24 04:19
wow, i didnt realize how complicated this issue was! thanks for that! ill
investigate further and try to adapt my workflow to account for this
barrier.

**Comment by jtaala** [comment] 2024-08-24 04:24
Well, it's still something that we hope will be addressed in gnome itself (in which case we can align with gnome instead of fighting it).  We've just had no luck here - I've actually considered forking a simpler paperwm which doesn't do "per monitor workspaces" - which would alleviate/resolve these multi-monitor issues, but would make paperwm work very differently (the good parts) for multi-monitors.

**Comment by sound-friend** [comment] 2024-08-24 04:31
interesting. quick question: with the gnome using one workspace for all
monitors, how does that work if there's an option for "workspaces on
primary display only"? from a naive interpretation, it seems that that mode
would have to be on separate workspaces, one for the primary, and one for
the rest.

**Comment by jtaala** [comment] 2024-08-24 10:05
Well, a workspace in mutter is just a logical grouping of windows.  

Essentially, in primary display only, when "switching" workspaces, windows on the non-primary are changed to the same grouping when any workspace is activated (i.e. coming out of overview or when "switching workspace"), e.g. with functions like `metaWindow.change_workspace`.  

So, when a workspace is activated, all windows (across monitors) are on the same workspace (or logical grouping) again.  Once out of overview etc, you can drag them across monitor boundaries, like it's one big workspace (because it is), e.g. one workspace across monitors (normal gnome behaviour).

You can see/check this by using looking glass (`alt`+`f2`) and selecting different windows on the different monitors and running `.get_workspace().index()` (in the evaluator) on those windows (metaWindow) - you'll see they're all actually on the same workspace index no matter what workspace to switch to.
