### ISSUE TITLE
Creating undefined var in user.js cripples keyboard

### ISSUE THREAD

**Issue by Dan733** [paperwm/PaperWM#362] opened 2020-12-27 21:39 UTC
Hello, 

Earlier this morning I was attempting to set certain programs to always open in scratch by editing the user.js file. After editing and saving the file, then restarting, I got an error that I had an undefined variable. I tried to open the file to remove the incorrectly typed line, and found I could not type. I have found that my keyboard does not work, except for a few shortcuts which I never set;
- "A" opens the app drawer
- "S" opens the launcher
- "L" logs out

Other than these shortcuts, the keyboard is unresponsive. Steps I have taken to try and fix the problem:

- remove the undefined variable
- reinstall paperwm from the login screen where keybaord still works (installs, but gives error GDBus.Error.org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell was not provided by any .service files something went wrong:)
- completely delete and reinstall the gnome shell

I am not a programmer, and would greatly appreciate any help you could give to solve this issue, as my laptop is currently unusable other than the right click menu.

**Comment by hedning** [comment] 2020-12-27 21:47
Sounds like your `Super` key is stuck (`Super+S` is a default keybinding for the launcher for instance).  I'd try to disable paperwm (`gnome-extensions disable paperwm@hedning:matrix.org` from the tty/login-screen to make sure the problem is actually paperwm.

**Comment by Dan733** [comment] 2020-12-27 21:52
Apologies, I should have noted I  already tried and disabled paperwm before reinstalling it. I think it edited my system files somehow. 

I do not believe the super key is stuck as pressing it also brings up the switcher. Also, when viewing keyboard shortcuts in settings, every one is marked as disabled and greyed out. 

I am using Ubuntu 20.04

**Comment by hedning** [comment] 2020-12-27 21:57
So the keyboard works when paperwm is disabled, and stops working when enabled (even after fixing the undefined var problem in  `user.js`)?

In that case sharing your `user.js` file might be helpful.

**Comment by Dan733** [comment] 2020-12-27 22:11
The problem persists when paperwm is disabled. However, as this issue began immediately after editing my user.js and restarting, I believe it was caused by paperwm. Of course, I'm no expert so I could certainly be wrong.

**Comment by Dan733** [comment] 2020-12-27 22:54
The settings of extension paperwm@hedning:matrix.org had an error:
```
Error: Expected type struct for Argument 'key' but got type 'undefined'
```

Stack trace:
```
parseAccelerator@/home/danielw/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:640:29
addKeybinding@/home/danielw/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:666:37
SettingsWidget/<@/home/danielw/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:257:17
SettingsWidget@/home/danielw/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:256:14
buildPrefsWidget@/home/danielw/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:751:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by olejorgenb** [comment] 2021-01-30 17:53
Hi, I hope the issue was resolved?

If the issue persist when paperwm is disabled, it's *very* likely to be something else (unless you've put something very exotic in your user.js :sweat_smile:). The default install script do change some gnome-settings, but none of these could possibly have this effect. The install script should've generated a `restore-gnome-shell-settings-*.sh` file. Run this to restore the settings changed.

To verify for sure that no paperwm code runs: disable paperwm, reboot and run `journalctl --boot | grep -i paperwm`. No output -> no paperwm code should've ran.

Sounds like you managed to disable paperwm using the mouse? If not - run this from a VT (ctrl-alt-F3): `rm ~/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org`

The output of `dconf dump /org/gnome/desktop/wm/keybindings/` miiiight help.

The settings error: does it start at all? Posting the result of `dconf dump /org/gnome/shell/extensions/paperwm/` would be helpful.

I'll close this. Will reopen if new information is provided :)

**Closed by olejorgenb** 2021-01-30 17:53 UTC
