### ISSUE TITLE
Multi-Display support doesn't seem to work

### ISSUE THREAD

**Issue by ganthern** [paperwm/PaperWM#88] opened 2018-11-06 21:27 UTC
Hey,
I'm using PaperWM with gnome-shell 3.30.1 under Wayland, and I can't get any windows to appear on my second display, be it by dragging or with shortcuts.

From the other issues it's not quite clear to me what the status on this is, so my apologies if this feature is WIP/planned.

Cheers

**Comment by hedning** [comment] 2018-11-11 09:16
I'm unable to reproduce on 3.30.1 too. Can you confirm that you're using `Workspaces span displays`?

**Comment by ganthern** [comment] 2018-11-11 10:46
yes, I have workspaces set to span displays. Turning that off produces a whole other kind of weirdness. I'll try getting some debugging in, my setup is probably a bit nonstandard since it's gnome on arch. 
The second screen won't really be in use for a few more weeks anyway.

**Comment by hedning** [comment] 2018-11-23 19:43
OK, things should work with `workspaces only on primary display`. `3.30` changed some schema names: 0b75e92e5087ae43c0ec016d680fc326f050c647

**Comment by hedning** [comment] 2018-11-23 23:20
Tried out scaling one of the displays, that seems to make it difficult or impossible moving windows from one display to another. I'm guessing that's the issue you're running into?

I'm still able to create new windows on both displays though (eg. from the overview or using dash-to-dock's `super+nr.` bindings), as long as the correct display has «focus» (ie. the display with the top bar).

**Comment by ganthern** [comment] 2018-11-24 11:40
I don't have any scaling enabled, I'm using two 1080p displays.
With the newest commit it seems to work fine now. I can move windows between the displays with super+shift+arrows or with the mouse. My current workspace settings are 2 static workspaces with ` workspaces span displays`. 
`workspaces only on primary` doesn't work at all.
Thanks!

**Comment by hedning** [comment] 2018-12-08 12:04
There's an issue with scaling, but the basic support should work, so closing this.

**Closed by hedning** 2018-12-08 12:04 UTC
