### ISSUE TITLE
Instant "Switch to Window."

### ISSUE THREAD

**Issue by Plyply99** [paperwm/PaperWM#940] opened 2024-08-31 07:12 UTC
Currently when using hotkeys to switch to a different window there is a pause and the unfocused windows darken.

Would it be possible to make the switch instant? Here is a clip of what I mean. Note the switch to another window is instant with no delays.

https://github.com/user-attachments/assets/f6d7ff5a-284d-43e0-8b7f-77b81c13a64c

**Comment by jtaala** [comment] 2024-09-01 11:17
> Would it be possible to make the switch instant? Here is a clip of what I mean. Note the switch to another window is instant with no delays.

Yes.  So, the darkening non-selected windows is linked to the showing of the minimap (which you might not use).  I suppose we could separate the delays for showing the minimap and darkening windows (and could make both timeouts user-settable (e.g. add them to advanced settings in PaperWM).

Anyways, you can change this timeout here (currently set to 200ms):

https://github.com/paperwm/PaperWM/blob/2c3e76a63951fa2f278e89ffc9cacfa59e5fe994/navigator.js#L333

Feel free changing this to `0` and see how it feels.

**Comment by Plyply99** [comment] 2024-09-01 12:24
I tried setting it to 0 millisecs and it seems a bit better maybe. 
Feels like the switch focus is tied to the release of the super key. I use Super+Arrows to move window focus.
Here is another clip.

https://github.com/user-attachments/assets/122f2af5-b331-49fd-b360-e143f92b71db

What I want is for the focus to change instantly with no darkening and not be tied to release of Super key.

**Comment by jtaala** [comment] 2024-09-01 12:45
> What I want is for the focus to change instantly with no darkening and not be tied to release of Super key.

So, switching is instant (always has been), darkening is linked to the minimap (which has a delay).  Darkening can be disabled too btw (see that to `0`):

![image](https://github.com/user-attachments/assets/a67049fb-7d69-411c-bd75-f5cc66a24120)

I can't see any delay in your videos though (since I can't see when you're pressing a button).

> for the focus to change instantly with no darkening and not be tied to release of Super key.

That's exactly what happens, it isn't bound to the release - if that isn't happening for you, then it sounds like there's something interfering with that keybind.

**Comment by jtaala** [comment] 2024-09-01 12:50
Can you change the keybind as a test?  Also what happens if you hold the keybind down? (just checking if it quickly moves through all windows or stops?).

**Comment by Plyply99** [comment] 2024-09-01 13:08
Thank you for the dimming to 0! That helps.
Tried changing to different key bind and same result. 
1) Hold modifier key and use arrows to change focus. 
2) While modifier key is held down it puts windows in a alternate state, (not sure how to say this) until modifier key is released. It's quite noticeable when using transparency.

https://github.com/user-attachments/assets/037b88d1-238d-41e0-a7f7-919fef67452c

**Comment by jtaala** [comment] 2024-09-01 13:12
Okay, quick one, did you specifically turn off the mini-map? (I notice it's not showing).

For testing, can you please enable the minimap (which is the default setting) - you should see the instant windows switch, then 200ms later the minimap should appear (if you're still holding the `super` key down).  

That'll help me see if it operating as it should be (or if there's something interfering with it).  Here's how to set the minimap size (setting to `0` disables the minimap):

![image](https://github.com/user-attachments/assets/78d152ea-06ef-403f-866d-d3a698e8ab67)

**Comment by Plyply99** [comment] 2024-09-01 13:21
Yes I had minimap turned off. Here is turned on.

https://github.com/user-attachments/assets/f7cd48f1-d829-4cfd-86ab-b403b130894e

**Comment by jtaala** [comment] 2024-09-01 13:25
I see, something is happening there that's not normal PaperWM behaviour.  First up, can you please paste info from the about tab in settings (so I can see version etc.).  E.g.

![image](https://github.com/user-attachments/assets/c0c9cda1-4a40-43ca-b8b5-ab50245919a4)

**Comment by Plyply99** [comment] 2024-09-01 13:30
Distribution: Fedora Linux 40 (Workstation Edition)
GNOME Shell: 46.4
Display server: Wayland
PaperWM version: 46.17.0
Enabled extensions:
- user-theme@gnome-shell-extensions.gcampax.github.com
- desktop-cube@schneegans.github.com
- clipboard-indicator@tudmotu.com
- just-perfection-desktop@just-perfection
- gradienttopbar@pshow.org
- blur-my-shell@aunetx
- weatheroclock@CleoMenezesJr.github.io
- osd-volume-number@deminder
- notification-timeout@chlumskyvaclav.gmail.com
- caffeine@patapon.info
- AlphabeticalAppGrid@stuarthayhurst
- monitor@astraext.github.io
- krypto@sereneblue
- quick-settings-tweaks@qwreey
- color-picker@tuberry
- gsconnect@andyholmes.github.io
- paperwm@paperwm.github.com
- extension-list@tu.berry

**Comment by jtaala** [comment] 2024-09-01 13:38
Thanks - for testing purposes (to rule out extension conflicts, which I'm thinking may be the issue here), can you disable all other extensions (again, to try isolate the issue) and just have paperwm enabled - then logout/login (important as need to unload all other extension code).

For reference, windows should be actually activated (not just selected and then activated on key-release) when switching, e.g.:

https://github.com/user-attachments/assets/1fecb43b-fbc0-43f2-bb6c-46b0ffa24bac

Another thing to test (and rule out) is `focus-follows-mouse` or `focus-on-hover` behaviours (e.g. just try switching to default `Click to Focus` just to see if still can reproduce the switching issue here).

**Comment by Plyply99** [comment] 2024-09-01 13:47
All extensions off except PaperWM, getting same results.
EDIT: Focus on hover is off also.


https://github.com/user-attachments/assets/c5ae2cb7-7db1-4ba8-8dfc-b499e29c3f96

**Comment by jtaala** [comment] 2024-09-01 13:58
Hmmm - can't reproduce (and haven't seen this before).  But def something is stopping the full activation of windows on selection on your setup (which is not normal paperwm behaviour).

Unfortunately, when we get to this point, and we can't reproduce, it's often some non-extension changes or other customisations for the environment.

If you get a chance (and have the motivation), I'd suggest creating a new user (just for testing and trying to isolate the issue) - log into that new user (should then be running vanilla gnome with default settings), just install paperwm and check you are still seeing the same thing.

Let me know if you have any luck in finding any other hints/tips that I can try to reproduce this.

I thought it might be something in Fedora 40, but I've got it up and running on my vm, and still can't reproduce what you're seeing.

**Comment by Plyply99** [comment] 2024-09-01 14:07
I'll keep testing it. I do appreciate very much your time.
PaperWM is still awesome!

**Comment by Plyply99** [comment] 2024-09-01 14:22
Ok setup new user and getting same results. I have to let go of Modifier Key.

https://github.com/user-attachments/assets/42a8d031-59a9-4e12-ad58-365ec9281748

**Comment by jtaala** [comment] 2024-09-01 14:40
Wait, that one looks fine (it at least different from your previous video).

You'll note in your previous video (easier to see when minimap is up), that switching to a window with keybind didn't change the white border to the selected window until you released the keybind (and the minimap closed).

In the new user video, it changes instantly as you select a window (as it should).

**Comment by jtaala** [comment] 2024-09-01 14:41
The border indicates which window is selected/activated, and should be updated to the new selected window instantly (no delay).

I may be misunderstanding what you mean or are after then.

**Comment by Plyply99** [comment] 2024-09-01 14:52
Right the border moves instantly. But the actual focus change happens after release of Modifier Key. You can see that by the color change of the app when in focus.
As an example, I use hotkeys for my most used apps. 
1) I change window focus with Super+Arrow
2)  While still holding down Super also press T to open my text editor Emacs. It will not work. I first have to release Super for the focus change to complete. Then I can Super+T to open Emacs.

**Comment by jtaala** [comment] 2024-09-01 15:00
I see, sounds like you want to destroy the navigator and keyboard modal hold on each window selection.

**Comment by Plyply99** [comment] 2024-09-01 15:02
Yes! That's it.

**Comment by jtaala** [comment] 2024-09-01 15:11
That'll make window switching a one-shot operation, and now makes sense why you don't use the minimap (since a one-shot operation would close the minimap, or just make it not applicable).

Will leave this one up as a request.  But a well placed `Navigator.getNavigator().finish()` at the end of the `tiling.switch` method would probably do this.

**Comment by Plyply99** [comment] 2024-09-02 17:12
I found an extension that only does switch window focus and it works perfectly with PaperWM.
https://extensions.gnome.org/extension/4627/focus-changer/

Thanks again for your help jtaala.

**Comment by jtaala** [comment] 2024-09-07 05:17
Nice find!  That extension work very well if you want this kind of switching in PaperWM.  So much so, that I wouldn't implement this type of switching into PaperWM specificall (I don't use it, and would need new options and probably some keybind modal refactoring etc).

Will close this one now.

**Closed as completed by jtaala** 2024-09-07 05:17 UTC
Labels: enhancement
