### ISSUE TITLE
When android emulator is started PaperWM gets messed up

### ISSUE THREAD

**Issue by likern** [paperwm/PaperWM#214] opened 2019-12-22 07:32 UTC
When I start emulator supplied by Android Studio PaperWM starts behaving incorrectly.
I recorded a videos to show the problem.

https://drive.google.com/file/d/1suTmT8-eZqENp_XNsxUPwSNyPluKLXpZ/view?usp=sharing

**Comment by likern** [comment] 2019-12-22 07:37
I'm not sure, but it looks like after that I have other consequences like:

- [ ] When I open context menu with mouse (say in file manager) and try to navigate to some element in menu - the focus of element is lost (even if mouse still under that element)

- [ ] When I play video in Chrome I see mouse twitching (it repeatedly changes mouse icon from arrow to hand)

**Comment by hedning** [comment] 2019-12-22 17:55
I'm unable to reproduce on gnome-shell 3.34.2 xorg. What gnome-shell version are you running, and are you  on wayland or xorg?

**Comment by likern** [comment] 2019-12-23 12:22
@hedning Hello! Thank you for your reply.

> I'm unable to reproduce on gnome-shell 3.34.2 xorg. What gnome-shell version are you running, and are you on wayland or xorg?

I'm using latest Fedora version without substantial modifications:
```bash
[me@localhost ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
```

```bash
[me@localhost ~]$ gnome-shell --version
GNOME Shell 3.34.2
```

```bash
[me@localhost ~]$ loginctl show-session 2 -p Type
Type=wayland
```

**Comment by hedning** [comment] 2019-12-24 01:20
Yep, I'm able to reproduce on wayland. Looks like the window reacts badly to being told to resize just its height, increasing the width will update the height, which seems to be a workaround. We'll probably need some custom handling of the window to get it to work out of the box unfortunately.

**Comment by hedning** [comment] 2020-01-24 12:06
Another workaround is disabling the «device frame» for the virtual device. This gives you a native title bar, and seems to play nice with paperwm no matter the size of the window.

**Comment by likern** [comment] 2020-01-24 18:36
@hedning Thank you very much! I've tried proposed solution. It works, but I've found some other bugs (I don't know is it a problem with emulator or PaperWM):

- [ ] If I try to hide emulator menu (flickeering is not visible on video, but it exists) - [Bug 3](https://drive.google.com/open?id=1L1qwDtBmR_8bUmyTIBDfWxarmqaQ3_jt)
- [ ] If I try to move emulator from it's menu (so they do not overlap) and navigate between windows - [Bug 2](https://drive.google.com/open?id=1EMpqW_7mNKVp9N--NJq0cRb5vt99TMMM)

And I've found some strange bug (I've caught it only once, can't figure out it's root) - [Bug 1](https://drive.google.com/open?id=1wU4K-_6TocB9U2jgXs17BdNvNNDGim2G)

**Comment by hedning** [comment] 2020-01-25 18:58
1. Hmm, it looks like the window is probably caught in its clone state, potentially after a resize, for some reason (when animation we use clones instead of the original window, substituting as required).
2. Yep, long lived modals/transients aren't handled all that well tbh. Ideally the menu would be docked (#50) at a monitor edge or perhaps even better tiled/docked to the emulator window.
3. Yeah, minimizing the menu seems to trigger a minimize of the emulator too, which apparently just triggers the emulator to be reattached (as it marks itself as not minimizable). I can observe the same behavior in plain gnome-shell, so not sure if there's much to do about it from our end.

I'll most likely make a fix for the menu (some sort of docking/tiling) pretty soon, as I'm going to be using android-studio a bit the few months :)

**Comment by likern** [comment] 2020-01-25 19:26
@hedning Thank you very much for your support. I highly appreciate your work and use it every day by default.

**Comment by hedning** [comment] 2020-01-25 19:44
Cheers :) I'm glad you're finding it useful.

**Comment by jtaala** [comment] 2024-01-29 22:27
Haven't been able to reproduce this on later version of PaperWM.  Will close this issue as outdated.  Let me know if this is still an issue.

**Closed by jtaala** 2024-01-29 22:27 UTC
Labels: bug
