### ISSUE TITLE
Setting "Top margin" to 0 shrinks the selected-window border to zero width

### ISSUE THREAD

**Issue by ankostis** [paperwm/PaperWM#893] opened 2024-07-14 23:14 UTC
**Describe the bug**
After i bumped to gnome-shell from 45 -> 46, i lost the ability to affect the settings of the border, rounded corners etc with the preferences UI.  It's as if there is another source of configuration controlling these.  I tried modifying `.config/paperwm/user.css` but didn't work either.  

I notice that there is a _small_ border visible, so it's not that it's not working, it's that my configs are ignored:
![image](https://github.com/user-attachments/assets/3f66d058-a5e9-4c6e-9525-9c202ec308de)

- I would like to uninstall and re-install PaperWM to reset the settings but i don't know how to keep my keyboard bindings?
- Any other idea where to search for configs?

Distribution: Debian SID+Experimental
GNOME Shell: 46.1
Display server: Wayland
PaperWM version: 46.13.2
Enabled extensions:
- drive-menu@gnome-shell-extensions.gcampax.github.com
- apps-menu@gnome-shell-extensions.gcampax.github.com
- places-menu@gnome-shell-extensions.gcampax.github.com
- notification-position@drugo.dev
- workspace-indicator@gnome-shell-extensions.gcampax.github.com
- flypie@schneegans.github.com
- paperwm@paperwm.github.com
- switcher@landau.fi
- quick-lang-switch@ankostis.gmail.com
- ```

**Comment by jtaala** [comment] 2024-07-15 08:58
mv .config/paperwm .config/paperwm_backuphmm,

Can you paste the output of `ls ~/.local/share/gnome-shell/extensions/` and also `cat ~/.local/share/gnome-shell/extensions/paperwm\@paperwm.github.com/metadata.json`.

Settings in PaperWM are in:
- dconf
  - if you install `dconf-editor` you can then run the following to see / change the settings;
  ```
  GSETTINGS_SCHEMA_DIR=::$HOME/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas dconf-editor /org/gnome/shell/extensions/paperwm/ &>/dev/null
  ```
  - `~/.config/paperwm`

I would suggest deleting/moving `~/.config/paperwm`, e.g. first try a:
```
mv .config/paperwm .config/paperwm_backup
```

then logout and login and see if you can then change the border etc. via PaperWM settings.

Let me know how that goes - that will tell us if it's the `.config/PaperWM` settings or not.

**Comment by ankostis** [comment] 2024-07-15 13:45
```shell
$ ls ~/.local/share/gnome-shell/extensions/
advanced-alt-tab@G-dH.github.com
apps-menu@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
flypie@schneegans.github.com
fullscreen-to-empty-workspace@aiono.dev
launch-new-instance@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
notification-position@drugo.dev
paperwm@paperwm.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
quick-lang-switch@ankostis.gmail.com
quick-lang-switch@local
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
smart-auto-move@khimaros.com
switcher@landau.fi
tiling-assistant@leleat-on-github
user-theme@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
```

```shell
$ cat ~/.local/share/gnome-shell/extensions/paperwm\@paperwm.github.com/metadata.json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Tiling window manager with a twist",
  "donations": {
    "buymeacoffee": "jaytaala",
    "patreon": "valpackett"
  },
  "name": "PaperWM",
  "settings-schema": "org.gnome.shell.extensions.paperwm",
  "shell-version": [
    "45",
    "46"
  ],
  "url": "https://github.com/paperwm/PaperWM",
  "uuid": "paperwm@paperwm.github.com",
  "version": 119,
  "version-name": "46.13.2"
}
```

I will delete now  `~/.config/paperwm` and relogin.

**Comment by ankostis** [comment] 2024-07-15 14:06
Moving the `~/.config/paperwm` didn't help - i had to reset-recursively dconf nodes.  And then...

**i realized that the border it not visible when _Top margin_ or _Bottom margin_ settings are set to 0!**

Now i need to restore my keys which seem to have been store only in the dconf registry, restoring `~/.config/paperwm` didn't restore those :-(
(but my main mystery in this issue has been solved)

**Comment by jtaala** [comment] 2024-07-16 11:15
Well, bad news is that reset-recusively dconf nodes resets PaperWM user settings (keybinds, options etc.).  That isn't recoverable unless you have a backup of the dconf settings.

**Comment by jtaala** [comment] 2024-07-16 11:20
> i realized that the border it not visible when _Top margin_ or _Bottom margin_ settings are set to 0!

That still sounds like something is not quite right there.  ~~Simply setting these to `0` should remove the window border:~~

![image](https://github.com/user-attachments/assets/079a9c0d-98c7-41cf-a08b-228fbb97b978) ~~

~~ Can you paste a screenshot of your border | gap | margins settings (like my pic above)?  I can then try reproduce what you're seeing.

**Comment by ankostis** [comment] 2024-07-16 12:38
These 2 settings you have screenshotted do not have any impact, have experienced extensively.  It's the 2 settings near the bottom of your image, about the Top/Bottom margins that when they are set to 0 they don't allow for the border to appear. 

I'm not in front of the PC for the screenshot, but i have presented how it looks when they are 0 in my Opening Post.

**Comment by jtaala** [comment] 2024-07-16 12:45
The opening screenshot doesn't really tell me anything about your actual border, margin settings (e.g. it's not really helping much) - so without those I won't be able to reproduce what you're seeing (I can't reproduce this behaviour currently).

I'm guessing it's a clash with something in those settings and your `.config/paperwm/user.css`, or something in your current border, margin settings that's hitting a corner case for showing the border.

Anyways, if you can, zap me a pic of your current settings and maybe the output of your `user.css` file.  Basically so I can reproduce and fix.

Cheers.

**Comment by jtaala** [comment] 2024-07-16 12:50
> > i realized that the border it not visible when _Top margin_ or _Bottom margin_ settings are set to 0!
> 
> That still sounds like something is not quite right there. Simply setting these to `0` should remove the window border:
> 
> 
> Can you paste a screenshot of your border | gap | margins settings (like my pic above)? I can then try reproduce what you're seeing.

oops - my bad, those settings I put in my pic is for the border radius :face-palm:

it should be this setting that you just need to set to 0:

![image](https://github.com/user-attachments/assets/0beb6408-94ee-4c2a-9b00-9c1a88287c0d)

**Comment by ankostis** [comment] 2024-07-16 14:54
No.  That's the setting that is not working as expected when set to a non-zero value and the margins are 0.

[Edit]My user.css is untouched.

**Comment by jtaala** [comment] 2024-07-16 21:50
> No. That's the setting that is not working as expected when set to a non-zero value and the margins are 0.

I understand that.

I can't reproduce this, so that's why I've been asking for specific pieces of information.  If we can't reproduce this, then there's little chance the cause in your case can be isolated and fixed.  So, I'm trying to isolate the cause.

So, with the little bits of information you've provided, I've been ruling things out.  e.g.
- it looks like you're running the latest version (so it's likely not that);
- it looks like you've cleared/reset `user.css` (so it's likely not that);
- sounds like you've cleared/reset dconf settings (so it's likely not that);

Next up, please send me a pic of your margin | border settings (e.g. just like the pic I've pasted previously).  I'd like to replicate your precise settings to see if I can reproduce the result that you're seeing (and hence deduce/isolate the potential causes).

Following that - I'd probably then try to replicate your precise extensions you have installed (another possibility could be an extension / styling conflict).  Actually, we can rule that out, if you can disable all extensions except PaperWM and then see if the issue is still there.

Cheers.

**Comment by jtaala** [comment] 2024-07-16 21:59
> [Edit]My user.css is untouched.

So, there's been different default versions of `user.css` that gets generated in PaperWM.  To rule out conflicts here, can you confirm your `user.css` look precisely like:

```
/*
Users may override the default PaperWM styles to suit their preferences.
Added custom styling in this `user.css` file.

`Disable` and then `enable` PaperWM extension to apply these styles 
(users do NOT need to logout / login).

DEFAULT STYLES ARE PROVIDED BELOW FOR REFERENCE:
/*

/*
.background-clear {
    background-color: rgba(0, 0, 0, 0);
}

.topbar-transparent-background {
    background-color: rgba(0, 0, 0, 0.35);
    box-shadow: none;
}

.space-workspace-indicator {
    padding: 0 10px 0 0;
    background-color: transparent;
    border-image: none;
    background-image: none;
    border: none;
}

.space-focus-mode-icon {
    icon-size: 16px;
    padding: 0 18px 0 18px;
    margin-left: 3px;
    background-color: transparent;
}

.focus-button-tooltip {
    background-color: rgba(0, 0, 0, 0.8);
    padding: 8px;
    border-radius: 8px;
    font-weight: 600;
}

.workspace-icon-button {
    -st-icon-style: symbolic;
    border: none;
    border-radius: 8px;
    padding: 8px;
}

.workspace-icon-button StIcon {
    icon-size: 16px;
}

.paperwm-minimap-selection {
    border-radius: 8px;
}

.paperwm-window-position-bar-backdrop {
    background-color: rgba(0, 0, 0, 0.35);
}

.paperwm-window-position-bar {
    border: 0;
    border-radius: 1px;
}

*/
```

_Note: the above should all be commented out, so it's equivalent to an empty file_.  Let me know if it looks any different to the above.

**Comment by jtaala** [comment] 2024-07-16 22:08
Alternatively, you can just run:

```
sha256sum ~/.config/paperwm/user.css
```

It should output something like:

```
8d3bb0667ae04a38ec3e32493e9a0050cc53d5b8fbed713b2a0f150009870d00  /home/jay/.config/paperwm/user.css
```

Let me know if the first part in your output is any different to the above.

Thanks @ankostis for helping to debug what you're seeing!

Cheers.

**Comment by jtaala** [comment] 2024-07-16 22:19
Just pasting this here for my notes and reference:

https://github.com/paperwm/PaperWM/issues/867
https://github.com/paperwm/PaperWM/pull/868

Note, that `paperwm-selection` management/control in `user.css` has changed - that's why I've asking to know about `user.css`.  It'll be much easier if you can paste the content of your `user.css` here so I can confirm/rule-out that as the cause.

**Comment by ankostis** [comment] 2024-07-16 23:07
(Now that i returned to my home-town...)
Yeap, `user.css` is "kind of empty" like above:

```shell
$ sha256sum ~/.config/paperwm/user.css
8d3bb0667ae04a38ec3e32493e9a0050cc53d5b8fbed713b2a0f150009870d00  /home/ankostis/.config/paperwm/user.css
```

And these are my settings's screenshot that manifest the "zero-width border" [edit: uploaded a 2nd screenshot]:
![image](https://github.com/user-attachments/assets/976dd958-7d46-4fda-86ff-eb67fee5e142)
![image](https://github.com/user-attachments/assets/72c9e0da-148d-4c96-a873-4079bb9e558a)
- Actually, it's enough to set the _"Top margin -> 0"_ for the border to dissappear.
- The radius settings do not have any impact.

Some more comments:

- Noticed that the sample `user.css` does not contain the border customization.
- Is there a customization in `user.css` to distinguish between the border of the _selected_ window of a monitor vs the _active_ window (the one across all monitors)?

Finally, some more debug infos in case they are of any use:

```shell
$ sha256sum  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/config/*
8d3bb0667ae04a38ec3e32493e9a0050cc53d5b8fbed713b2a0f150009870d00  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/config/user.css
11a8babfe2be5f5a6c60733c9067fb09810c2bb5919267151f9b6a1714b0ddea  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/config/user.js

$ sha256sum  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/*
34a95545562e6fadcddf8144db910ce18a7e8188ffe3b2e8e1cb45c66ab4369b  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/acceleratorparse.js
2d7cff1f08bd77a08f595921c17660347c9184c83f8e47b7de9a72cefa46ab20  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/app.js
7d1e85de4fc0450e0aaabada4ccbb6d45847f377135c61ba479347dbbbd9ddd8  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/background.js
sha256sum: /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/config: Is a directory
9314f7647a7cecd5aff75e39ce780088b32369c08764dfe0198b755f01c7e07c  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/extension.js
94b481c3e57e60631ff7c3234b679685322c5c0a37b39e0e50cf72654252c8ce  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/gestures.js
1736c9e06c0f61e405f53bf0b3c1063d5d8cbee6aeee468a5690b75db3285885  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/grab.js
2d961bf16eb898dc5f85ec1b80492daeffe71373817b9db4ae638f3aaa91be20  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/imports.js
a3b04b0d94671b5c5d7f6f8b9994adaf3a4b86df3fabb5df8d36137141fbf63f  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/KeybindingsComboRow.ui
f5427bec81f7e9008c6d273a421ef876c98716a11e47e18a627e734585c820b6  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/keybindings.js
af4994cc05b46d2cae57945ace73a7c17d10699f061e71bc057cc1739818fbce  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/KeybindingsPane.ui
2e2202bede9c786e7a21a317a6376da2d8c9ab71fa67ce9327a4d7f05f081ef1  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/KeybindingsRow.ui
a1fa76a5856e0e4245c46ed8a34812752555e1ae36439e8652e60fd1275456c2  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/lib.js
589ed823e9a84c56feb95ac58e7cf384626b9cbf4fda2a907bc36e103de1bad2  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/LICENSE
477a31644b2568cc84f26846dcc4ded00c424b4c5c5fbc5915b4ac8e44953ab7  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/liveAltTab.js
dd0569ce3fd2719cbad40691f70ed5989e0e3b79b0cae3ecc91e4cc7f4492050  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/metadata.json
61a735c82165a27e5ea09375909dade0ef27e210fc521aa1b74028071a817b8d  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/minimap.js
46b8e1df9d12fbade310df7cd3c663b5267ace0e58de07221c3f6ab242f68803  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/navigator.js
804123f33bbec655423aab3de77022b310430353c1b5cbe4c340475efdc75bfd  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/overviewlayout.js
930640cf29e88a62634a1d5e264da9f35146664e839229db490c0a40d1118fb4  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/patches.js
b18d87510f06b2ab65159fea377412da16a9b39e6e1cbadea2523f7e13ad1c98  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/prefs.js
92692c00ea796b2d06d01a0b5e78b68d5e75a4f47b63fda0be2da58f98aa3daf  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/prefsKeybinding.js
sha256sum: /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/resources: Is a directory
sha256sum: /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/schemas: Is a directory
ffb8512131cd4bb400b3810026378349f30929117d4c7171b3c727ab31eda800  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/scratch.js
db927c4ba054d28a2354516fd10ed1f9c262830852802c1686520816188ba8c3  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/settings.js
bb6d453e93d70a32e37700e29ea0dd6a6482d1527242a7f232d0c9df5851a246  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/Settings.ui
3fae6efe374d1bc3fae1b2403a09b44be677e24e6d7bc84ec413481ceaf85378  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/stackoverlay.js
0425405aeb65f6702da74a10c738266dd01ee4a7e15f59db38b3550ca56631f1  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/stylesheet.css
ad094d976fc582969bad1257ae94efd7246fef1ae43e480556ea0507180b7ae9  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js
97f40d349fb1678f64bd2a48c559fb602fcf6a7a38b234afd7d52a2c413cec2d  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/topbar.js
ad72fcb03ddc9becad7c1a600ab6c4bb4e1d1599cb20c215e8f7ecb2bc483780  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/utils.js
d9b733c0c4f2130f1a90db0a452aa859f7e5997897335e97c39324922324286f  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/virtTiling.js
76b83be0f137988cfb3e2f5c0b4c4537e908cc7a74ad4be33d2cdbe4d334bd8f  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/winpropsPane.js
0176ff5a2c6c097c7e2060311a07be460ff529a5a117891b9bae154b17c4973d  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/WinpropsPane.ui
9ffe292d99727e588c3b3fd4f8c9a5298d0a65a76e09d59bc7d2d812b0fccbb2  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/WinpropsRow.ui
a563776e777b1ab97a0d6da055b4bb2fb3dc63b9761626c3098d1eb5e53af1a2  /home/ankostis/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/workspace.js

$ ls /usr/share/gnome-shell/extensions/
apps-menu@gnome-shell-extensions.gcampax.github.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
light-style@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
system-monitor@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com

$ ls ~/.local/share/gnome-shell/extensions/
advanced-alt-tab@G-dH.github.com
apps-menu@gnome-shell-extensions.gcampax.github.com
drive-menu@gnome-shell-extensions.gcampax.github.com
flypie@schneegans.github.com
fullscreen-to-empty-workspace@aiono.dev
launch-new-instance@gnome-shell-extensions.gcampax.github.com
native-window-placement@gnome-shell-extensions.gcampax.github.com
notification-position@drugo.dev
paperwm@paperwm.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
quick-lang-switch@ankostis.gmail.com
quick-lang-switch@local
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
smart-auto-move@khimaros.com
switcher@landau.fi
tiling-assistant@leleat-on-github
user-theme@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com

$ gnome-extensions list --enabled
drive-menu@gnome-shell-extensions.gcampax.github.com
apps-menu@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
notification-position@drugo.dev
workspace-indicator@gnome-shell-extensions.gcampax.github.com
flypie@schneegans.github.com
paperwm@paperwm.github.com
switcher@landau.fi
quick-lang-switch@ankostis.gmail.com
```

Thank you for your persistence.

**Comment by ankostis** [comment] 2024-07-16 23:10
Additionally, i disabled all my other extensions (though not all of them at the same time, but in 3 groups) and the buggy behavior remained.

Puzzled that you cannot reproduce - could it be my x2 monitors?
(a comment in the known limitations may suffice then)

**Comment by jtaala** [comment] 2024-07-17 08:47
ah... so, with those settings you have - PaperWM is acting as it's designed.

It sounds like their might be some misunderstanding of what those settings do to the select window border though.

What are you trying to do exactly?  For example, if you want to hide the selected window border, just set the first setting to `0`:
![image](https://github.com/user-attachments/assets/dfed9cba-f311-4506-a9eb-2100a43c11dc)

Now the these settings just control the corner radius (or curve):
![image](https://github.com/user-attachments/assets/8a5b7e95-5f37-47f2-b321-a71c05519ca7)

So setting them to `0` will make them pointy/sharp, i.e. no curve.

Also setting any top/bottom margin to `0`, will by design, hide the selected window border (it's not a bug) - in other words, if you have 0 top/bottom margin - you have no "space" to show a window border.  In other words, if you want to show a border for the selected window - you'll have to create some "space" so it can show.

Anyways, let me know what you're trying to do exactly and I can point out the settings to change.

**Comment by jtaala** [comment] 2024-07-17 08:52
You can see some history of this in his PR: https://github.com/paperwm/PaperWM/pull/822

Which fixes this issue: [inconsistency between bottom margin and top margin calculation](https://github.com/paperwm/PaperWM/issues/817)

**Comment by jtaala** [comment] 2024-07-17 08:55
> * Is there a customization in `user.css` to distinguish between the border of the _selected_ window of a monitor vs the _active_ window (the one across all monitors)?

No, but PaperWM will "dim" the border of the non-selected monitor.

**Comment by jtaala** [comment] 2024-07-17 08:57
I think I was mostly confused about what you were actually trying to do - I thought you were just trying to turn off the selected window border (still not sure, but let me know if that's your goal).

**Comment by jtaala** [comment] 2024-07-17 09:04
> * The radius settings do not have any impact.

The radius setting just changes the corner "curves".  Here's video of various behaviours, hopefully that makes it clearer:

[Screencast from 2024-07-17 19-01-49.webm](https://github.com/user-attachments/assets/2e03c67a-e9db-4d61-ae22-307377c4a798)

**Comment by ankostis** [comment] 2024-07-17 10:00
> I think I was mostly confused about what you were actually trying to do - I thought you were just trying to turn off the selected window border

What I'm trying to do is occupy as much screen real estate as possible. Therefore I try to eliminate the top & bottom margins, but still let the gaps between the windows denote the active border - definitely not hide the border (that'd be easy to do just by setting its width to 0, as you wrote).

> Also setting any top/bottom margin to 0, will by design, hide the selected window border (it's not a bug) - in other words, if you have 0 top/bottom margin - you have no "space" to show a window border.

There is space in the gap between windows, even if top margin is 0.  Besides, the bottom margin do not have this side effect (hiding the border).  So at least, a note on the Top margin's GUI stating that "Setting this to 0 will hide the border" would alleviate this whole situation.  

> It sounds like their might be some misunderstanding of what those [corner radius] settings do to the select window border though.

Regarding the corner radius settings, there is a misunderstanding, indeed.  I wrote that they are irrelevant for me, not the that they are buggy and do not work.  I had set them 0 to render the active border visually more distinguishable but that's a .  Additionally I verified that modifying them does not fix the "border hidden when top margin is 0" bug in anyway. 

> No, but PaperWM will "dim" the border of the non-selected monitor.

Well, with 2 monitors, it is vital to know which window has the focus, eg. when you start typing after a break (there can only be one such windows across all monitors), so active & selection better support different colors/opacity css settings a well. 
- Should i  open a new issue for this RFE?

**Comment by jtaala** [comment] 2024-07-17 13:01
> * Should i  open a new issue for this RFE?

I'll close this one but feel free to open a new feature request describing the behaviour you're looking for.   I like the current design and behaviour - but, would definitely accept a PR if you have some ideas you'd like to implement and test.

Cheers.

**Closed as completed by jtaala** 2024-07-17 13:01 UTC
Labels: not-a-bug
