### ISSUE TITLE
TypeError: settings is undefined

### ISSUE THREAD

**Issue by holtzermann17** [paperwm/PaperWM#380] opened 2021-04-24 22:35 UTC
```
Stack trace:
  createWorkspacePage@/home/joe/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:320:63
  SettingsWidget@/home/joe/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:196:29
  buildPrefsWidget@/home/joe/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/prefs.js:751:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by jtaala** [comment] 2023-03-02 19:56
Closing as I can't reproduce and this is likely old or no longer an issue.  Pleased comment if this is still an issue and I can reopen and look into it.

**Closed by jtaala** 2023-03-02 19:56 UTC

**Comment by RichardFevrier** [comment] 2023-11-10 11:37
Got it today. But trying to re-enable the extension after this error makes it work.
Gnome 45
PaperWM 56

**Comment by jtaala** [comment] 2023-11-10 12:15
hmm - need some more details here:

1. what did this error result in? (e.g. paperwm could start... couldn't open peferencess?
2. what led up to this exception? (new login? etc.)?
3. how can I reproduce this error?

Also, your stacktrace would be different (for example line number would be different in Gnome 45 etc.).  Post your stracktrace here if you've still got it.
