### ISSUE TITLE
Failed to rebind keybindings using UI

### ISSUE THREAD

**Issue by Zhou-Yicheng** [paperwm/PaperWM#545] opened 2023-06-08 14:22 UTC
**Describe the bug**
Succeed to rebind `Super + Shift + >` to Switch to the right monitor
Failed to rebind `Super + Shift + <` to Switch to the left monitor

**To Reproduce**
1. Go to Extensions UI settings
2. Click on 'Keybindings'
3. Remove shortcut of 'Move the active window to the left'
4. Scroll down to 'Monitors'
5. Add shortcut for 'Switch to the left monitor'

**Expected behavior**
Shift to left monitor

**Screenshots**
FYI: '右' means right
![image](https://github.com/paperwm/PaperWM/assets/52224018/f840adfe-b52f-4552-a98c-1c0d0c802180)

**System information:**
```
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: v44.1.1
PaperWM commit: 5bf0e3e5387c9f69b795091d66678b6796190772
Enabled extensions:
- paperwm@hedning:matrix.org
- vertical-overview@RensAlthuis.github.com
```

**Comment by jtaala** [comment] 2023-06-08 22:57
Thanks @Zhou-Yicheng, that's interesting.

Can you confirm this also happens without the character 右 (i.e. use the `<` character representation) if that's possible.

Maybe an issue with the `Gtk.accelerator_parse` with diff lang characters? (it's used to  check against system keybinds that clash, then disable that system clash, and enable the PaperWM one) - e.g. might be that PaperWM doesn't detect them as equivalent, and hence won't disable the clashing gnome system keybind.

Just a guess, but will check this keybind on my system tonight.

**Comment by Zhou-Yicheng** [comment] 2023-06-09 16:21
> Can you confirm this also happens without the character 右 (i.e. use the `<` character representation) if that's possible.

I remove both '左' and '右' , and use `>` and `<` only. Same as before: Succeed to press `Super + Shift + >` to switch to the right monitor and failed to press `Super + Shift + <` to switch to the left monitor.

BTW, 左 is the representation of ← and 右 is the represention of →. They are default binding using arrow key.

**Comment by jtaala** [comment] 2023-06-09 23:20
Yep, I can confirm am seeing this with this particular keybind.  Thanks for reporting!

**Comment by jtaala** [comment] 2023-07-07 00:16
Okay, think I found the problem here.  Finally found it as part of #557 (since been looking at ways to ease reliance on `Gtk.parse_accelerator` (not sure if this is btw)... in any case, getting this error when trying to apply `<` keybind:

```
Jul 07 10:13:33 jay-blade gjs[1276284]: Failed to set text '<b>Shift+Super+Left, Shift+Super+<</b>' from markup due to error parsing markup: Error on line 1 char 45: “<” is not a valid name
```

So seems to be a keystring parsing issue!  I'll look at fixing this tonight (and then can carry on with #557).

**Comment by jtaala** [comment] 2023-07-15 05:42
Hey @Zhou-Yicheng - finally got around to fixing this.  

It's fixed in branch [`submission-to-extensions.gnome.org`](https://github.com/paperwm/PaperWM/tree/submission-to-extensions.gnome.org) - which we're planning on merging soon.

You can wait to that merge or if you wanted to text/have this fix now, you can checkout that branch and run the `install.sh` script again:

```
git fetch --all
git checkout submission-to-extensions.gnome.org
./install.sh
```

and logout/login.

**Comment by Zhou-Yicheng** [comment] 2023-07-15 06:47
thx! I will wait for the mergence.

**Closed as completed** 2023-07-18 21:13 UTC
Labels: bug, good first issue
