### ISSUE TITLE
Snap horizontal viewport to columns, including gaps, during swipes

### ISSUE THREAD

**Issue by winteriscariot** [paperwm/PaperWM#307] opened 2020-05-21 15:38 UTC
Steps to reproduce:

* open 1 window in an empty workspace, i use firefox. set it to fullscreen (super+f)
* open 2nd window in same workspace, I used Gnome Extension app. this should create a separate column to the right of firefox, pushing the firefox window to the left a bit
* swipe left-to-right to go back to firefox: you'll see the viewport snap to the window edge, NOT the gap edge, leaving the left edge of the window in the right column visible

It seems that the current behavior of horizontal viewport (that is, going right and left between columns) while using 3 finger gestures, is to snap to the edge of the _window_ after swiping left or right. Since the default config is to use window gaps (I prefer them myself) this means that the edge of the window it snaps to has no gap, meaning there's more space on the opposite side, and you can see the edge of the window in the column just to the right:

![image](https://user-images.githubusercontent.com/49098280/82575586-4b38f600-9b4e-11ea-8794-eb18ecbf02e6.png)

This becomes especially noticeable when you have multiple columns with split-width layouts (ie, no fullscreen). there doesn't seem to be any way to get the viewport to "snap" to the columns, meainng you can arbitrarily sit with portions of windows (ie columns) hanging off-screen

**Comment by winteriscariot** [comment] 2020-05-21 15:40
Here's a full screen screenshot, you can see on the left that the firefox window is flush to the edge of the screen, while there's a few pixels of the rightmost window visible:

![image](https://user-images.githubusercontent.com/49098280/82576616-7e2fb980-9b4f-11ea-9091-d711f7c9cd11.png)

**Comment by winteriscariot** [comment] 2020-05-21 15:42
I've also noticed that this occurs when you only have 1 window on a workspace: if i swipe left or right, i can't go left or right cuz there's no columns there, but swiping left or right will snap the edge of the single window to the left or ride sides of the screen

**Comment by winteriscariot** [comment] 2020-05-21 15:51
Couple more things:

* Using Super+,/. to move right and left through columns/windows results in the right or left-most windows snapped to the screen edge
* I have 'Horizontal margin' set to 20px (default i believe); it feels like horizontal scrolling ignores this margin (as there's no margin after horizontal scrolling)

**Comment by olejorgenb** [comment] 2020-05-23 07:24
> it looks like PaperWM treats empty "columns" to the left of the left-most window and to the right of the right-most column. that is to say: if you have 4 half-width windows open, and you press Super+Home or Super+End, it will only show you ONE window, with blank space next to it. (empty half-column to the left when Super+Home, to the right when Super+End)
> 
> If I press Super+Home, I would expect to see the 2 left-most columns, so 2 windows (or 1 full-width [Super+f] window)

That sounds like a bug. Just to be sure I understood correctly. After pressing Super+Home this is the result?

![image](https://user-images.githubusercontent.com/72201/82724451-a0077880-9cd6-11ea-96b1-59733d0d34c0.png)

Could you check `journalctl $(which gnome-shell)` right after pressing Super+Home.

**Comment by olejorgenb** [comment] 2020-05-23 07:30
> additionally, in a 4-half-width-window layout the middle 2 windows don't have any sort of snapping logic: there's no way to easily "center" the viewport on the 2 middle windows with swiping. If you use Super+,/. to move focus, you can get the 2 middle windows in the viewport, but the right and left gaps are, for some reason, different. I think this is cuz there's no real "snapping" involved, and it just sort of moves viewport focus

The gaps should be the same, but if the windows only resize in increments[1] (eg. the width is always a multiple of 14px) the windows wont be exactly 1/2 sized. Then one of the gaps will necessarily be bigger since Super+,/. don't do any centering.

[1] Typically terminal windows (eg. gnome-terminal)

**Comment by jtaala** [comment] 2023-04-08 04:57
I haven't been able to reproduce this issue in current PaperWM `develop` branch.  A few things have changed since this issue was submitted (notably #488) which may have corrected this issue(?).

Have marked this as potentially no longer valid and will close this issue in a month or so - let me know if this is reproducible by others given current PaperWM status.

**Comment by jtaala** [comment] 2023-05-15 19:25
Closing as stipulated in previous comments (have received no further feedback in more than a month).

**Closed by jtaala** 2023-05-15 19:25 UTC
Labels: bug, no longer valid?, can't reprodurce
