### ISSUE TITLE
Windows switch workplaces after suspend

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#314] opened 2020-06-08 21:11 UTC
When I reawaken my laptop after it's been suspended, application windows move to different workspaces. I'm not sure what the pattern to this is, but it happens every time (ie. I can close the lid, immediately open it, and after the gdm lock screen - windows are now on different workspaces).

PaperWM 36.0 on Gnome 3.36.2 (Wayland).

**Comment by olejorgenb** [comment] 2020-06-08 21:37
Yeah, I've also experienced this a few times lately :/ Haven't gotten around to debug it yet, but hopefully the pain will soon do its job :)

It doesn't always happen here though. If you can see any patterns in where the windows moves it would be helpful. (eg. windows from workspace X moves to Y)

**Comment by crispinb** [comment] 2020-06-08 21:51
I don't think it's random - a couple of workspaces seem to be favoured. I haven't paid close enough attention to be sure. I'll have a play when I'm back at my desk a bit later and report back.

**Comment by crispinb** [comment] 2020-06-08 22:37
Hmm I just did some experimentation but to keep track of things I started from a clean slate - ie. closed all existing windows and opened up new ones on each workspace to test with. Now it's not happening, whereas it had previously been occuring after every suspend. 

Presumably the issue is dependent on state somehow. When it next happens I'll gather any info I can and reply.

**Comment by rayjanoka** [comment] 2020-07-09 23:33
This happens to me pretty often, I usually notice because a bunch of windows are moved from one monitor to the other.

**Comment by cben** [comment] 2020-11-17 12:33
Not sure it's the same but:

1. I start with one extenal monitor and laptop lid closed.  Windows spread on several workspaces.
2. I open laptop lid => internal screen comes on, shows another workspace with other windows :heavy_check_mark:  
3. I turn off internal screen (Super+P "External only") => windows collapse to single workspace :frowning_face: 

Interestingly, if I repeat this without closing the lid — just enable internal screen then disable it — windows stay in separate workspaces :heavy_check_mark:.  So it's something about the hardware lid event?    And apparently it's not about suspend / lock screen!

PaperWM 36.0 git tag, GNOME Shell 3.36.7, Xorg, fedora 32.

**Comment by olejorgenb** [comment] 2020-11-17 12:39
IIRC we suspect this is caused by having dynamic-workspaces on. I recommend trying to turn this off and rather increase the number of workspaces until we can sort this out.

**Comment by cben** [comment] 2020-11-17 12:42
Correction: the above only happens with the unsupported "workspaces only on primary".  
Yes, I have dynamic workspaces, but with "workspaces span monitors" setting I can't reproduce that problem (whether I close lid or not) :tada:.  Guess I should listen to README :wink:

**Comment by jtaala** [comment] 2023-03-11 07:56
Noting that this issue appears resolved (see last comment).  Planning on closing this issue when we review it next.  Let us know if anyone thinks it should remain open (e.g. if anyone else is seeing this issue and it's not resolved by trying what was in the last comment).

**Comment by crispinb** [comment] 2023-03-11 09:10
I'm no longer experiencing this issue, so it can be closed from my pov.

**Comment by Lythenas** [comment] 2023-03-11 09:18
As a side note: Maybe we should check for the required settings when the extension is enabled. Similarly to #478

**Comment by jtaala** [comment] 2023-03-11 10:48
> As a side note: Maybe we should check for the required settings when the extension is enabled. Similarly to #478

That's a fair idea @Lythenas - could check and throw a warning similar or something (similar to #478) - only concern is don't want it to become spammy/naggy.

**Comment by Lythenas** [comment] 2023-03-11 10:56
> only concern is don't want it to become spammy/naggy.

Yes I'm also a bit worried about that. Maybe we can add just one warning notification when you first log in and open a window to show more detailed information on click. And also allow disabling a particular warning. Maybe this window can even be integrated into the preferences (as kind of a healthcheck or something). Not sure.

**Comment by jtaala** [comment] 2023-04-10 12:56
> I'm no longer experiencing this issue, so it can be closed from my pov.

Thanks @crispinb - closing this issues now given the above comment and having received no further comments after a month.

**Closed by jtaala** 2023-04-10 12:56 UTC
Labels: no longer valid?
