### ISSUE TITLE
Preferred width does not work with some applications

### ISSUE THREAD

**Issue by alondrayona** [paperwm/PaperWM#642] opened 2023-10-23 10:13 UTC
**Describe the bug**
Title

**To Reproduce**
1. Install [Alacritty](https://github.com/alacritty/alacritty) and/or [VSCodium](https://flathub.org/apps/com.vscodium.codium)
2. Create rule under winprops, eg `'{"wm_class":"Alacritty","preferredWidth":"80%"}'` and/or `'{"wm_class":"codium-url-handler","preferredWidth":"50%"}'`
3. Open Alacritty[1] and/or VSCodium
4. Preferred width does not apply

**Expected behavior**
New windows should use the preferred width.

**System information:**

<details>
<summary>System information</summary>

```
Distribution: Fedora Linux
GNOME Shell 44.5
Display server: Wayland
Enabled extensions:
- gsconnect@andyholmes.github.io
- scroll-workspaces@gfxmonk.net
- switcher@landau.fi
- do-not-disturb-while-screen-sharing-or-recording@marcinjahn.com
- default-workspace@mateusrodcosta.com
- mediacontrols@cliffniff.github.com
- hidetopbar@mathieu.bidon.ca
- paperwm@paperwm.github.com
- Always-Show-Titles-In-Overview@gmail.com
```
</details>

**Additional context**
The rules worked for both apps a few versions ago.
<details>
<summary>[1] I use a custom keyboard shortcut for this</summary>

```ini
[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>T'
command='alacritty'
name='Open Terminal'
```
</details>

**Comment by jtaala** [comment] 2023-10-23 20:34
Thanks @alondrayona,

I don't believe anything has changed on this in PaperWM.

So far, it appears that alacritty (at least) is rejecting the PaperWM startup size.  I get this message in the logs from alacritty:
```
Oct 24 07:29:38 m16 gnome-shell[549291]: Invalid window geometry for xdg_surface@45. Ignoring for now, but this will result in client termination in the future.
```
There's a couple of references/issues on alacritty's repo re this issue and other sizing issues (these were closed, so may have been a regression there?):

https://github.com/alacritty/alacritty/issues/7058
https://github.com/alacritty/alacritty/issues/6184

**Comment by jtaala** [comment] 2023-10-23 20:39
Also, just checking how you're setting these winprops - are you using the settings ui? e.g.

![image](https://github.com/paperwm/PaperWM/assets/30424662/025cc367-5263-42a2-8748-3132557ad554)

Note that `user.js` won't be supported in Gnome 45 (just a heads up), see https://github.com/paperwm/PaperWM/issues/576#issuecomment-1721315729

**Comment by jtaala** [comment] 2023-10-23 20:47
Also, it appears your `wm_class` value for vscodium is incorrect.  This should work:

![image](https://github.com/paperwm/PaperWM/assets/30424662/5ad8a870-372e-4c87-ace7-f14a020bc37a)

**Comment by jtaala** [comment] 2023-10-23 20:55
Out of interest, where did the `codium-url-handler` wm_class come from?

Finally, see this section of setting a default rule (and then choosing different sizing by exception):

https://github.com/paperwm/PaperWM#setting-a-default-window-property-rule

E.g. might work better for you (i.e. set default to be 50% and then create a winprop rule for any app you want something different).

NOTE: this won't fix `alacritty` issues since it appears it's alacritty itself that is overriding gnome/paperwm startup size.

**Comment by jtaala** [comment] 2023-10-23 21:16
I'll have a look and see if there's some improvement we could add to override application's startup size (with PaperWM's).

**Comment by alondrayona** [comment] 2023-10-25 15:57
Thanks for checking it out.

#### General 


> are you using the settings ui

Yep I use the UI, it's just easier to copy paste the saved version. :D

> Finally, see this section of setting a default rule 

I originally had one, but it also broke for some apps (eg gnome extensions[1], mpv, etc) 


And I use gnome 44.

#### Alacritty

> There's a couple of references/issues on alacritty's repo re this issue and other sizing issues (these were closed, so may have been a regression there?)

I don't think so, I tried it on fedora with v0.12.1 and v0.10.1, and it doesn't work on alpine too (where the latest version is v0.12.1). Previously it worked in alpine and alacritty version hasn't changed since.
The interesting part is that it usually resizes the height (to fill the screen), but the width is unchanged, and sometimes the height is left untouched too.


#### VScodium

> Out of interest, where did the codium-url-handler wm_class come from?

I tried to use VSCodium but it didn't worked so i checked in looking glass[2]. I'm using an older version because of [this issue](https://github.com/flathub/com.vscodium.codium/issues/224).


---


[1] [paperwm.webm](https://github.com/paperwm/PaperWM/assets/148759012/8ccf5b1d-19b4-42e9-b29d-1e1e1e3a23e6)


[2]
![vscodium](https://github.com/paperwm/PaperWM/assets/148759012/d7acb3af-251e-4ed0-ae99-1a6128c0f6b9)

**Comment by alondrayona** [comment] 2023-10-25 16:29
I reset all gnome settings and tried the v40 and v34 from extensions.gnome.org and it still doesn't work (I tested with gnome extensions) so I have no idea where it breaks...

**Comment by Lythenas** [comment] 2023-10-25 18:21
For what it's worth, I feel like lately I ran into the problem more often where the window does not have the full height. Usually this is gnome terminal and terminator. But I think it only happens the fist time you start it after login.

But I'm not sure if it got worse or was always like this and I just didn't notice^^

**Comment by jtaala** [comment] 2023-10-27 22:40
> For what it's worth, I feel like lately I ran into the problem more often where the window does not have the full height. Usually this is gnome terminal and terminator. But I think it only happens the fist time you start it after login.
> 
> But I'm not sure if it got worse or was always like this and I just didn't notice^^

Is that for autostarted app windows?

**Comment by jtaala** [comment] 2023-10-27 22:52
> [1] [paperwm.webm](https://github.com/paperwm/PaperWM/assets/148759012/8ccf5b1d-19b4-42e9-b29d-1e1e1e3a23e6)

Thanks @alondrayona - that I can reproduce.  Interestingly, I've 25% set for extensions for a while - not sure when it stopped working for those apps.

I'll try a git bisect to see if we can isolate a commit when this started happening.

**Comment by jtaala** [comment] 2023-10-27 23:01
Okay, seems introduced between v44.11.0 and v44.11.1.

Bisecting now.

**Comment by jtaala** [comment] 2023-10-27 23:07
hmmm - saying was introduced in 825d2a575c1762aa9b6d1b91f0452d48b1d2b8ad.

Kind of looks like a race condition on the animation.  Well, at least can isolate now.

**Comment by jtaala** [comment] 2023-10-28 01:19
@alondrayona,

Can you test out PR #647?

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-642-preferredWith-winprop-regression
./install.sh
```

and then logout/login.

Let me know how that goes.

When you're done your tests you can just uninstall PaperWM (from extensions app) and then reinstall from extensions.gnome.org.

**Closed as completed** 2023-10-28 04:28 UTC
Labels: bug

**Comment by jtaala** [comment] 2023-10-28 04:39
Hey @alondrayona.  Fixes for these issues have been pushed for gnome-44 and gnome-45, and versions have been submitted to extensions.gnome.org (they'll be available when they are approved).

Thanks for reporting.
