### ISSUE TITLE
Capturing window is broken in screenshot view caused by a js error

### ISSUE THREAD

**Issue by lost-melody** [paperwm/PaperWM#811] opened 2024-04-01 09:27 UTC
**Describe the bug**
As a GNOME feature, we can press `PrtSc` to take a screenshot, and in the "screenshot view" we can then press `w` to preview and select a window to capture.
Now when I try to capture a window, there's no preview displayed and no window to select. Plus an error is observed in logs. (see addition context)

**To Reproduce**
1. Press `PrtSc` (or whatever keybinding for *Take a screenshot interactively* in GNOME keyboard shortcuts settings).
2. Press `w` if not in window selection view.
3. Result: no window is listed here.

**Expected behavior**
Previews of windows should be listed to select and capture.

**Screenshots**
<details><summary>Nothing displayed</summary>

![capture-window-nothing](https://github.com/paperwm/PaperWM/assets/32810294/2cb5f325-b6e8-4478-bac1-8cf42517e799)
</details>

<details><summary>Expected</summary>

![capture-window-expected](https://github.com/paperwm/PaperWM/assets/32810294/09ef279c-dd62-48a0-824c-8a2aadb066d4)
</details>

**System information:**
<details><summary>System information</summary>

```
Distribution: Arch Linux
GNOME Shell 46.0
Display server: Wayland
PaperWM branch/tag: develop
PaperWM commit: 8f80d09f1cd5c32a36f4acdfd2e8af959ea1d35c
Enabled extensions:
- paperwm@paperwm.github.com
- appindicatorsupport@rgcjonas.gmail.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- Bluetooth-Battery-Meter@maniacx.github.com
- AlphabeticalAppGrid@stuarthayhurst
- kimpanel@kde.org
- runcat@kolesnikov.se
- blur-my-shell@aunetx
- gnome-ui-tune@itstime.tech
- unite@hardpixel.eu
```
</details>

**Additional context**
<details><summary>Error logs</summary>

```
gnome-shell[619105]: JS ERROR: TypeError: meta_window is undefined
    spaceOfWindow@file:///home/lost-melody/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/tiling.js:2919:9
    sortWindows@file:///home/lost-melody/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/overviewlayout.js:263:32
    computeLayout@file:///home/lost-melody/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/overviewlayout.js:101:23
    setupOverrides/<@file:///home/lost-melody/.local/share/gnome-shell/extensions/paperwm@paperwm.github.com/patches.js:244:49
    vfunc_allocate@resource:///org/gnome/shell/ui/screenshot.js:729:33
    @resource:///org/gnome/shell/ui/init.js:21:20
```
</details>

A workaround is to add those codes in function `sortWindows`:
```js
export function sortWindows(a, b) {
    if (!a || !b || !a.metaWindow || !b.metaWindow) {
        return 0;
    }
    // ...
}
```
This is not a fix, but I cannot proceed any further.

**Comment by Lythenas** [comment] 2024-04-01 10:58
I can confirm this issue on Gnome 46. I think on Gnome 45 it still worked some time ago (but not 100% sure).

The behavior is also a bit inconsistent. From very limited testing:

- I have two monitors, monitor 1 with multiple firefox windows, discord and thunderbird
- taking a screenshot on monitor 2 with only a single firefox window works fine
- taking a screenshot on monitor 2 with steam main, friends and chat windows only shows the chat window. But it shows on monitor 1 and only the part that was visible on monitor 2.
- taking a screenshot on monitor 1 shows only the discord window, which was out of screen.  But it shows on monitor 2.
- somehow it works fine if all windows on the workspace take up the entire screen (e.g. `Super+f`).

It seems like `sortWindows` is called with arguments that don't have a `metaWindow` field.

@jtaala does this have something to do with what you implemented for the gnome overview? If so can you take a look here? Otherwise I will try to look into it.

**Comment by jtaala** [comment] 2024-04-01 11:17
Sure, just pushed up a fix for that comparator.  

Can you please test branch [fix-gnome-window-screenshot](https://github.com/paperwm/PaperWM/tree/fix-gnome-window-screenshot)?

**Comment by lost-melody** [comment] 2024-04-01 11:22
Yes it fixes the problem.

**Comment by jtaala** [comment] 2024-04-01 13:08
Well, it's fixed in that the windows show, but it's also showing PaperWM's clipping for partially shown windows:

![image](https://github.com/paperwm/PaperWM/assets/30424662/61eeb9b1-095a-4e83-b847-3e864b160b1a)

A workaround this by going into Gnome `overview` (which Gnome window screenshot works correctly).  We could override the window screenshot to either go into Gnome overview first or disable PaperWM's clipping for the screenshot...

Both of those options are some work, I'll push up this fix first anyways and keep this issue open.

**Comment by jtaala** [comment] 2024-04-01 21:21
Just a heads-up that I'm going to try fix the clipping issue tonight (will experiment with hiding the `clip` actor while in screenshot view).  If that doesn't go well, I'll just merge this branch for a partial fix.

**Comment by jtaala** [comment] 2024-04-02 21:08
Morning all,

I believe I've now fixed the clipping windows issue.  @lost-melody, could you please pull the latest on [fix-gnome-window-screenshot](https://github.com/paperwm/PaperWM/tree/fix-gnome-window-screenshot) and test?

I've added a patch to remove window clipping (which clips windows to the monitor boundaries in PaperWM) when the `ScreenshotUI` opens, and then re-apply them when it `closes`).

**Comment by lost-melody** [comment] 2024-04-03 02:51
@jtaala, I've tried your fix and it works, but a side effect is introduced. If I return to *Overview* from *ScreenshotUI* (by pressing `Super`, `PrtSc`, then `Esc`), windows are clipped.

**Comment by jtaala** [comment] 2024-04-03 07:47
> @jtaala, I've tried your fix and it works, but a side effect is introduced. If I return to _Overview_ from _ScreenshotUI_ (by pressing `Super`, `PrtSc`, then `Esc`), windows are clipped.

Nice pickup @lost-melody.  Fixed.

**Comment by jtaala** [comment] 2024-04-03 08:13
> * I have two monitors, monitor 1 with multiple firefox windows, discord and thunderbird
> * taking a screenshot on monitor 2 with only a single firefox window works fine
> * taking a screenshot on monitor 2 with steam main, friends and chat windows only shows the chat window. But it shows on monitor 1 and only the part that was visible on monitor 2.
> * taking a screenshot on monitor 1 shows only the discord window, which was out of screen.  But it shows on monitor 2.
> * somehow it works fine if all windows on the workspace take up the entire screen (e.g. `Super+f`).

Most of these issues are due to the gnome paradigm of "one workspace across all monitors" (i.e. see https://github.com/paperwm/PaperWM/issues/389#issuecomment-1911089672).  Even with multiple monitors, on vanilla gnome it's actually one workspace.  That's what's happening here, for screenshots, gnome is pulling the windows on that "workspace" (which conflicts with PaperWM approach of having one workspace per monitor).

Anyways, what it means is that for screenshotting windows with PaperWM (and multiple monitors), is that pressing printscreen will show the windows _on that PaperWM space_... which may be spread out across multiple monitors (in the case where some windows are to the left/right in scrolling space.

It's workable, but may be confusing.

**Closed as completed** 2024-04-03 09:52 UTC
Labels: bug, WIP
