### ISSUE TITLE
windows on second screen do not fully cover it on the bottom

### ISSUE THREAD

**Issue by thenameisluk** [paperwm/PaperWM#876] opened 2024-06-12 20:02 UTC
**Describe the bug**
windows on second screen do not fully cover it on the bottom, it is probably caused by the lack of top bar on the other screen
the windows seam to fix them selve after resizing with a shortcut

**To Reproduce**
1. Connect a second monitor
2. Move a window there with a shortcut

**Expected behavior**
Covering full screen

**Screenshots**
![obraz](https://github.com/paperwm/PaperWM/assets/92756992/12a2428a-6a94-416c-9eb7-4678fb2c45e2)
_Note. the minecraft window is only visible on the second screen but taking a screenshot makes it visible on both, just a weird thing, don't have an issue with that_

**System information:**

```
Distribution: Debian GNU/Linux
GNOME Shell: 46.2
Display server: Wayland
PaperWM version: 46.11.1
Enabled extensions:
- caffeine@patapon.info
- ddterm@amezin.github.com
- gravatar@dsheeler.net
- gsconnect@andyholmes.github.io
- paperwm@paperwm.github.com
- tophat@fflewddur.github.io
- weatheroclock@CleoMenezesJr.github.io
```

**Additional context**
my screen is connected via usb-c to hdmi adapter (very likely unrelated)

**Comment by jtaala** [comment] 2024-06-12 22:49
I'm guessing your monitors are different resolutions (or different DPIs)?

Note, multi-monitor support has issues, and this is one of them.  It's essentially how mutter handles window heights if they are offscreen (in PaperWM, they are partly offscreen and we clip/hide them).  So in PaperWM when we select left/right - the windows are moved mostly offscreen (mutter stops us moving it entirely off screen), and mutter then says "this window is mostly on monitor x, I'll resize it automatically" - which often causes these issues like this with monitors of differing resolutions / dpis.

We don't have a good way to resolving this (would likely require patching mutter to completely resolve).

**Comment by jtaala** [comment] 2024-06-12 22:57
ah, actually - that looks more like a topbar (or PaperWM's `window position bar` for external monitors).

That is, looks like you don't use PaperWM's window position bar on other monitors, and the layout calculation isn't taking that into account.

Definitely a bug.

**Comment by jtaala** [comment] 2024-06-12 23:00
Would then be same issue as #709 (mult-monitor and if don't have topbar for a specific screen).  This close this one as a duplicate of #709.  This issue will then be referenced in #709.  I'll work on this as part of #709 when I can get to it.

**Comment by jtaala** [comment] 2024-06-13 06:14
Hey @LukIsHere,

I've done some work on (what I think is a related issue).   See #709.

Could you give this one a test and let me know if changes anything for the issue you're seeing (it was a complicated refactor so there is a possibility it doesn't fix your issue... or makes it worse?).

Can you please test this PR?

```
git fetch --all
git checkout fix-709-notopbar-layout-height
./install.sh
```

then logout / login.

**Comment by jtaala** [comment] 2024-06-13 06:19
Oh can you also sent me screenshot of your margin  / border settings, e.g.:

![image](https://github.com/paperwm/PaperWM/assets/30424662/a0b25bd6-ddf2-464a-87ec-2c91199db8ae)

Cheers!

**Comment by thenameisluk** [comment] 2024-06-13 10:14
i just keep them all at 0, since i don't feel like any gap is needed at all
![obraz](https://github.com/paperwm/PaperWM/assets/92756992/c5c4521d-03ce-4bc8-9e28-dd70d086693d)

> I'm guessing your monitors are different resolutions (or different DPIs)?

both are same resolution and all
main
![obraz](https://github.com/paperwm/PaperWM/assets/92756992/26b575f9-48a7-46f6-b4ed-c2cb5c5b84b1)
second
![obraz](https://github.com/paperwm/PaperWM/assets/92756992/adb0d5f0-4d50-4b7e-bfca-a438157c04c6)

**Comment by thenameisluk** [comment] 2024-06-13 10:20
i checkedout and installed the patch
and it still seams to be an issue for some windows, but not for others

https://github.com/paperwm/PaperWM/assets/92756992/0c16c264-189f-4b44-946b-bc3b73c02999

^
firefox works fine
but extension manager nope

**Comment by jtaala** [comment] 2024-06-13 10:26
Does this behaviour only occur when you use a shortcut to move the window to another monitor?

What shortcut are you using to send the window to the other monitor?

It probably needs to trigger a `layout` call once the window has moved - if it corrects itself when you open another window on that monitor then that would likely be the issue.

**Comment by thenameisluk** [comment] 2024-06-13 10:31
it also happends when i drag it with the mouse
https://github.com/paperwm/PaperWM/assets/92756992/703ffc5a-731e-4210-a83b-d6ff6366a036

i use these shortcuts
![obraz](https://github.com/paperwm/PaperWM/assets/92756992/5b6b6cda-9d8e-4f69-b45b-522efcfa80c8)

**Comment by jtaala** [comment] 2024-06-13 10:38
Cheers - I can reproduce this now.

**Comment by jtaala** [comment] 2024-06-13 11:03
Yeah, some apps are more prone to this it seems.  Same thing happens in vanilla gnome when moving windows to another monitor (they don't have up full height in monitor without topbar - they maintain there original height from monitor with topbar).

Not really an issue with PaperWM's window position bar (which was partly designed to avoid these mutter-height issues.  Becomes very apparent when you disable the window position bar though.

Looks like we might need to implement a forcing height mechanism when no topbar (or paperwm window position bar).

**Comment by jtaala** [comment] 2024-06-13 11:19
Will reopen this one as it's a little different to #709.

**Comment by jtaala** [comment] 2024-06-13 12:37
Hey @LukIsHere,

Getting there with this one.  Checkout a new branch for the fix:

```
git fetch --all
git checkout fix-876-windows-on-second-screen-not-full-height
```
then logout/login.

~~Shortcuts moving window to another monitor should be working.  Drag/dropping windows isn't quite working yet.~~ _Drag/drop also should now be working_.

Cheers.

**Comment by jtaala** [comment] 2024-06-13 12:52
> Shortcuts moving window to another monitor should be working. Drag/dropping windows isn't quite working yet.

Drag/drop should now be fixed on that branch.

**Comment by thenameisluk** [comment] 2024-06-13 16:08
seams to be working

https://github.com/paperwm/PaperWM/assets/92756992/55211b03-341a-4d3b-a634-29b5cb935ebd

but it's instant instead of smooth unlike firefox ('s not really a big deal but ye)

**Comment by jtaala** [comment] 2024-06-14 00:08
> but it's instant instead of smooth unlike firefox ('s not really a big deal but ye)

Not too much we can do about that one - it's down to the application on how gracefully it handles natural resizing when moving to another monitor and addressing the height difference (e.g. without topbar).

Some applications address this type of resizing gracefully, others don't.

PaperWM itself avoids this situation with the `window-position-bar`.  Otherwise, we'll need to manually resize to compensate for apps that don't address this case gracefully.

_Note also, that some applications (like gnome terminal) can enforce an discrete "number of lines" height... e.g. there might still be a gap at the bottom since they won't allow to resize height-wise unless it's a full terminal line height.  So, basically it comes down to what the application enforces._

**Comment by jtaala** [comment] 2024-06-14 00:11
Would accept a PR from you if you'd like to work more on making the resize smoother for this use case (note, I don't use this type of setup, e.g. 0 margins and disabling `window-position-bar`.  There's probably some improvement you could find for this configuration).

**Closed as completed** 2024-06-14 00:56 UTC
Labels: bug, multi-monitors, PR READY
