### ISSUE TITLE
Error in Gnome 42 with the gnome 44 fixes

### ISSUE THREAD

**Issue by Lythenas** [paperwm/PaperWM#524] opened 2023-05-16 08:00 UTC
**Describe the bug**
I'm getting the following error (after multiple lock, unlocks).

This breaks all workspaces on all monitors and all windows are now in a strange state. They are hidden unless on the active monitor.

**To Reproduce**
1. Lock
2. Unlock
3. Repeat multiple times (have not consistently reproduces this)

**Expected behavior**
No error and everything works.

**Screenshots**

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

Distribution: Ubuntu
GNOME Shell 42.5
Display server: Wayland
PaperWM branch/tag: fixes-gnome-44-support
PaperWM commit: 7358da5466d0f03551c0036fd2da3f3bb4f7e37a
Enabled extensions:
- switcher@landau.fi
- paperwm@hedning:matrix.org
- ubuntu-appindicators@ubuntu.com

**Additional context**
@jtaala  Since this happened while testing your PR #515  I'm assigning this to you.

[error.txt](https://github.com/paperwm/PaperWM/files/11485436/error.txt)

**Comment by jtaala** [comment] 2023-05-16 08:28
Hey @Lythenas, if you're on gnome 42, please use the gnome-42 branch.  The gnome 44 fixes are likely not compatible with gnome 42 as gnome has changed much since then.

I'm also not planning on attempting to maintain compatibility across all gnome versions in the latest (which is why we have specific branches) as we don't have resources to do so (also, I wouldn't be able to test this as I don't use, or plan to use gnome 42).

**Comment by jtaala** [comment] 2023-05-16 08:36
I've also created a gnome-43 branch, partly for this reason - although gnome-43 likely works fine with 44 fixes (not sure though as I can't test this anymore).

Given this, I'm also thinking it might be better to remove the previous versions from metadata, so that users don't get confused - the README.md outlines which branch to use for gnome versions.

**Comment by jtaala** [comment] 2023-05-16 08:38
Unassigning me as I can't actually test (and hence can't fix this) since I don't use gnome 42.

**Comment by jtaala** [comment] 2023-05-16 08:49
Actually, from memory I think you were running gnome 43 branch on gnome 42?

I can see where it's erroring in your log, will put a guard on them and get you to test again.

**Comment by jtaala** [comment] 2023-05-16 08:59
Hmmm - we can put guards on the areas where this happened, but I'm not sure how it got in that state to begin with.

I also can't (yet) reproduce this on gnome 44, I've locked/unlocked 27 times in a row and haven't reproduced it yet.

**Comment by Lythenas** [comment] 2023-05-16 17:23
I just copied the error logs at work and haven't looked into the code at all. I also don't see how the error could happen. I don't think we need to add a guard to the code. Because if `metaWindow.clone` ends up as undefined. There will likely also be errors somewhere else later.

Also, not wanting to support so many versions is fair. Although then I might try to backport some features to the gnome-43 or gnome-42 branch. And the gnome-43 branch worked fine for gnome 42 so far. Unfortunately since I have to use ubuntu 22.04 at work for now I probably can't easily upgrade to gnome 43 :(

It might also just be some very strange coincidence that I ran into this. It worked fine for about 2h. Also while locking and unlocking a couple of times. The error was just annoying because I couldn't really use most of the windows after that. Even creating this issues was a pain. I think I will try to implement a "reset everything" feature on the weekend, as I mentioned on zulip.

**Comment by jtaala** [comment] 2023-05-16 22:37
Well, feature-wise, there's currently feature parity between PaperWM gnome 43 & 44 (at the moment at least).  If you've been using gnome 43 on your 42 machine (at work) - maybe we can set the gnome-42 branch where the latest 43 is?  At least then 42 & 43 will be at the same commit.

From memory, there didn't seem to be any big changes in PaperWM between 42 & 43.  It's quite difference in 44 as there's been quite a few things changed (not just code, but approaches, e.g. the new grab methods which completely changed from previous gnome versions).

I'm going to reopen this and make a small change (based off your provided logs) - the first error is an issue, but the 2nd error in there is grab related.... we can at least fix that one and test again if you are able to.

The main issue is that I can't easily test on 42 - and requiring all our changes that are required for 44 to also work in 43 & 42 (&41?) isn't feasible (heck, gnome don't do that, even with lots more resources/devs than we have).

I'll reopen and make a quick change so you can give that a test in 42.

**Comment by jtaala** [comment] 2023-05-16 22:53
Hey @Lythenas, can you test latest #515?  specifically commit 477e87a4f04a01ad05245852c0cf645fd19bec0c.  Try that one out and see if you can reproduce on 42.

Otherwise, let me know if you've been using gnome 43 PaperWM (i.e. the develop branch we've been using before gnome 44) - if so, then it might be worth setting gnome-42 branch to that commit.

**Comment by Lythenas** [comment] 2023-05-18 16:41
No idea if your commit fixed the issue, but at least today I didn't encounter it. I will continue testing next week on my work laptop as I have tomorrow off.

Previously I've been using the develop branch on gnome 42 (before the work for gnome 44). And I haven't encountered any issues. So I think we can just set the gnome-42 branch to the commit of the gnome-43 branch.

**Comment by jtaala** [comment] 2023-05-31 21:49
Closing this issue after testing in gnome 42 mentioned in #540.

Can reopen if issue happens again and we can reproduce.

**Closed as completed by jtaala** 2023-05-31 21:49 UTC
Labels: bug
