### ISSUE TITLE
Compatibility with vertical Dash to Panel

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#199] opened 2019-11-10 02:03 UTC
When PaperWM is running, Dash to Panel cannot be configured vertically in its settings (i.e. panel position can be set to "left", but panel remains on top or bottom).

PSA: for those trying the new vertical Dash to Panels, note that if you 1) disable PaperWM and then set Dash to Panel to the left or right; 2) drag a window to where the panel usually sits, and then unset vertical Dash to Panel (set the panel position back to top or bottom); 3) re-enable PaperWM: PaperWM will incorrectly gauge the vertical space and thus new windows will intrude into the Dash to Panel, causing it to hide every time.

**Comment by code-doge** [comment] 2020-04-26 07:17
in Gnome 3.36,  I even have an issue with pannel placed horizontally at the bottom,  there will be an empty row on top as if there is a pannel.

**Comment by hedning** [comment] 2020-04-26 13:26
> in Gnome 3.36, I even have an issue with pannel placed horizontally at the bottom, there will be an empty row on top as if there is a pannel.

Hmm, right, we make the assumption that the top bar is on the top (IIRC we ran into some trouble just relying on the reported workarea as it could change on eg. fullscreen, though I think that's fixed in newer gnome-shell).

We'll also move the panel to the top when eg. changing workspace, so that's also not ideal.

I think the left/right issue is also caused by us moving the top bar.

**Comment by adamlwgriffiths** [comment] 2020-11-03 06:04
Using Gnome 3.36.5, Dash to Dock 69.
I can adjust the Dock to both left, and bottom. Haven't had any issues (auto-hide works, avoiding windows works, etc).
Perhaps this one is resolved?

**Comment by jvzr** [comment] 2020-12-16 12:08
I'm using Dash to Panel (horizontal, bottom) and the gap at the top remain

**Comment by adamlwgriffiths** [comment] 2021-01-03 07:15
Can you guys provide a screenshot of exactly what it is you're seeing?
I haven't followed the instructions in OP's "PSA" so there may be other edge cases in there that I'm not seeing.

Horizontal
![image](https://user-images.githubusercontent.com/1239156/103473684-66abf500-4def-11eb-9015-5e3520d32b8c.png)

Vertical
![image](https://user-images.githubusercontent.com/1239156/103473692-7b888880-4def-11eb-91c4-055de6beb74b.png)

**Comment by jtaala** [comment] 2024-04-09 10:17
Closing as no response.

**Closed by jtaala** 2024-04-09 10:17 UTC
Labels: extension-conflict, no longer valid?
