### ISSUE TITLE
Can't scroll/Choppy Animationfor window switching using three finger touchpad swipe after latest update.

### ISSUE THREAD

**Issue by adityainduraj** [paperwm/PaperWM#663] opened 2023-11-02 14:14 UTC
**Describe the bug**
Earlier, the animation for switching between windows using the three finger horizontal swipe gesture used to be very smooth. I just noticed after updating to the latest version (took me a day or two to notice however) that the animation was very choppy and I could not exactly scroll smoothly, making the gesture unusable. 
I have also experimented with various friction/sensitivity combinations but they seem to be making little to no difference. 

**To Reproduce**
1. Download latest PaperWM.
2. Open multiple windows. 
3. Use the touchpad's three finger horizontal swipe to navigate between them. 
4. Note the choppiness in animation. 

**Expected behavior**
Should work smoothly as it did in previous versions.

**Screenshots**

https://github.com/paperwm/PaperWM/assets/85331139/018cd481-14a5-4191-b6de-28523f968e77

**System information:**

```
Example:
Distribution: Fedora Workstation 38
GNOME Shell 44.5
PaperWM branch/tag: latest EGO version
Enabled extensions:
- paperwm@paperwm.github.com
- gesture improvements
- dash to dock
- burn my windows.
```

**Additional context**
I thought that the Gesture-Improvement extension might have been causing the issue but the problem persisted even after disabling and removing that extension.

**Comment by adityainduraj** [comment] 2023-11-02 14:20
[Screencast from 2023-11-02 19-47-33.webm](https://github.com/paperwm/PaperWM/assets/85331139/a1490acd-bbb5-437c-946d-2d67bf2fe69b)

There is something wrong with the first video, it seems that the compression really slowed it down for some reason. 
This should be better.

**Comment by Thesola10** [comment] 2023-11-02 17:39
~~Maybe related to #658 @jtaala~~

Nevermind, happens somewhere in #643 though I don't recall having had that issue before the release merge somehow

**Comment by Thesola10** [comment] 2023-11-02 17:57
I still don't think it's #643 because it doesn't touch anything beyond adding a touch event handler, meaning no code from that should trigger on non-touchscreen systems, it's like the `done()` function just broke

**Comment by Thesola10** [comment] 2023-11-02 18:24
uh, `done()` straight up never gets called wtf

**Comment by jtaala** [comment] 2023-11-02 20:18
Thanks for reporting @adityainduraj.  Yes, I noticed a change and was like "I'm sure the swiping used to feel different".

Anyways, since it's easily reproducible, I bisected it to this commit: 6410268b1c4e0c237dd25feb3026ee85e58a69f1.

So this should be easily fixable.

**Comment by Thesola10** [comment] 2023-11-02 20:19
nice. I don't really have a workflow in place for quickly iterating GNOME Shell extensions since the nested Shell doesn't handle trackpad gestures, which are key to testing this, and bisecting to before #643 also removes my ability to test using the touch screen

but yeah, just did a revert of that commit and bingo, scrolling works properly again

**Comment by jtaala** [comment] 2023-11-02 20:57
yep, found the issue - if `params.time` isn't set set (undefined) then we shouldn't set a duration.  I'll push up a fix soon.

**Comment by jtaala** [comment] 2023-11-02 21:14
Hey @Thesola10 - just merged fix into `gnome-44` branch and `develop` branch.  Can you checkout `develop` branch (remember to `git pull`) and test this out for fixing this issue?

**Comment by jtaala** [comment] 2023-11-02 21:15
I'll then do a release (which will include your touch fixes for multimonitor).

**Comment by jtaala** [comment] 2023-11-02 21:34
@adityainduraj  - given you're on gnome 44, I've submitted this fix to EGO so you should get it soon.

@Thesola10 will do the same for a new release for gnome 45.

**Closed as completed** 2023-11-02 21:46 UTC
Labels: bug, visual-bug, animation-change

**Comment by jtaala** [comment] 2023-11-02 21:55
P.S. @adityainduraj - it's fixed in EGO version 50.
