### ISSUE TITLE
MPV freezes when when it is on second screen

### ISSUE THREAD

**Issue by quexten** [paperwm/PaperWM#781] opened 2024-02-14 01:31 UTC
**Describe the bug**
I'm not sure if this is the right place to report the bug, or if it should be at mpv, but I've never encountered this in regular gnome.

**To Reproduce**
1. Open mpv on screen 2.
2. Go to screen 1
3. Switch workspaces using windows + page down
4. Mpv now has a frozen picture (but sound continues playing)
5. Focus screen 2
6. Mpv resumes fine

**Expected behavior**
Mpv should not freeze.

**Screenshots**
--

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.

```
Please include this information in your bug report on GitHub!
Distribution: Fedora Linux
GNOME Shell 45.3
Display server: Wayland
PaperWM branch/tag: release
PaperWM commit: cb7110b5d33e324a29ca59c356829f9b2863ca10
Enabled extensions:
- caffeine@patapon.info
- gsconnect@andyholmes.github.io
- focused-window-dbus@flexagoon.com
- switcher@landau.fi
- power-profile-switcher@eliapasquali.github.io
- monitor-brightness-volume@ailin.nemui
- paperwm@paperwm.github.com
- background-logo@fedorahosted.org
- launch-new-instance@gnome-shell-extensions.gcampax.github.com
```

**Additional context**

**Comment by quexten** [comment] 2024-02-14 01:37
Actually it's not just when switching workspaces, but when having another screen focused in general (not instantly, but after around 3 seconds). Other players (youtube in firefox) continue rendering fine.

**Comment by jtaala** [comment] 2024-02-14 09:35
Thanks for reporting @quexten.

I can't reproduce this.  Let me know if I'm doing anything wrong, or different, than what you do to reproduce:

https://github.com/paperwm/PaperWM/assets/30424662/14b51a68-a188-46c9-8a39-ca37389757bd

**Comment by jtaala** [comment] 2024-02-14 09:36
I anyone else seeing this? (@Lythenas have you seen this?)

**Comment by quexten** [comment] 2024-02-14 14:06
https://github.com/paperwm/PaperWM/assets/11866552/37586986-474b-4c12-9238-88e13920b7ed

Thanks for the quick response!

Hm, so at first I encountered this on a dual monitor setup, but just on my laptop, this also happens (as visible in the screencast) when switching workspaces like in your screencast. Though, does not happen consistently every time depending on what workspace i switch to/was last on. I'm not sure about the exact pattern yet.

As soon as you re-focus the workspace, it unfreezes. If it's just 1 monitor I don't mind because I don't see the window anyways, but when it's on 2 monitors, it's an issue since the player is visible but frozen.

Are there any debug logs I can grab that would help?

**Comment by quexten** [comment] 2024-02-14 14:13
Actually, might be more of an mpv issue, since forcing x11 on mpv with `-vo x11` fixes the freezes.

**Comment by quexten** [comment] 2024-02-14 14:55
Okay, tracked it down to `gpu-api=vulkan` in the config. I'm not sure why this specifically only happens when using PaperWM with mpv, but removing this from my config fixes the freeze (even withouth `-vo x11`). I'll report this at mpv.

**Comment by Lythenas** [comment] 2024-02-14 19:11
Just to confirm. With `mpv --gpu-api=vulkan` I can also reproduce the issue. But without (not sure what the default is) it works fine. I would say the issue is more on mpv side but it likely only manifests because of how we handle workspaces on multiple monitors.

In any case setting `gpu-api` to something other than vulkan is a workaround.

**Comment by jtaala** [comment] 2024-02-18 11:37
Closing as being reported upstream to mpv.

**Closed as completed by jtaala** 2024-02-18 11:37 UTC
Labels: bug, upstream
