### ISSUE TITLE
Getting the glimpse of the window in the first workspace sometimes when scrolling windows in an another workspace

### ISSUE THREAD

**Issue by anonlegionoke** [paperwm/PaperWM#934] opened 2024-08-24 15:10 UTC
**Describe the bug**
Intermittent display of content from the first workspace when scrolling within windows in a different workspace.

**To Reproduce**
1. Open a window in the first workspace
2. Open multiple windows in the second or third workspaces
3. Scroll horizontally using touchpad in second or third workspace
4. Intermittent display of content from the first workspace happening when switching between windows in the second or third workspace

**Expected behavior**
Scroll the windows properly horizontally

**Screenshots**

**System information:**
Distribution: Fedora Linux 40 (Workstation Edition)
GNOME Shell: 46.4
Display server: Wayland
PaperWM version: 46.17.0
Enabled extensions:
- netspeedsimplified@prateekmedia.extension
- pano@elhan.io
- Bluetooth-Battery-Meter@maniacx.github.com
- extension-list@tu.berry
- status-area-horizontal-spacing@mathematical.coffee.gmail.com
- Vitals@CoreCoding.com
- just-perfection-desktop@just-perfection
- color-picker@tuberry
- fullscreen-notifications@sorrow.about.alice.pm.me
- gsconnect@andyholmes.github.io
- notification-icons@muhammad_ans.github
- paperwm@paperwm.github.com
- pip-on-top@rafostar.github.com
- appindicatorsupport@rgcjonas.gmail.com
- emoji-copy@felipeftn
- window-on-top@yousafesaeed.github.io
- logomenu@aryan_k
- caffeine@patapon.info
- top-bar-organizer@julian.gse.jsts.xyz
- notification-timeout@chlumskyvaclav.gmail.com
- power-profile-switcher@eliapasquali.github.io
- auto-move-windows@gnome-shell-extensions.gcampax.github.com
- window-thumbnails@G-dH.github.com
- Battery-Health-Charging@maniacx.github.com
- eepresetselector@ulville.github.io
- default-workspace@mateusrodcosta.com

https://github.com/user-attachments/assets/6d9e5234-ed1c-4dda-9258-878c0f9ca082

**Comment by jtaala** [comment] 2024-08-24 22:34
Hey @anonlegionoke,

This looks like a conflict with touchpad gesture settings (e.g. normal three-finger swipe down gesture allows to switch workspaces).

Can you post your gesture settings, e.g:
![image](https://github.com/user-attachments/assets/967e0f69-9aa9-4c3b-b74c-c915ad9ca5ec)

My guess is it's an extension conflict or some other conflict with three-finger swipe down or other gestures (maybe).  It's almost like your trackpad is picking up three-finger swipe down momentarily.

Can you please disable all other extensions (for testing/isolation) and just leave paperwm enabled and see if you can reproduce?

Cheers.

**Comment by jtaala** [comment] 2024-08-25 02:01
Another guess is that there could be some "fat-finger"'ing happening here.  E.g. if any slight downward motion, then it could be getting picked up as a three-finger down gesture at the start.

Note you can also disable the three-finger swipe down gesture for PaperWM workspace switching (or change it to use four-finger in PaperWM options to avoid this type of detection for three-fingers).

**Comment by anonlegionoke** [comment] 2024-08-25 02:38
Already tried disabling all the extensions, and touchpad thing. 

Sorry, but the issue is not just with the touch pad. I tried switching windows in the second workspace using keyboard shortcuts. Still same issue happened. It was showing Window from the first workspace.

**Comment by jtaala** [comment] 2024-08-25 02:42
Hmm - haven't been able to reproduce this yet, and have never seen this.  Has this just started happening?

Okay, to rule out touchpad issues, can you just confirm you're still seeing this with this setting:
![image](https://github.com/user-attachments/assets/30f57aa0-66ac-4dbe-a10a-ffa0acd02691)

**Comment by anonlegionoke** [comment] 2024-08-25 02:43
Like the window switcher popup was showing when using keyboard shortcuts, but the single  window from the first workspace is showing in the list windows in the second or third workspace, also showing that window in the background of window switcher popup as if I selected it. I  couldn't get a screenshot of it. I will try it again. 


But this issue happens, if have many windows opened across multiple workspaces. And I switch between them frequently!

**Comment by jtaala** [comment] 2024-08-25 02:48
I've followed your reproduction steps precisely, and can't reproduce in my setup (and haven't had this happen).

Must be something else going on here that's affected in your setup.

@Lythenas have you seen this?

> Already tried disabling all the extensions, and touchpad thing.

Just double-checking here, disable all extensions and would need to logout, login, and enable PaperWM only.

Let me know if there's any other tips (e.g. specific apps using etc.) to try reproduce this.

**Comment by anonlegionoke** [comment] 2024-08-25 02:54
> Hmm - haven't been able to reproduce this yet, and have never seen this.  Has this just started happening?
> 
> Okay, to rule out touchpad issues, can you just confirm you're still seeing this with this setting:
> ![image](https://github.com/user-attachments/assets/30f57aa0-66ac-4dbe-a10a-ffa0acd02691)

For now I disabled this, and opened multiple windows, so far I don't see it yet. But will update when I see it again. 

But without that Workspace switching using fingers, I don't think I can use this much.


One weird thing happening now is.., I was on third workspace, I closed the lid to suspend, and when waking up again, it was showing the opened window from the first workspace first instead of windows on third workspace.

**Comment by anonlegionoke** [comment] 2024-08-25 02:56
> I've followed your reproduction steps precisely, and can't reproduce in my setup (and haven't had this happen).
> 
> Must be something else going on here that's affected in your setup.
> 
> @Lythenas have you seen this?
> 
> > Already tried disabling all the extensions, and touchpad thing.
> 
> Just double-checking here, disable all extensions and would need to logout, login, and enable PaperWM only.
> 
> Let me know if there's any other tips (e.g. specific apps using etc.) to try reproduce this.

Let me try disabling all extensions and re-login once again. I will update you if I could get any more info.

**Comment by jtaala** [comment] 2024-08-25 03:02
> but the single window from the first workspace is showing in the list windows in the second or third workspace

This is interesting, what list are you referring to here?

**Comment by jtaala** [comment] 2024-08-25 03:04
> But without that Workspace switching using fingers, I don't think I can use this much

Well, this was testing to see if it was related to touchpad gesture issues since it sounded like you through it wasn't related to the trackpad gestures.

**Comment by jtaala** [comment] 2024-08-25 03:12
> But without that Workspace switching using fingers, I don't think I can use this much.

You could switch to "Four fingers" for workspace switching and give that a go (see if you could reproduce).  If you can't reproduce then it looks like it's probably related three-finger swiping signal being triggered momentarily etc.

**Comment by jtaala** [comment] 2024-08-25 03:14
> But without that Workspace switching using fingers, I don't think I can use this much.

That's fine - paperwm definitely isn't for everyone and their preferred setup / env.  Sad that it's not working for your setup, and that there's something there that's triggering the three-finger swipe down action for some reason in your setup (if that turns out to be the issue).

Thanks for giving PaperWM a go!

**Comment by jtaala** [comment] 2024-08-25 03:37
> Let me try disabling all extensions and re-login once again. I will update you if I could get any more info.

Sounds good, let me know if you find anything else.

> I tried switching windows in the second workspace using keyboard shortcuts

Hmm - this may be a clue.  Let me know which shortcuts you're using exactly to switch to those windows on other workspace (so I can reproduce).  Let me know how you're doing that as I don't think there's a way to switch directly to other windows on other workspaces in paperwm (there is in default gnome app switcher though).

One thing I noticed in your video is that you posted was that it looked like when switching to an app with windows on another workspace you weren't seeing the standard gnome workspace switch animation (which I would have expected). 

e.g. (ksnip and a browser window is another another workspace in the video below):

[Screencast from 2024-08-25 13-36-30.webm](https://github.com/user-attachments/assets/94423a61-6400-46c1-8960-72470730bdff)

**Comment by anonlegionoke** [comment] 2024-08-25 04:00
Let me try to simplify it further.

The touchpad gesture I were using - 3 finger up and down.

OK well this is what happens when switching windows with the keyboard. Shortcut used Super + left/right (I don't remember if it's a gnome/PaperWM default or I remapped it)


In this video you can see that when I was trying to switch windows using shortcuts in the second workspace, the window from the first workspace appears on top of the windows from second workspace. This is what happens when waking up from sleep too.

https://github.com/user-attachments/assets/0406bd60-6709-486b-9e62-9b8d0fe99a61

PS: I haven't done disable all extensions and re-login yet, posted this quickly when I could record it.

**Comment by anonlegionoke** [comment] 2024-08-25 04:15
Update - No matter how hard I tried I could not reproduce the issue with only PaperWM enabled after re-login :(

Now I need to find which one of my extensions was responsible for this.

**Comment by jtaala** [comment] 2024-08-25 04:20
> In this video you can see that when I was trying to switch windows using shortcuts in the second workspace, the window from the first workspace appears on top of the windows from second workspace. This is what happens when waking up from sleep too.

Okay, I think this issue is different from the original issue (I've seen this one before sometimes when coming out of sleep, opening laptop lid, and can semi-reproduce - still got to fix that one).  This can usually be fixed by doing a PaperWM workspace `Switch to workspace above / below` type thing (default keybinds being `Super`+`Page Up`, `Super` + `Page down`).

> Update - No matter how hard I tried I could not reproduce the issue with only PaperWM enabled after re-login :(

> Now I need to find which one of my extensions was responsible for this.

If I had to hazard a guess, I'd say look for any extension that might change workspace switching animations.  From your original video, it looks like PaperWM is trying to do it's own animation (maybe due to Gnome not doing it's normal workspace switching animation - I'll have a look at PaperWM code here).

**Comment by jtaala** [comment] 2024-08-25 04:40
Okay, I've found some PaperWM code that looks suspicously related to the og issue:

https://github.com/paperwm/PaperWM/blob/2c3e76a63951fa2f278e89ffc9cacfa59e5fe994/navigator.js#L452

This is on the `Navigator.destroy()` code, which is active when using PaperWM's window switcher.  It's forcing a PaperWM workspace animation (not default gnome anim).  Anyways, not sure what conditions you have that trigger this issue, but could be related to a corner-case related to that code.

Let me know if you track down an extension that's leading to the triggering of this issue and I can try reproduce (with that extension) and isolate.

Cheers.

**Comment by anonlegionoke** [comment] 2024-08-25 06:36
> this.space.activate(false, true); 

> This is on the Navigator.destroy() code, which is active when using PaperWM's window switcher. It's forcing a PaperWM workspace animation (not default gnome anim).

Interesting.

I tried various combinations of extensions, but for my life I couldn't reproduce the same issue. Still I do have some extensions on my sus list(some of them were installed and previously enabled but been disabled during the issue).

just-perfection-desktop@just-perfection
[pip-on-top@rafostar.github.com](mailto:pip-on-top@rafostar.github.com)
[auto-move-windows@gnome-shell-extensions.gcampax.github.com](mailto:auto-move-windows@gnome-shell-extensions.gcampax.github.com)
 [default-workspace@mateusrodcosta.com](mailto:default-workspace@mateusrodcosta.com)
[window-on-top@yousafesaeed.github.io](mailto:window-on-top@yousafesaeed.github.io)

Previously enabled(don't know if they could be responsible)
windowgestures@extension.amarullz.com
useless-gaps@pimsnel.com
Roundedwindowcorners.

This may not be really useful. But I could not find any more info :(

Thanks a lot for PaperWM btw.

**Comment by jtaala** [comment] 2024-08-28 21:14
Just a thought - had you updated PaperWM recently but not logged-out, logged-in? (which is generally).

Only thing I can think of atm.  Let me know if you discover anything and can reproduce again over the next week or so.

**Comment by jtaala** [comment] 2024-08-29 12:31
Closing this one, are it seems you're not able to reproduce.  Let us know if you have any luck reproducing.

**Closed as completed by jtaala** 2024-08-29 12:31 UTC
Labels: bug, extension-conflict, can't reproduce
