### ISSUE TITLE
Esc KeyRelease event leaks from navigator

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#70] opened 2018-07-05 21:45 UTC
- run `xev -event keyboard`,
- start switching to another workspace
- abort (ie. press Esc) 

The xev window recieved a KeyRelease event for ESC.

This is quite annoying when eg. netflix are playing since it react on keyrelease and quits the playing show :(

Note: happens for alt-tab too. (everything that is based on SwitcherPopup)

TODO: Check if it happens in vanilla gnome-shell too

**Comment by hedning** [comment] 2018-07-08 10:39
This doesn't happen with X11 windows in wayland at least (haven't got a test case for wayland windows though).

**Comment by olejorgenb** [comment] 2018-07-08 11:05
Delaying destroy until keyrelease fixes the problem:

```
diff --git a/js/ui/switcherPopup.js b/js/ui/switcherPopup.js
index a53b1e6e9..21fc2b70c 100644
--- a/js/ui/switcherPopup.js
+++ b/js/ui/switcherPopup.js
@@ -192,13 +192,18 @@ var SwitcherPopup = new Lang.Class({
         if (this._keyPressHandler(keysym, action) != Clutter.EVENT_PROPAGATE)
             return Clutter.EVENT_STOP;
 
-        if (keysym == Clutter.Escape)
-            this.destroy();
+        if (keysym == Clutter.Escape) {
+            this.destroyMe = true;
+        }
 
         return Clutter.EVENT_STOP;
     },
 
     _keyReleaseEvent(actor, event) {
+        let keysym = event.get_key_symbol();
+        if (this.destroyMe === true)
+            this.destroy();
+
         if (this._modifierMask) {
             let [x, y, mods] = global.get_pointer();
             let state = mods & this._modifierMask;

```

**Comment by hedning** [comment] 2019-01-18 23:02
Happens on wayland too, but only for wayland clients.

**Comment by jtaala** [comment] 2024-01-29 22:25
Closing as upstream can't reproduce (and hence wont' address).  Currently fixed (worked around) in PaperWM.

**Closed by jtaala** 2024-01-29 22:25 UTC
Labels: bug, upstream
