### ISSUE TITLE
[Feature Request] Sticky/docked Windows

### ISSUE THREAD

**Issue by darkfrog26** [paperwm/PaperWM#339] opened 2020-09-22 17:52 UTC
I've been using this extension for a while and love it, but I'm about to switch from two monitors to a single ultrawide monitor. I usually keep Chrome open on the right monitor while switching between development tools in the left. Once I have a single monitor though, this won't be easily achieved. If I could "lock" or make a window "sticky" so that it remains stationary as I cycle through other windows, this would drastically improve useability on ultrawide monitors.

**Comment by hedning** [comment] 2020-09-22 17:55
See #50 and https://github.com/paperwm/PaperWM/pull/194. So we'll see when I get the time :)

**Comment by darkfrog26** [comment] 2020-09-22 20:55
Nice! Thanks @hedning!

**Comment by jtaala** [comment] 2023-04-08 05:40
Closing as duplicate of #50 (and #50 is on our enhancement list and worked on in PR #194).

**Closed** 2023-04-08 05:40 UTC
