### ISSUE TITLE
Doesn't work correctly with rounded window corners reborn 

### ISSUE THREAD

**Issue by TheToxicToast** [paperwm/PaperWM#884] opened 2024-06-27 12:13 UTC
**Describe the bug**
Some apps doesn't work correctly when both plugins are enabled, eg sublime text and kitty, sublime text is visually glitched out and kitty doesn't show rounded corner

**To Reproduce**
enable both plugins

**Expected behavior**
have rounded corner and normal app placement

**System information:**
Distribution: Fedora Linux 40 (Workstation Edition)
GNOME Shell: 46.2
Display server: Wayland
PaperWM version: 46.12.1
Enabled extensions:
- gsconnect@andyholmes.github.io
- just-perfection-desktop@just-perfection
- blur-my-shell@aunetx
- bluetooth-quick-connect@bjarosze.gmail.com
- clipboard-indicator@tudmotu.com
- caffeine@patapon.info
- Vitals@CoreCoding.com
- unite@hardpixel.eu
- thinkpad-battery-threshold@marcosdalvarez.org
- drive-menu@gnome-shell-extensions.gcampax.github.com
- paperwm@paperwm.github.com
- wiggle@mechtifs
- disable-workspace-animation@ethnarque
- (I have rounded window corners reborn disabled)

**Comment by jtaala** [comment] 2024-06-27 13:14
Closing as duplicate of #763 (rounded corner extensions). 

See this comment: https://github.com/paperwm/PaperWM/issues/763#issuecomment-1915477521

E.g. I don't use rounded corners and this is not something I'm interested in working on.  I would accept a PR though if you (or someone else) would like to work on this.

**Closed as completed by jtaala** 2024-06-27 13:14 UTC
Labels: duplicate, extension-conflict
