### ISSUE TITLE
Hotkeys on dead keys not caught depending on which application is focused

### ISSUE THREAD

**Issue by schoel-bis** [paperwm/PaperWM#768] opened 2024-01-31 11:36 UTC
**Describe the bug**

On a German keyboard the key above tab is a dead key (^ which will combine with some letter e.g. ^ then o → ô). In some applications (e.g. Gnome Terminal, Gnome text editor, LibreOffice, Firefox when a text input field is focussed), using a hotkey combination with that key (e.g. Super + `<key above tab>` → switch to another workspace) will simply cause that dead key to be passed to that application instead of the PaperWM action happening. For other applications (e.g. Firefox with no input focussed, Chrome, …) this does not happen and the PaperWM action is properly executed.

**To Reproduce**
1. Add a German keyboard layout with dead keys
2. Open one of the aforementioned applications and make sure you are in text input mode
3. press Super + `<key above tab>`
4. See an underlined ^ appear in your text input, waiting for the second character to combine with
5. Switch to some other application (e.g. Files)
6. Press Super + `<key above tab>`
7. See PaperWM switch desktops

**Expected behavior**

When pressing the Super + `<key above tab>` combination workspaces should always be switched.

**System information:**

Fedora 39
Gnome 45.3
PaperWM 45.9.1 installed from extensions.gnome.org

**Comment by jtaala** [comment] 2024-01-31 22:55
Thanks @schoel-bis - I can reproduce this.  Looks like we need to add `dead_circumflex` mapping to `above_tab` behaviour in PaperWM.

Will look into this.

**Comment by jtaala** [comment] 2024-02-01 11:43
So, after digging into this, this is an upstream Gnome issue (same thing happens in Gnome without PaperWM) and not something PaperWM can fix (or work around it appears).

See below (vanilla gnome, german keyboard layout, no PaperWM).

In the video below, (vanilla Gnome) I'm simply pressing `super`+`above_tab` with german keyboard layout - which is switching windows in application, but when I focus on setting app, that keybind isn't caught - which is what you're seeing (e.g. it depends on the application):

https://github.com/paperwm/PaperWM/assets/30424662/07f2b7d3-32a6-42ed-80c4-397e6fc68c7f

Gnome seems to treat `super`+`above_tab` for a layout with dead keys specially.  Note, that remapping `super`+`above_tab` to `alt`+`above_tab` (which shows up as `alt`+`dead circumflex` in PaperWM) in such a layout works in all applications:

![image](https://github.com/paperwm/PaperWM/assets/30424662/f1b81119-f87d-4398-b2ae-1b576fa951e4)

Hence, your options in Gnome (and therefore PaperWM) to have keybindings work regardless of app are:

- remap any `super`+`above_tab` keybindings to alternates (e.g. `alt`+`above_tab`, `ctrl`+`above_tab`, etc.);
- use non-deadkey layouts (and remap any keybindings in PaperWM);

Given this is an upstream Gnome issue, I'd encourage to you file this issue with Gnome (although I expect this to be by design in Gnome):
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues

**Comment by jtaala** [comment] 2024-02-01 11:53
I'm planning on closing this issue (as an upstream Gnome issue) in a few days.

**Comment by jtaala** [comment] 2024-02-01 21:21
Note if using a non deadkey layout (e.g. German (no dead keys) , you could instead use Gnome's Compose key for special characters?, e.g. if using `Caps Lock` as Compose key:

![image](https://github.com/paperwm/PaperWM/assets/30424662/a8223d2f-ac4b-418e-9907-6a01edc966d3)

pressing `caps_lock` then `above_tab` then o → ô 

Not sure what else can be done here.

**Comment by schoel-bis** [comment] 2024-02-02 08:38
Thank you very much for your amazing research and support. It hadn't even crossed my mind that this might be an upstream issue. I don't think the compose key is for me since I need to type a lot of French and also make regular use of quite a few other dead keys, so I would have to adapt significantly my typing habits while I am already adapting my window managing habits due to the switch to PaperWM. I have settled on Super+Tab for switching the desktops for now and will probably file a bug with gnome-shell over the weekend.

**Closed as not planned** 2024-02-02 22:17 UTC
Labels: wontfix, upstream
