### ISSUE TITLE
Telegram not getting "tiled" properly as startup application

### ISSUE THREAD

**Issue by Rutherther** [paperwm/PaperWM#719] opened 2023-11-26 15:34 UTC
**Describe the bug**
I have Telegram, Discord and Firefox automatically start, I have configured that using gnome tweaks tools. The problem is that Telegram (and I would guess more apps, but haven't had issues with anything else yet), somehow gets tiled only partially. When I try resizing it with PaperWM shortcuts (like Cycle through userful window widths), and there is a window right of Telegram, it doesn't get moved. So Telegram can overflow to that window, or if I shrink it more, there is a lot of space between the two apps.

Another issue is that when I am in different workspace on the monitor where I had workspace with Telegram opened, it glitches through sometimes. So instead of the window on workspace I have focused, I see telegram, it disappears after some cursor movements.

I usually just restart Telegram to fix it. That makes me guess it's a problem of starting Telegram before an important part of PaperWM has been started.

**To Reproduce**
I am unfortunately unable to reproduce this without setting it as a startup app. And I don't have a VM with Gnome+PaperWM set up yet. That makes trying to figure out what's going on pretty tough. (as I have to relogin to reproduce it) If it's not clear from the description, I will come up with more exact steps (after I install a VM, which I will definitely do at some point this week)

**Expected behavior**
All apps getting tiled properly, without glitches to other workspaces and with no overflows to other windows.

**Comment by Rutherther** [comment] 2023-11-26 17:42
One thing I forgot to mention. The window is somehow tiled. It's not completely untiled. I am able to move it with keybindings to left/right of other windows. The only problem is it's size. It looks like it's not _updated_ when I resize it.

**Comment by jtaala** [comment] 2023-11-27 06:02
Yes, autostart applications generally start before PaperWM and can cause some issues.

Can you post a pic/video of what you mean by "not completely tiled"?

Thanks.

**Comment by Rutherther** [comment] 2023-11-27 16:40
I have telegram on workspace 9. I first triggered the glitching prior to starting the video, to make it shorter. I am not sure exactly what triggers it, but it's related to cursor movement. I then switch to workspace 9. At the end of the video I put the window to scratch layer, and back (Super+Shift+G, I think that is the default keybinding). That fixes the problem.

https://github.com/paperwm/PaperWM/assets/12197024/8a131dda-ea82-48a5-bdf7-2bca2196d89d

**Comment by Lythenas** [comment] 2023-11-27 19:15
I had similar issues with firefox and thunderbird when I had set it to autostart. Although thunderbird seems to have fixed itself after the last big update to it. But I just stopped setting firefox to autostart partly because of this problem. I tried to debug the issue a bit then, but I couldn't figure out anything useful. But it looked like the video you posted. Unfortunately from the video I still have no clue what is happening... It seems like some PaperWM internal state is inconsistent somehow.

**Comment by jtaala** [comment] 2024-01-28 07:39
Hey all, can you let me know if this is still an issue on latest `release`?

I fixed an issue which looked related (#758).  I also can't reproduce this one with telegram (flatpak version) on autostart.

**Comment by jtaala** [comment] 2024-01-29 22:32
Can't reproduce this on any telegram, and having it autostart (on latest PaperWM).

Let me know if still an issue, otherwise will close this in a few weeks.

**Comment by jtaala** [comment] 2024-03-29 12:25
Closing as not heard back on this issue.

**Closed as completed by jtaala** 2024-03-29 12:25 UTC
Labels: bug, no longer valid?, can't reproduce
