### ISSUE TITLE
Performance issues with Video windows

### ISSUE THREAD

**Issue by anderssv** [paperwm/PaperWM#385] opened 2021-06-11 07:36 UTC
First of all: I love PaperWM, it fits perfectly with how I want to use the desktop.

But sadly I can't use it because it looks like it slows down **everything** whenever I have live video on. And for me that's all the time as we have a "always on" Zoom room that we collaborate in. Zoom is worst, but it seems it affects other things like video in browser as well.

I have done a lot of triage, and it seems the issue "goes away" when I turn off PaperWM.

I know this isn't the best of bug reports, but maybe it triggers something that you already know of. Is there some loop etc that keeps iterating the windows and becomes less viable when those windows contains video? Hope someone knows, because I really want to turn it back on. :)

Cheers,
Anders,

**Comment by anderssv** [comment] 2021-06-17 17:29
Forgot to mention: On Ubuntu 21.04 :)

**Comment by lediur** [comment] 2023-02-24 22:36
I think I run into this performance issue with Firefox screensharing as well. Slack huddle screen sharing seems to be alright. It seems to cause low framerate / high input latency on the entire desktop. 

The machine is pretty high-end (5950X, RTX 3080 with proprietary drivers) so there shouldn't be any performance issues dealing with screensharing or 2D graphics.

**Comment by jtaala** [comment] 2023-04-08 05:55
Hey all, so, are you still seeing this?  I ask since I recall seeing similar issues before #477 was merged.

Long story short, #477 fixes an issue where locking screen (and then unlocking) can cause it to very rapidly go through lots of disable/enable cycles - which had potential to create lots of signal connects without destroying previous signal connects - so on events it could potentially run lots of the same event actions.

Anyways, let me know if you're still seeing this in recent version of PaperWM (basically if you've checked out `develop` branch after March 17 2023).

Planning on closing this issue in a month or so, unless anyone is still seeing this behaviour.

**Comment by lediur** [comment] 2023-04-08 06:35
I'm happy to try reproducing tomorrow. I forget if my issue is with capturing the screen for screen sharing or with playing back video from videoconference calls. 

On today's `develop`, I think video playback works okay on a single active 4K monitor, but I think I still see some performance issue (micro stuttering, inconsistent frame timing on smooth pans) with full screen web video when playing a video on one of multiple active 4K monitors (well, one TV and one monitor, both running at 100% scaling).

<details>
<summary>edit: I think the version I was previously running was after the commit you mentioned, so I collapsed this section as no longer relevant.</summary>

I did notice when I pulled `develop` today (I was 20 or so commits behind) that pressing Super to open the overview screen felt much smoother. In the past, I noticed that over time in a login session, PaperWM appeared to develop a stutter (0.5-1sec frame) at the beginning or end of the animation entering or exiting the overview screen. This issue appeared to resolve when I turned off PaperWM, and went away when toggling the extension. A login session would typically persist over a few days and multiple screen lock and sleep events, so #477 might have addressed that issue.
</details>

**Comment by lediur** [comment] 2023-04-12 03:25
I just tried a few tests on my machine running [`9f3a5781`](https://github.com/paperwm/PaperWM/tree/9f3a5781b02d712454403dd65b841bf11b7478fe):

- playing two 1080p streams from Piped simultaneously ([one](https://piped.qdi.fi/watch?v=KNINXsObzMU), [two](https://piped.chauvet.pro/watch?v=rQCEYyEWMt8))
- screen sharing my desktop to a Zoom call in the browser while playing the 1080p streams. had some issues with the screensharing capture framerate but I think that's on Firefox / Zoom / Wayland rather than PaperWM
- watching a screen share from a Zoom call in the browser while playing the 1080p streams

Performance seems pretty snappy now, with the caveat that I recently rebooted this machine so uptime is about an hour.

**Comment by jtaala** [comment] 2023-05-20 11:55
Closing this as resolved given the last comment and not further comments.  Feel free to comment here again in the future if you see this issue again.

**Closed by jtaala** 2023-05-20 11:55 UTC
Labels: bug, no longer valid?
