### ISSUE TITLE
Some windows become "sticky" after a while

### ISSUE THREAD

**Issue by damageboy** [paperwm/PaperWM#315] opened 2020-06-09 10:38 UTC
I'm not sure if it's something I'm doing, or if it happens all by itself in PaperWM, but some windows, after a while suddenly become "sticky" in the sense that they appear on all desktops, and all float above the existing windows managed by PaperWM:

![image](https://user-images.githubusercontent.com/125730/84138008-4208be00-aa56-11ea-94ce-48208e21a2a4.png)

In this case, this is happening with Chrome, but I've had it happen to me on occasion for different windows.

It might be just me pressing some weird combo triggering this, but I can't figure out what is actually happening / causing this.

**Comment by hedning** [comment] 2020-07-02 20:54
Looks like you've accidentally tiled the window (by dragging it to an edge) which we don't support. (It also looks like it's «on-all-workspaces» which is why you're seeing it on all workspaces).

I recommend turning off `edge-tiling` (can be done in gnome-tweaks under the «Windows» tab).

**Comment by damageboy** [comment] 2020-07-06 13:24
I don't see that it was ever turned on to begin with, but I'll make sure to check next time it happens

**Comment by dimaqq** [comment] 2022-01-23 23:36
I have edge tiling off, and somehow this happened to me. Chrome became "sticky" or rather "on top of other windows which paperwm tiles correctly" after I dragged Chrome (by its own toolbar) to the external monitor.

**Comment by jtaala** [comment] 2023-04-08 05:12
> I have edge tiling off, and somehow this happened to me. Chrome became "sticky" or rather "on top of other windows which paperwm tiles correctly" after I dragged Chrome (by its own toolbar) to the external monitor.

That one just sounds like dragging a tab/window out of tiling to add it to the scratch layer (which is PaperWM functionality), e.g:

https://user-images.githubusercontent.com/30424662/230704250-52412289-d6af-4128-aef2-e2dd8815ecb2.mp4

It might also be due to having a `Scratch` window (currently scratched) select and creating a new window (which will also be then `Scratch`'ed.

I haven't seen this happen randomly or unexpectedly though.  Is anyone able to reproduce this - or it's still an issue for you?

Let me know if this is still an issue for anyone, otherwise I'll look at closing this issue in a month or so.

**Comment by dimaqq** [comment] 2023-04-08 12:27
It's been a while, I don't think I've had it happen lately.

**Comment by jtaala** [comment] 2023-05-15 19:23
Closing as been more than a month since couldn't reproduce (and hasn't been reported by others) and reporter hasn't seen this since then (see last comment).

**Closed by jtaala** 2023-05-15 19:23 UTC
Labels: no longer valid?
