### ISSUE TITLE
When minimap is active, other hotkeys are disabled

### ISSUE THREAD

**Issue by setzer22** [paperwm/PaperWM#268] opened 2020-03-13 19:08 UTC
Hi, first of all, many thanks for this awesome project! Now onto my issue/question:

I find it confusing that when I'm pressing Super+Left/Right (and the minimap is active) I cannot use other hotkeys, like for instance Shift+Super+Left/Right to change monitor. Is this intended or undesired?

Many thanks!

**Comment by hedning** [comment] 2020-03-13 20:14
Cheers, glad you like it :)

That's indeed not intended when it comes to the change monitor keybindings. Though I foresee some edge cases that might need fixing (eg. what happens when changing monitors while previewing workspaces with eg. `<Super>above_tab`).

In general we aim to make the hotkeys usable in as many scenarios as possible (you can for instance navigate, remove windows and spawn new windows while flipping through workspaces). There's some actions we haven't figured out how to integrate, mainly `<Super>Tab`, as we're not sure how to make the transition from linear to time based navigation make sense. 

For hotkeys that aren't ours the problem is unfortunately harder. Starting navigation (eg. with `<super>left`) starts a mini mode (like `<Super>Tab` does in plain gnome shell), where we need to take full control of the keyboard. And for some reason it isn't possible to just ask gnome shell what handler is naturally associated with a hotkey and then run it. So for native bindings we need to set up that manually per hotkey/action (this is done for the minimize action).

**Comment by olejorgenb** [comment] 2020-03-14 21:56
If anyone wants to take a crack at this:
- Download gnome-shell source code: https://gitlab.gnome.org/GNOME/gnome-shell
- Download mutter source code: https://gitlab.gnome.org/GNOME/mutter
- Find the mutter action name of the action you want to implement support for (usually possible by looking here `dconf-editor /org/gnome/desktop/wm/keybindings/` - the settings keyname is the action name)
- Find out how this action is implemented: Search the gnome-shell and mutter code for the action name. (`setCustomKeybindingHandler` in gnome-shell)
- Figure out how to trigger the action programatically
- If the action comes from mutter it's action id is listed in Meta.`KeyBindingAction`
- If the action comes from gnome-shell, use the `Keybindings.getActionIdByActionName` method to get the actionId
- See https://github.com/paperwm/PaperWM/blob/d47206cc017df0a8ce63f2612d25c1db7d609267/navigator.js#L168 for how minimize is done

**Comment by hedning** [comment] 2020-03-14 22:05
There's a list of native actions here, https://github.com/paperwm/PaperWM/blob/clutter-dnd/keybindings.js#L566, as we reset the custom handlers on disable.

**Comment by jtaala** [comment] 2023-09-04 11:36
This issue should be resolved by #510.

Let me know if this is still an issue, otherwise will close this in a couple of weeks.

**Closed** 2023-09-16 08:31 UTC
Labels: good first issue, no longer valid?
