### ISSUE TITLE
Workspace name keeps changing infinitely

### ISSUE THREAD

**Issue by letavocado** [paperwm/PaperWM#497] opened 2023-03-21 10:49 UTC
**Describe the bug**
When changing the workspace to the topmost position, the workspace name starts changing endlessly

**To Reproduce**
1. scroll workspaces vertically to the topmost position with a three-finger gesture

**Expected behavior**
Maybe keep last scrolled workspace name. I don't know.

**Screencast**
[Screencast from 2023-03-21 16-19-37.webm](https://user-images.githubusercontent.com/31704887/226581900-5884fc7c-3930-4a43-9f8c-35f232f248b9.webm)

**System information:**
```
Distribution: Arch Linux
GNOME Shell 43.3
Wayland, mutter 43.3
PaperWM branch/tag: develop
PaperWM commit: 7fa25a6072a8ccd51ecbf154d030f23d2ed98d4e
Enabled extensions:
- paperwm@hedning:matrix.org
- gestureImprovements@gestures (NOTE!!!)
- clipboard-history@alexsaveau.dev
- blur-my-shell@aunetx
- gnome-ui-tune@itstime.tech
- Vitals@CoreCoding.com
- trayIconsReloaded@selfmade.pl
- switcher@landau.fi
- dash-to-dock@micxgx.gmail.com
- user-theme@gnome-shell-extensions.gcampax.github.com 
```

**Additional context**
Scrolled using touchpad gestures (used gestureImprovements@gestures extension for three-finger gesture)

**Comment by Lythenas** [comment] 2023-03-21 18:32
I also noticed this while testing #493

**Comment by jtaala** [comment] 2023-03-21 20:08
Hey @Lythenas, I can't reproduce this - are you also using `gestureImprovements@gestures` extension?

My workspaces just wrap around with 3-finger gesture.

**Comment by Lythenas** [comment] 2023-03-21 20:12
No I'm not using any extensions that change swiping and the like. For me it looks very similar to the video in the issue and it keeps switching as long as I keep swiping. And them some times it also wrapps around. Not sure if I'm maybe swiping to hard^^

Swiping in the other direction always seems to work.

But in general I also find it a bit hard to control the workspaces well with swiping but that just might be a sensitivity thing and I very rarely use a touch pad anyway.

**Comment by jtaala** [comment] 2023-03-21 20:13
But something else weird I haven't noticed before (I usually just switch paperwm workspaces with keybinds rather than 3-finger gesture): in 3-finger gesture, after wrapping around, the current workspace no longer appears when swiping through.

**Comment by jtaala** [comment] 2023-03-21 20:17
> might be a sensitivity thing and I very rarely use a touch pad anyway

Good suggestion!  Yep, I just pushed my trackpad senstivity all the way up and after swiping up for a bit I could reproduce.

@letavocado - good find!

**Comment by jtaala** [comment] 2023-07-29 09:27
Fixed by #567.

**Comment by jtaala** [comment] 2023-07-30 07:12
Reopening this - the previous fix in #567 caused a few timing issues in workspace switching (see #570) so had to revert.

**Comment by jtaala** [comment] 2024-06-18 09:23
Just cleaning up some older issues. I can't reproduce this issue on latest PaperWM.  I'll close in a few weeks unless this is still an issue on recent versions of PaperWM (e.g. on Gnome 45, 46 etc.).

**Comment by letavocado** [comment] 2024-06-18 11:50
Hey @jtaala! I'm not tested it. But seems it's no more issue.
 
I'm on Hyprland now, but I missing by PaperWM. Thinking about make some mixed stuff from Hyprland+PaperWM (not codebase, just concepts). I love how PaperWM's can move for 2 vectors (vertically workspaces, and horizontally windows). And using Super+> and Super+< for my every workspace. Thank you for great project! 

PaperWM 🩵

Cheers! ✨

**Comment by jtaala** [comment] 2024-06-18 23:18
> I'm on Hyprland now, but I missing by PaperWM. Thinking about make some mixed stuff from Hyprland+PaperWM (not codebase, just concepts). I love how PaperWM's can move for 2 vectors (vertically workspaces, and horizontally windows). And using Super+> and Super+< for my every workspace. Thank you for great project!

Hey @letavocado - I've heard awesome things about hyperland.  Seems like there's a few [other WMs](https://github.com/paperwm/PaperWM?tab=readme-ov-file#related--similar-projects) that are using PaperWM style tiling (scrolling / tiling) and that's a great thing.

**Comment by letavocado** [comment] 2024-06-20 11:04
Oh-oh, horizontal scrolling is gaining momentum! You've set a good trend bro! 😎

**Closed as completed** 2024-07-21 04:05 UTC
Labels: bug, no longer valid?

**Comment by letavocado** [comment] 2025-01-22 07:22
Good day my friend @jtaala! I'm back to using PaperWM again, after Hyprland and Cosmic. I do love PaperWM! Thank you so much! I appreciate your efforts. 💓 

Cheers! ✨
