### ISSUE TITLE
Incorrect new window height when some scratch window exists

### ISSUE THREAD

**Issue by kassick** [paperwm/PaperWM#671] opened 2023-11-07 22:29 UTC
**Describe the bug**

When there are scratch windows (visible or not), new windows may not be resized vertically to fill their allocated column

**To Reproduce**
1. Open two windows (winA, winB)
2. Move winB to scratch
3. Move winB towards the left side of the space.
4. Open another window (of any app) -- winC

**Expected behavior**

winC occupies the whole vertical space of the screen

**Observed behavior**

winC is correctly allocated in it's column, but it does not fill all the column vertical space

**Screenshots**

[Gravação de tela de 2023-11-07 19-12-02.webm](https://github.com/paperwm/PaperWM/assets/21071/625e4607-ec7d-4150-bd85-8ce92853da72)

**System information:**

Distribution: Fedora Linux
GNOME Shell 44.6
Display server: Wayland
PaperWM branch/tag: gnome-44
PaperWM commit: 9d01fa2aeb679f331f195d72a3c8c8c50e1eadf9
Enabled extensions:
- custom-hot-corners-extended@G-dH.github.com
- dash-to-dock@micxgx.gmail.com
- switcher@landau.fi
- bluetooth-quick-connect@bjarosze.gmail.com
- paperwm@paperwm.github.com
- just-perfection-desktop@just-perfection
- caffeine@patapon.info
- appindicatorsupport@rgcjonas.gmail.com

**Additional context**

I started observing this behaviour after leaving some console windows with htop/logs on scratch. At first, I assumed that emacs or tilix was refusing the resize -- but then I noticed it happened with gnome-extensions-app and other less finicky apps.

It does not make a difference if I have the scratch windows visible or not -- but it does makes a difference if the windows in scratch are more towards the left (the bug happens) or the right (the bug does not happen).

[Gravação de tela de 2023-11-07 19-27-14.webm](https://github.com/paperwm/PaperWM/assets/21071/30f1332f-b3a8-4f68-b368-c283795be6a9)

**Comment by jtaala** [comment] 2023-11-08 00:32
Thanks for reporting @kassick.  Question - are you running multiple monitors? (and is one of them another resolution/dpi)?

**Comment by jtaala** [comment] 2023-11-08 01:20
Although, given it looks like you're running in a nested shell - probably not the issue I was thinking.

Anyways, will have a look at this.

**Comment by kassick** [comment] 2023-11-08 02:25
Indeed, the first video is a nested shell, so no external monitors on that one.

**Comment by jtaala** [comment] 2023-11-09 07:56
Wowzers... I can't believe I haven't seen this before.  All good, I can reproduce this, so will be able to fix.

**Comment by jtaala** [comment] 2023-11-09 08:42
Ah, most likely from changes in https://github.com/paperwm/PaperWM/pull/647

**Comment by jtaala** [comment] 2023-11-09 10:10
Hey @kassick,

Implemented a fix for this.  Can you please test this out and confirm it does fix this issue for you?

```
git fetch --all
git checkout fix-671-incorrect-window-height-when-scratch-exists
./install.sh
```

then logout / login.

**Comment by kassick** [comment] 2023-11-09 14:33
Thanks @jtaala! You rock!

I'll be testing it today and I'll let you know if I find any regression.

So far, so good.

The only oddity is that when the single window  (across all spaces) was a scratch window, hidden from view, when I opened the a second window (via Switcher) on a visually empty space, it was opened in scratch too -- but maybe that predates these changes; I'll check it later..

**Comment by jtaala** [comment] 2023-11-09 20:32
> The only oddity is that when the single window (across all spaces) was a scratch window, hidden from view, when I opened the a second window (via Switcher) on a visually empty space, it was opened in scratch too -- but maybe that predates these changes; I'll check it later..

Nah, that's current behaviour - basically if a scratch window was selected last (and in the absence of no other tiled windows in other spaces - which would get selected if a user switched to that space)... then the next window would get scratched too.

Basically in that use case - the scratch layer is still "active" (in the absence of tiling windows).  Hence new windows will be scratched as mentioned in https://github.com/paperwm/PaperWM#scratch-layer.

**Comment by jtaala** [comment] 2023-11-10 12:16
@kassick any issues you noticed with this PR?

Hoping to merge it in.

**Comment by kassick** [comment] 2023-11-10 13:20
LGTM

Looks like the issue is gone.

**Closed as completed** 2023-11-10 19:22 UTC
Labels: bug
