### ISSUE TITLE
Workspace label is misaligned with dash-to-panel 26

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#258] opened 2020-03-08 07:28 UTC
![image](https://user-images.githubusercontent.com/47434276/76158483-0c58df80-60cb-11ea-9efe-a5db9ada5fc7.png)
Got a new linux machine and put the latest PaperWM on it. I noticed that this issue has once again surfaced. I recall there was a resolution earlier, but after searching issues for quite a while I haven't been able to find a way around this misalignment. Any help appreciated, thanks!

**Comment by hedning** [comment] 2020-03-08 10:09
I'm unable to reproduce with the default theme and without extensions that modify the top bar. What theme and extensions are you using (dash-to-panel etc.)? Also what gnome-shell version are on?

We haven't made any changes to the logic since last time, so not sure what's going on (might be changes in gnome-shell 3.36 if you've just upgraded).

Now some things to check:
- Does switching workspaces fix the problem?
- Does changing the workspace name fix the problem?

**Comment by danielyzli** [comment] 2020-03-08 20:38
Sorry I didn't include enough information; I am on Pop! OS 19.10 with gnome shell 3.34.3. I am indeed using dash to panel. Switching workspace does not make the issue go away. Changing workspace name causes both names to change at the same time.

**Comment by hedning** [comment] 2020-03-08 22:14
Hmm, right, I'm able to reproduce with gnome-shell-3.34.4 and dash-to-panel 26. It works correctly in gnome shell 3.35.92 and dash-to-panel 27. dash-to-panel 27 also works in gnome-shell 3.34 so I'd try to upgrade to the latest dash-to-panel which was relased today.

When asking what coordinates the label have relative to the panel we get gibberish back when dash-to-panel is active for some strange reason. No idea how that happens tbh.

**Comment by danielyzli** [comment] 2020-03-08 23:12
Yes, upgrading to dash-to-panel 27 fixed it. Thanks!

**Comment by alextremblay** [comment] 2020-03-23 13:59
Hello, 

First off, thanks for making PaperWM. I've only been using it for a few days but am already in love with it.

I'm having almost the same issue as described in the opening post of this issue, with two important caveats:

I don't have any other extensions enabled, and I'm specifically only experiencing this issue on workspaces that are not workspace 1

I have two monitors, and no matter which monitor workspace 1 is on, that workspace looks correct, does not have the extra offset workspace name, but every other workspace does

using latest (i think?) dev branch of PaperWM on gnome-shell v3.32.2, tested in wayland and x11, currently on x11

Please let me know if there's any other info I can provide

**Comment by vincentmathis** [comment] 2020-10-23 04:30
I have the same issue I think. Top left corner shows misaligned workspace indicator which is not necessary because there already is one in Dash-To-Panel.

paperwm r1565.40a7509-1
gnome-shell 3.38.1-1
dash-to-panel 40-1

**Comment by jtaala** [comment] 2023-09-04 11:24
Let me know if this is still an issue on a recent version of PaperWM (I can't reproduce this).

Planning on closing this in a couple of weeks.

**Closed** 2023-09-16 08:31 UTC
Labels: extension-conflict, no longer valid?
