### ISSUE TITLE
Wallpaper is stretched in a wierd way when using different display scalings

### ISSUE THREAD

**Issue by Pajn** [paperwm/PaperWM#247] opened 2020-02-13 07:43 UTC
I have multiple displays with the same resolution but different sizes. After enabling fractional scaling in gnome and reducing the scaling on the larger displays to 150% I get this look on them:

![Screenshot from 2020-02-13 08-40-34](https://user-images.githubusercontent.com/817422/74412005-cba7d680-4e3c-11ea-8eae-c1068868f318.png)

**Comment by hedning** [comment] 2020-02-13 08:32
Right, I'm able to reproduce.

Looks like we'll need to recreate the background when we change monitors to get it correct.

**Comment by hedning** [comment] 2020-02-13 08:46
Pushed a fix to background-scale-fix (d91f777aceaea1e4f89af6077e6152728e5308d3), will need some more work as it's very aggressive in destroying and making new backgrounds, but it seems to work.

**Closed** 2020-02-13 11:02 UTC
Labels: bug

**Comment by Pajn** [comment] 2020-02-13 12:14
It works great, thanks!
