### ISSUE TITLE
Horizontal resizing sometimes scrolls entire workspace, not just windows to the right of the resizing window

### ISSUE THREAD

**Issue by lediur** [paperwm/PaperWM#424] opened 2022-10-11 20:25 UTC
## Description

I noticed an issue that sometimes appears on workspaces with many windows. After a while, using keyboard shortcuts to resize window width causes the entire set of windows to scroll horizontally during the resize, not just the windows to the right of the resizing window. This causes the whole monitor full of windows to jump to the right and then scroll to the left on each resize step, which makes it somewhat disorienting to use.

I noticed that using the resizing shortcuts when in the "workspace change" view (holding super while moving between workspaces) somehow fixes this issue (at least temporarily).

## Steps to reproduce

Unclear at the moment. I'm unable to reproduce in a workspace with many windows of gedit open. Changing workspaces and resizing some windows in the other workspace seems to resolve the problem temporarily.

## Environment

Linux 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 GNU/Linux

Gnome Shell 43.0

PaperWM version: commit at https://github.com/paperwm/PaperWM/commit/3bedb67f22881343c7b66639d28732fa6493d894

**Comment by jtaala** [comment] 2023-04-08 08:41
I tried to reproduce this with 100 terminal windows (lol, thought that might be enough).  Tried resizing various windows in that (poor) workspace but wasn't able to reproduce this.

Let me know @lediur if you're still seeing this issue or if you've got a way to reproduce it and I'll be able to have a look more at it.

Cheers!

**Comment by lediur** [comment] 2023-04-08 22:46
I'll try for the next week or so with https://github.com/paperwm/PaperWM/tree/9f3a5781b02d712454403dd65b841bf11b7478fe. If I see it again I'll comment

**Comment by jtaala** [comment] 2023-05-27 05:32
Thanks @lediur.  It's been more than a month since last post so assuming that it's not an issue that you saw.

I never could reproduce this after several attempts (I was also interested in seeing how many windows I could make and how long it took to scroll through them all!).

Will close this now.

**Closed as completed by jtaala** 2023-05-27 05:32 UTC
Labels: bug, can't reproduce
