### ISSUE TITLE
Ability to set focus on winprop or setting

### ISSUE THREAD

**Issue by rodrigogonegit** [paperwm/PaperWM#744] opened 2024-01-03 21:42 UTC
**Is your feature request related to a problem? Please describe.**
When opening Ulauncher, since it's bound to the scratch pad, the window is not focused which is really frustrating.

**Describe the solution you'd like**
I'd like to be able to set a winprop to automatically focus the window when opened, much like we can set the scratch pad prop based on win class name.

**Describe alternatives you've considered**
Using the swicter extension, but I really like Ulauncher.

Essentially I'd like to open Ulauncher as a floating window and have it automatically steal focus so I can type away immediately.

**Comment by Lythenas** [comment] 2024-01-04 17:25
Winprops can actually do that already:

https://github.com/paperwm/PaperWM/blob/6bead84704bf4db8fb7eb2ecd94bb1212059f7c3/tiling.js#L3296-L3298

But it's not exposed through the UI settings. Not sure why.

Also I think some other PR was changing/fixing something regarding scratch windows. But I don't remember if it also changed focusing. @jtaala do you remember?

Also for what it's worth, for me ulauncher automatically takes focus when it starts. I'm using:
![Screenshot from 2024-01-04 18-22-38](https://github.com/paperwm/PaperWM/assets/32217236/82a1cfe1-0795-4156-8483-69eb5e9de9b3)
But I'm not using it actively. I use the Search Light extension instead.

Edit: Actually I think it is #741 (which I am currently testing). It focuses scratch windows automatically now.

**Comment by jtaala** [comment] 2024-01-04 22:43
> @jtaala do you remember?

Ah, I added the `focus` property later and must have forgot to implement it in the  prefs UI.

I'll assign this to me and add this to the UI (it might also need to be in a `callbackOnActorShow`).

Thanks for the reminder.

**Comment by jtaala** [comment] 2024-01-04 22:48
> Also for what it's worth, for me ulauncher automatically takes focus when it starts. I'm using:

Relatedly, I also have ulauncher and similar settings to @Lythenas and it also automatically takes focus on start.

**Comment by jtaala** [comment] 2024-01-06 10:16
@rodrigogonegit, can you please run the `./generate-system.info.sh` script? (unless you're running a PaperWM version from extensions.gnome.org?).

I've added the focus option to the UI to branch `fix-744-add-focus-option-to-winprops` but I can't reproduce what you're seeing in ulauncher.  The shown window should have focus with or without this option (it does for me anyway).

Just need to know what version / commit of PaperWM you're on and if you're running X11/Wayland.

**Comment by jtaala** [comment] 2024-04-27 05:33
Closing as no response from user for several months.

**Closed as completed by jtaala** 2024-04-27 05:33 UTC
Labels: enhancement, can't reproduce
