### ISSUE TITLE
Gnome-pie does not work with PaperWM

### ISSUE THREAD

**Issue by danielyzli** [paperwm/PaperWM#156] opened 2019-07-14 03:52 UTC
Gnome-pie menus do not display when PaperWM is enabled i.e. the pies will show up invisibly, clicking items still work. Gnome-pie log shows nothing wrong. Please tell me how to provide more information. Thanks!

**Comment by olejorgenb** [comment] 2019-07-14 09:19
System information and logs is a first step:

Wayland or X11?

    gnome-shell --version

    dconf read /org/gnome/shell/enabled-extensions

    # Logs from around the time of the problem
    journalctl --pager-end $(which gnome-shell)

A screenshot if possible. (or - is "the pies" the whole application? Is anything visible at all)

Always good to test with only paperwm enabled (although in this case I don't think interaction with other extension is the problem).

I'll try to squeeze in some time testing on my ubuntu computer later.

NTS: I think this is gnome-pies window setup code https://github.com/Simmesimme/Gnome-Pie/blob/0d766697fb71f60d53e328f8b306eee4930d7508/src/renderers/pieWindow.vala#L123

**Comment by danielyzli** [comment] 2019-07-15 00:48
Gnome shell version: `3.30.2`
Pop! OS `18.10` (to all intensive purposes Ubuntu `18.10`)
X11

Enabled extensions:
![image](https://user-images.githubusercontent.com/47434276/61191367-80d39f80-a65e-11e9-86d0-1ccd02936b90.png)

Errors do not occur once paperWM is disabled. I found that the pies work fine when the gnome-pie settings GUI is open and put on `scratch`; is there a way to open all gnome-pie window instances as `scratch`? Maybe that might solve the problem.

Thanks!

**Comment by hedning** [comment] 2019-07-16 13:52
You can try something like this (from https://github.com/paperwm/PaperWM/blob/master/examples/winprops.js), if you have the wm_class:

```javascript
defwinprop({
    wm_class: "copyq",
    scratch_layer: true
});

**Comment by olejorgenb** [comment] 2019-07-16 15:02
On x11 you can use `xprop WM_CLASS` and click on a window to get the wm class

**Comment by danielyzli** [comment] 2019-07-16 15:58
Thanks for the tips! The `winprops` worked well for keeping the gnome-pie GUI afloat. Unfortunately, after more poking around, I discovered that the gnome-pie settings have to be the focused window, otherwise the gnome-pie pies are once again invisible. Any suggestions?

**Comment by hedning** [comment] 2019-07-16 16:56
Hmm, might work to add `focus: true` to the winprop (we should really make that the default for scratch I think).

**Comment by danielyzli** [comment] 2019-07-16 20:37
Unfortunately, the same invisible pie behaviour persisted after `focus: true` was added. I added it in my `user.js` like in the example in the `README`; would there be a difference if I added it in my `winprops.js`? One idea, what if apps were opened normally with regular windows, and placed into a `window conveyor` like the scrollable desktop implemented right now? Essentially this would be the opposite behaviour i.e. 'open and then tile' vs 'tile then place on scratch'; but it might settle better with apps that open weird windows like `gnome-pie`.

**Comment by olejorgenb** [comment] 2019-07-16 21:37
`user.js` is the correct place. (a `winprops.js` in the user folder is not automatically loaded)

I'm (@hedning?) not totally opposed of adding a floating-as-default option, though it's not sure it would help in this case since scratch: true should emulate "floating-as-default" for a single window more or less perfectly.

I'll install gnome-pie tomorrow and see if I can reproduce.

**Comment by danielyzli** [comment] 2019-07-17 17:49
Thanks for all the replies; this extension is so well supported, keep it up devs!

**Comment by olejorgenb** [comment] 2019-07-17 18:49
Pushed a fix in branch `ignore-dock-windows`. I'd like to investigate the root cause a bit more before pushing to master. Let me know if it doesn't work on you setup.

PS: the fix is not dependent on the winprop so you can remote that.

**Comment by danielyzli** [comment] 2019-07-17 23:38
So far, that works! Thanks a lot! :tada: :+1:

**Closed** 2019-07-19 20:09 UTC
