### ISSUE TITLE
Not working for Ubuntu 22.04

### ISSUE THREAD

**Issue by johnmee** [paperwm/PaperWM#405] opened 2022-04-24 03:52 UTC
I've tried all three branches: master, develop, and next-release.  No joy.

The gdbus command at the end of the install script returns `(false,'')`.

I'm on X11, not wayland (due to nvidia), and it is Gnome 42.
Cloned it directly into `~/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org` and did git switches in there. Yes, gnome reset, but didnt bother to login/out/reboot.  Got nothing at all; the keybindings for Gui-left and Gui-right do throw the window left and right, but they are the gnome/mutter default actions.

Shame.  This was my daily driver :-{

**Comment by bentongxyz** [comment] 2022-04-24 08:05
it seems that it will not work on Gnome 42

from `README`

| Supports Gnome Shell from 3.28 to 3.38 on X11 and wayland.

Indeed a shame, I would love to use PaperWM on the latest DE

**Comment by bentongxyz** [comment] 2022-04-24 08:05
it seems that it will not work on Gnome 42

from `README`

| Supports Gnome Shell from 3.28 to 3.38 on X11 and wayland.

Indeed a shame, I would love to use PaperWM on the latest DE

**Comment by johnmee** [comment] 2022-04-25 07:47
For What Its Worth, I did have the 'next-release' branch working on gnome 40.

I have a 4K monitor, and just being able to center the window I'm working with is a bit of a winner.  Can't believe gnome std has left and right align kb shortcuts, but not "put it in the middle"!  <facepalm>  (or do they?)

**Comment by bentongxyz** [comment] 2022-04-25 14:11
damn... my thought exactly!
I'm using gTiles as suggested by fellow redditors, 
allow me to customize where to put the windows, 
working great so far!

**Comment by romaia** [comment] 2022-04-26 14:21
There was a fork somewhere with patches to make it work on recent gnome versions, but I can't seem to find it anymore.

**Comment by ellakk** [comment] 2022-04-30 18:11
PaperWM-community next-release branch does not yet work on Ubuntu 22.04. There is a pull request that is not merged yet that adds support, at leats it works for me :) :
https://github.com/PaperWM-community/PaperWM/pull/25

**Comment by manpagebob** [comment] 2022-05-11 12:24
> For What Its Worth, I did have the 'next-release' branch working on gnome 40.
> 
> I have a 4K monitor, and just being able to center the window I'm working with is a bit of a winner. Can't believe gnome std has left and right align kb shortcuts, but not "put it in the middle"! (or do they?)

Off-topic but there's this entry in the dconf gnome schema: _org.gnome.desktop.wm.keybindings.move-to-center_

You can write the value with:

`dconf write /org/gnome/desktop/wm/keybindings/move-to-center "['<Key>x']"` 

where x might be another function key or some other key that doesn't need brackets. Here's my binding for moving a window to the workspace to the right

`/org/gnome/desktop/wm/keybindings/move-to-workspace-right "['<Shift><Super>Right']"`

**Comment by johnmee** [comment] 2022-05-14 07:30
@manpagebob 
To center current window left-right (and up-down) with "GUI-C"

`dconf write /org/gnome/desktop/wm/keybindings/move-to-center "['<Super>C']"`

**Comment by smichel17** [comment] 2022-08-15 13:24
I'm going to close this as a duplicate of #409

**Closed by smichel17** 2022-08-15 13:24 UTC
