### ISSUE TITLE
Wayland 3-finger swipe broken?

### ISSUE THREAD

**Issue by thomaseizinger** [paperwm/PaperWM#413] opened 2022-09-01 20:12 UTC
I've been testing out the Gnome 42 branch (referenced [here](https://github.com/paperwm/PaperWM/issues/409)) and it works pretty good. The only thing I've found to be broken is the 3-finger swipe is meant to be supported on Wayland (according to the README).

Is this a known problem or something with my local setup?

When I try 3-finger swipe sideways, the window jitter a bit and sometimes move but not reliably. I think it would be great if swiping through horizontally with 3 fingers would just scroll the way a webpage scrolls, i.e. _without_ snapping. The user's next click on the window will snap it into place anyway. This way, it would be super easy to just scroll through all windows that are open, skimming them as they go past and choosing the one that you want by stopping the scrolling and focusing a window.

**Comment by hedning** [comment] 2022-09-07 19:05
Just upgraded to gnome 42. It looks like Gnome Shell captures the 3-finger swipe and tries to do a native workspace change, which obviously looks strange.

I'm guessing the code that disabled the native swipe handlers no longer work.

So we'll need a new kludge to disable native swipe handling.

**Comment by smichel17** [comment] 2022-09-07 21:27
One thing that's not well-documented is that installing the **[vertical overview](https://github.com/github.com/RensAlthuis/vertical-overview)** extension alongside PaperWM is ~required for the current gnome 42 code to work properly.

**Comment by smichel17** [comment] 2022-09-07 21:31
In https://github.com/PaperWM-community/PaperWM/discussions/6, we decided at the time that as long as the two extensions work well together, not to merge its code base into ours, to avoid duplicating effort. But that's a big "as long as"; I suspect eventually we will have to do it.

**Comment by alexpdp7** [comment] 2022-10-13 20:29
This seems also to apply to Gnome 40 (CentOS Stream 9). I also applied the extension and solved the issue.

**Comment by Thesola10** [comment] 2022-11-18 10:39
I believe this issue should be pinned for people to find it easily.

**Comment by smichel17** [comment] 2022-11-18 17:33
I have pinned it, but I think it would be best to include in the README, alongside the other installation information.

Also,

1. I saw issues caused by the vertical workspaces extension in the another issue (not sure which off hand, sorry!)
2. With multiple monitors, windows do not currently appear on the correct monitor when you enter the overview

Especially considering (2) is something kind of unique to PaperWM (using different workspaces for different monitors), I suspect it might not be fixed in the vertical workspaces extension, so we might end up adding overview handling to PaperWM sooner than later. (Only if someone feels like tackling those issues, of course)

**Closed** 2023-03-21 19:53 UTC
Labels: bug, documentation, gnome-42
