### ISSUE TITLE
Gnome 44: loss of mouse input

### ISSUE THREAD

**Issue by schopin-pro** [paperwm/PaperWM#495] opened 2023-03-20 11:10 UTC
**Describe the bug**

During navigation, I totally lost any form of mouse input. I was still able to use keyboard, though.
The mouse cursor was stuck as a "crossed arrow".

I found the following in the gnome-shell logs:

```
gnome-shell[63733]: JS ERROR: TypeError: global.display.end_grab_op is not a function
                                             begin@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/grab.js:53:24
                                             createBackground/<@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/tiling.js:1384:28
gnome-shell[63733]: JS ERROR: TypeError: this.pointerOffset is undefined
                                             beginDnD@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/grab.js:128:28
                                             _doAction@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/navigator.js:212:31
                                             show@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/navigator.js:116:14
                                             preview_navigate@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/navigator.js:446:14
                                             asKeyHandler/<@/home/schopin/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/keybindings.js:272:20
```

**To Reproduce**
Sadly, I don't have a reproducer.

**System information:**
```
Distribution: Ubuntu
GNOME Shell 44.rc
PaperWM branch/tag: develop
PaperWM commit: d601f99d87837f925ebc41a5ab961cd13aa0f1c7
Enabled extensions:
- paperwm@hedning:matrix.org
- nightthemeswitcher@romainvigier.fr
- vertical-workspaces@G-dH.github.com
- ubuntu-appindicators@ubuntu.com
```

**Comment by jtaala** [comment] 2023-03-22 12:53
Yep, looks like gnome-44 removed the `end_grab_op` function from

https://gitlab.gnome.org/GNOME/mutter/-/blob/gnome-43/src/core/display.c#L2009

Compare 

https://gitlab.gnome.org/GNOME/mutter/-/blob/44.0/src/core/display.c

Not sure where the equivalent function is (or if there is one).  Hoping it's deprecated and not needed (looks like original function was mostly cleanup).  I'd try remove/comment-out that line and check the behaviour in gnome 44.

Unlikely though - commenting that line out on Gnome 43 causes behaviour similar to what you described.  Looks like we'll have to find an equivalent (functionally) for 44.

**Comment by jtaala** [comment] 2023-03-22 13:13
Seems this function is very similar and potentially what we might need to move to (although the function input is different - expects a window to terminate the default dragging, so paperwm can do it's' own):

https://gitlab.gnome.org/GNOME/mutter/-/blob/44.0/src/compositor/meta-window-drag.c#L360

**Comment by jtaala** [comment] 2023-03-22 21:50
Sidenote: lots of other extensions will be hit with this one, including material-shell:

https://github.com/material-shell/material-shell/blob/becc8b3b1b4f0447ceb8ea258e166bb4732d3079/src/manager/msResizeManager.ts#L73

**Comment by jtaala** [comment] 2023-03-22 21:57
Interesting commit looking to solve this issue in gnome 44 (putting here for reference):

https://github.com/Leleat/Tiling-Assistant/commit/85c9dd17106e3e581d69618f6a6a8ccdce842dbd

**Comment by fumbles** [comment] 2023-04-20 15:53
I wonder if this is what I'm hitting: 
I'm unable to click any window. Can still get to windows in the scratch layer fine though. And can navigate windows just can't click into anything at all. 

![image](https://user-images.githubusercontent.com/90968/233420370-2e8bf746-d96a-485e-889b-76659c925286.jpeg)

**Comment by jtaala** [comment] 2023-04-20 21:41
> I wonder if this is what I'm hitting: I'm unable to click any window. Can still get to windows in the scratch layer fine though. And can navigate windows just can't click into anything at all.
> 

Is this for gnome 44? (note: gnome 44 doesn't work with paperwm atm).

**Comment by fumbles** [comment] 2023-04-20 22:51
Ah yes. It’s gnome 44. I pulled the trigger and upgraded to fedora 38 🤦🏻‍♂️ It mostly works…Sent from my iPhoneOn Apr 20, 2023, at 16:41, jtaala ***@***.***> wrote:﻿

I wonder if this is what I'm hitting: I'm unable to click any window. Can still get to windows in the scratch layer fine though. And can navigate windows just can't click into anything at all.

Is this for gnome 44? (note: gnome 44 doesn't work with paperwm atm).

**Comment by jtaala** [comment] 2023-04-22 02:41
@fumbles @schopin-pro I've just pushed up a Gnome 44 support PR #515.

Can you test this?  E.g. do a

```
git fetch --all
git checkout fixes-gnome-44-support
```
and logout/login.

It's now working fine in Fedora 38 for me - can you please test this?  Note, there's still an small issue/annoyance: t seems to require a second click to activate a window (after moving a window) - but at least it doesn't completely/irreversibly lose mouse click control.  Will look at this and see how to improve here.

**Comment by crispinb** [comment] 2023-04-22 03:15
I just gave this a short test & it seems good so far. Some error message pops up when I log in that I forgot to note & it doesn't remain in the gnome notifications panel. I'll check what it is next time I log in (too many windows & workspaces open to want to rearrange right now).

I'll be at the computer much of today & will report on any new issues that arise.

[& thanks - the temporary loss of PaperWM was making me regret my impetuous Fedora upgrade]

**Comment by fumbles** [comment] 2023-04-22 03:24
I just enabled it- will check it on out. Thanks!

**Comment by crispinb** [comment] 2023-04-22 19:04
After a good few hours of use yesterday things mostly seemed as they should.

I had one odd glitch which I can't reproduce and don't know whether it might be a Gnome rather than a PaperWM issue (there are still a lot of package updates rolling in for Fedora 38).

One window suddenly became frontmost on all workspaces, obscuring others. And the  workspace switching animation (behind the on-top window) stopped working. 

The errant window had 'Always on Top' and 'Always on Visible' ticked, and unticking them did nothing. Disabling and re-enabling the PaperWM extension didn't fix it and I had to log out and back in.

**Comment by jtaala** [comment] 2023-04-23 11:13
> The errant window had 'Always on Top' and 'Always on Visible' ticked, and unticking them did nothing. Disabling and re-enabling the PaperWM extension didn't fix it and I had to log out and back in.

That just sounds like a `scratch` window (if it was, unticking `scratch` in that same menu would have fixed it).

**Comment by jtaala** [comment] 2023-04-23 11:37
See comment around grab/moving windows around with mouse in Gnome 44 (and the issue atm):

https://github.com/paperwm/PaperWM/pull/515#issuecomment-1519042682

**Comment by crispinb** [comment] 2023-04-24 03:12
> That just sounds like a `scratch` window (if it was, unticking `scratch` in that same menu would have fixed it)

If it was, it was a broken scratch layer because show/hide wasn't working. Nor was much else (everything had kind of gone nuts). But it hasn't happened again, and all is good.

Should us Gnome 44 users be staying on the `fixes-gnome-44-support` branch for now?

**Comment by jtaala** [comment] 2023-04-24 12:35
> > That just sounds like a `scratch` window (if it was, unticking `scratch` in that same menu would have fixed it)
> 
> If it was, it was a broken scratch layer because show/hide wasn't working. Nor was much else (everything had kind of gone nuts). But it hasn't happened again, and all is good.

Oh dang, that does sound messed up.

> Should us Gnome 44 users be staying on the `fixes-gnome-44-support` branch for now?

For now - hoping to get this merged in asap - still stuggling with the mouse-move-window-needing-extra-click issue...

**Comment by jtaala** [comment] 2023-04-25 01:47
Hey all, finally found a fix/workaround for the "needs a second click after pointer grab/moving a window".

Could you please got a `git pull` on the `fixes-gnome-44-support` branch and test that for us?

Once (if) you're happy, please let us know and we'll work to get these changes merged.

**Comment by jtaala** [comment] 2023-04-25 08:27
> Hey all, finally found a fix/workaround for the "needs a second click after pointer grab/moving a window".
> 
> Could you please got a `git pull` on the `fixes-gnome-44-support` branch and test that for us?
> 
> Once (if) you're happy, please let us know and we'll work to get these changes merged.

~~Well :cry: that fix only works in X11... `gi.Atspi` apparently has issues in wayland.  Looking for another approach.~~

**Comment by jtaala** [comment] 2023-04-26 20:33
Fix is in for this now (implemented mutter based Wayland compatible fix).  Please pull and test this.

**Comment by crispinb** [comment] 2023-04-26 22:09
So far so good here & I'll be on it most of the day so will let you know if anything arises. I didn't really hit the mouse focus problem as it was though. Maybe I don't use the mouse enough.

**Comment by crispinb** [comment] 2023-04-27 05:32
Here's an oddity. Some apps in the scratch layer, sometimes, maximise with a single click in the window title bar. Chrome is the only app I can reproduce this consistently with. With a single click, the mouse pointer changes briefly to drag cursor style, and the window maximises. So if I try  to drag a Chrome window in the scratch layer by grabbing the title bar, it maximises instead.  It can be coerced to a drag by doing the whole operation more slowly.

It's not really a problem for me (if I move a window with the mouse, I usually use Super + click for a bigger target), but thought it worth pointing out.

**Comment by jtaala** [comment] 2023-04-27 23:46
> Here's an oddity. Some apps in the scratch layer, sometimes, maximise with a single click in the window title bar. Chrome is the only app I can reproduce this consistently with. With a single click, the mouse pointer changes briefly to drag cursor style, and the window maximises. So if I try to drag a Chrome window in the scratch layer by grabbing the title bar, it maximises instead. It can be coerced to a drag by doing the whole operation more slowly.
> 
> It's not really a problem for me (if I move a window with the mouse, I usually use Super + click for a bigger target), but thought it worth pointing out.

Thanks @crispinb, can you pull the latest and give it a test.  I was able to reproduce this issue once, but haven't been able to with the latest changes (although I might just be not doing it right...).

**Comment by crispinb** [comment] 2023-04-28 00:23
The Chrome maximise on click still happens for me (on fixes-gnome-44-support 9caf8e8). See attached recording. Firstly there I click to maximise, then secondly to restore. Then I click, hold for slightly longer, then release.  Mouse movement now drags the Chrome window. It requires another click or `<ESC>` press to release the drag operation's hold.

I think this is only happening with Chrome.


[chrome-click-drag.webm](https://user-images.githubusercontent.com/630851/235018024-f868446a-96e1-44db-986e-cace870cf0ec.webm)

**Comment by jtaala** [comment] 2023-04-28 03:09
> The Chrome maximise on click still happens for me (on fixes-gnome-44-support [9caf8e8](https://github.com/paperwm/PaperWM/commit/9caf8e8318f28cb5b2a9d5d7b62ca7bb19758c31)). See attached recording. Firstly there I click to maximise, then secondly to restore. Then I click, hold for slightly longer, then release. Mouse movement now drags the Chrome window. It requires another click or `<ESC>` press to release the drag operation's hold.
> 
> I think this is only happening with Chrome.
> 
>  chrome-click-drag.webm

Perfect, thanks @crispinb - yeah, I just wasn't doing this right! (to reproduce).  Will look at this when I'm back at home.

**Comment by jtaala** [comment] 2023-04-28 13:40
> Perfect, thanks @crispinb - yeah, I just wasn't doing this right! (to reproduce). Will look at this when I'm back at home.

Another day, another test!  @crispinb, pull latest from `fixes-gnome-44-support` branch - it should fix this issue (was caused by the virtual "clickout" causing a regrab.  Working now in my tests, but let me know.

**Comment by crispinb** [comment] 2023-04-28 21:02
OK, got it. And, yes, it seems to have done the trick.

**Comment by fumbles** [comment] 2023-05-02 14:48
I've hit this issue a few times after you've updated the branch.... I didn't hit it before hilariously.

```Please include this information in your bug report on GitHub!
Distribution: Fedora Linux
GNOME Shell 44.1
Display server: Wayland
PaperWM branch/tag: fixes-gnome-44-support
PaperWM commit: 47a6d9ead03c899a96cf5efe57d7b747a74db262
Enabled extensions:
- paperwm@hedning:matrix.org
- drive-menu@gnome-shell-extensions.gcampax.github.com
- dash-to-dock@micxgx.gmail.com
- clipboard-indicator@tudmotu.com
- utcclock@injcristianrojas.github.com
- apps-menu@gnome-shell-extensions.gcampax.github.com
- background-logo@fedorahosted.org
- places-menu@gnome-shell-extensions.gcampax.github.com
- appindicatorsupport@rgcjonas.gmail.com
- caffeine@patapon.info
```

**Comment by randomvariable** [comment] 2023-05-11 22:43
I only upgraded on the weekend so only had this branch, and am experiencing the issue. It'll be disappointing if Gnome 44 really has made this impossible.

**Closed as completed** 2023-05-19 20:58 UTC
Labels: bug
