### ISSUE TITLE
Desktop on Gnome 40 has extra window

### ISSUE THREAD

**Issue by forgottosave** [paperwm/PaperWM#423] opened 2022-10-06 20:10 UTC
###### Overview
Gnome Version: 40
Operating System: Ubuntu 20.04
PaperWM branch: gnome-40
Recreate bug: Just use PaperWM

###### Details
Since updating to gnome 40 today I encountered a weird issue:
The desktop (background, I don't know how to call it better) seems to be treated like a weird separated application (see image below).
In this image I currently hold `Super + left`, which shows all of the open applications, the focus being on the weird desktop.

![image](https://user-images.githubusercontent.com/88790311/194408295-fbffd40f-d74f-4d02-8599-2d01f9094741.png)

 PaperWM allows to switch to it, just like any other application. This on it own could be ignored by moving the window to the very left or right and not moving to it, but sadly every time I switch the workspace it gets moved right next to the focused window.
 Sadly this kinda maked PaperWM unusable.

**Comment by forgottosave** [comment] 2022-10-06 20:19
By the way: Moving this "application" to the scratch layer to avoid it works, but comes with the major bug of not being able to use the mouse in *any* windows anymore

**Comment by jtaala** [comment] 2023-03-02 19:43
Hey @forgottosave, closing as I can't reproduce this.  Please let me know if this is still  happening for you and I can reopen.  Cheers.

**Closed as not planned by jtaala** 2023-03-02 19:43 UTC

**Comment by manuelmorales** [comment] 2023-09-19 08:20
Sorry for the issue necromancing. But I just experienced the same and disabling the "Desktop Icons NG" built-in extension fixed it. I hope this helps.
