### ISSUE TITLE
Crash on startup - `Tiling.spaces.monitors is undefined`

### ISSUE THREAD

**Issue by smichel17** [paperwm/PaperWM#563] opened 2023-07-26 00:07 UTC
**Summary**
On startup, PaperWM fails to activate and there is a notification that "an error occurred in PaperWM startup."

**Details**

Clicking the notification opens a text editor containing a stack trace:
```
Tiling.spaces.monitors is undefined

_checkWorkspaces@kludges.js:551:34
init@tiling.js:1599:35
initWorkspaces@tiling.js:2706:20
enable/startupTimeoutId<@tiling.js:2737:13
```

I bisected and it looks like the first commit with this error is b85dfcd4528ae0b584489c6b38a6845d44b22aa6.

**System information**

```
Distribution: Fedora Linux (38)
GNOME Shell 44.0
Display server: Xorg
PaperWM branch/tag: release
PaperWM commit: df9a6b212b67726b4b5f2cb39a294afa0ee2503d
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- paperwm@paperwm.github.com
- clipboard-indicator@tudmotu.com
```

**Comment by rhedgeco** [comment] 2023-07-26 00:38
Thanks for making this. Was about to make a report when it just happened to me. Exact same issue.

**Comment by smichel17** [comment] 2023-07-26 00:44
For now, `git checkout a27d3168` will take you to the latest commit that works for me.

**Comment by jtaala** [comment] 2023-07-26 10:29
Thanks for reporting @smichel17 & @rhedgeco.  Haven't been able to reproduce this yet but am working on it.

@rhedgeco - are you also on Gnome 44.0 and X11?

**Comment by jtaala** [comment] 2023-07-26 10:30
Also I'm assuming you have multimonitors? (just given the commit @smichel17 pointed to).

**Comment by smichel17** [comment] 2023-07-26 10:36
Actually this was on a single monitor (laptop). I do also have a multi-monitor setup to test with.

**Comment by jtaala** [comment] 2023-07-26 10:48
Okay, found it - looks like it's "dynamic workspaces" (as opposed to fixed number of workspaces).

**Comment by jtaala** [comment] 2023-07-26 10:59
Got a fix.  Will push it up shortly.

**Comment by jtaala** [comment] 2023-07-26 11:17
Thanks again for reporting this one @smichel17 and @rhedgeco.  Fix has been implemented in `v44.5.1`.

Can you please checkout the latest release and let me know if you still have any issues here?

**Comment by jtaala** [comment] 2023-07-26 11:31
Closing as fixed in https://github.com/paperwm/PaperWM/commit/9101b748415edbe9ba8da56d5c7cd49b13d8bddb.

**Closed as completed by jtaala** 2023-07-26 11:31 UTC
Labels: bug

**Comment by rhedgeco** [comment] 2023-07-26 16:51
Using arch package again that is up to date with the fix. All good on my end! Thanks @jtaala

**Comment by jtaala** [comment] 2023-07-26 21:05
Hey @smichel17 @rhedgeco, just a heads-up I pushed up a fix (see https://github.com/paperwm/PaperWM/pull/564) and did another release for an issue that wasn't picked up immediately (it only happened sometimes).  Basically we removed an old fix which looked like wasn't applicable anymore and our testing routines didn't pick up any issues (caused some visual anomalies that were noticed later).

Anyways, @rhedgeco, I've updated the AUR packages so please update again to get this fix.

Cheers!
