### ISSUE TITLE
drag/drop window gets stuck (regression from #897) FIXED (awaiting release on extensions.gnome.org)

### ISSUE THREAD

**Issue by AlexeySFr** [paperwm/PaperWM#898] opened 2024-07-18 18:32 UTC
**Describe the bug**

**To Reproduce**
1. Enable extension
2. Try drag window
3. See error

**Expected behavior**
Can't use window until i close them 

**Screenshots**
![Screenshot from 2024-07-19 01-31-55](https://github.com/user-attachments/assets/e944a600-257c-4fb7-892a-065a1dda5615)
Also i have video what show's that bug

See https://www.youtube.com/watch?v=ci_7v6axcss

**System information:**
```
Distribution: Arch Linux
GNOME Shell: 46.3.1
Display server: Wayland
PaperWM version: 46.13.3
Enabled extensions:
- screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
- user-theme@gnome-shell-extensions.gcampax.github.com
- paperwm@paperwm.github.com
```

**Comment by jtaala** [comment] 2024-07-18 22:04
Thanks for reporting!  ah, looks like a regression from #897.

**Comment by jtaala** [comment] 2024-07-18 22:26
Thanks @AlexeySFr,

Pushed a fix for this that's been released.

I'll reopen this ticket for others' vis until `v46.13.4` gets approved / released on gnome.extensions.org.

https://extensions.gnome.org/review/56513

Thanks for reporting so quickly!

**Comment by jtaala** [comment] 2024-07-18 22:27
I've also inactivated the impacted version on extensions.gnome.org.

**Closed as completed** 2024-07-19 09:21 UTC
Labels: bug
