### ISSUE TITLE
Windows change their horizontal position after consuming operation

### ISSUE THREAD

**Issue by tobias-haenel** [paperwm/PaperWM#684] opened 2023-11-11 17:46 UTC
**Describe the bug**
Consuming the window to the right changes the horizontal position of the previously focused window 
**To Reproduce**
1. Opened chromium browser with 50% width (width specified by Winprops)
2. Opened kitty terminal 1 with 50% width (width specified by Winprops)
3. Opened kitty terminal 2 with 50% width 
4. Opened kitty terminal 3 with 50% width 
5. Move focus to kitty terminal 1
6. Consume the window to the right into the active column
7. Column with Kitty terminal 1 and 2 moves slightly to the right. This breaks the cool effect of 50% window focus movements

**Expected behavior**
Column with Kitty terminal 1 and 2 should stay at the original focus position

**Screenshots**
[Screencast from 2023-11-11 17-38-10.webm](https://github.com/paperwm/PaperWM/assets/6195791/b8580637-547e-4be7-ac05-028a87e85ffe)

**System information:**
```
Distribution: Arch Linux
GNOME Shell 45.1
Display server: Wayland
PaperWM branch/tag: https://extensions.gnome.org/extension version for Gnome 45 v57
Enabled extensions:
- appindicatorsupport@rgcjonas.gmail.com
- blur-my-shell@aunetx
- paperwm@paperwm.github.com
- no-overview@fthx
- alttab-mod@leleat-on-github
- auto-move-windows@gnome-shell-extensions.gcampax.github.com
- launch-new-instance@gnome-shell-extensions.gcampax.github.com
- user-theme@gnome-shell-extensions.gcampax.github.com
```

**Comment by jtaala** [comment] 2023-11-11 21:49
Thanks for reporting @tobias-haenel - seems to be some small miscalculation in layouting when that browser window was involved and then consuming (I couldn't reproduce just with terminals).

In any case, I can reproduce this so should be able to address it.

**Comment by jtaala** [comment] 2023-11-12 05:09
Hey @tobias-haenel, I've implemented a fix for this.  Are you able to test this out?

If you're on ego version, then please uninstall that (don't worry, you won't lose any of your settings etc.) and install the branch for tests.  Then from a terminal run:

```
git clone https://github.com/paperwm/PaperWM.git
cd PaperWM
git checkout fix-684-consume-window-can-change-window-positions
./install.sh
```

Then logout / login.

Let me know how it goes!

**Comment by jtaala** [comment] 2023-11-12 06:11
P.S. you can uninstall the source version (and then reinstall the ego version) by:

```
cd PaperWM
./uninstall.sh
```

**Comment by jtaala** [comment] 2023-11-12 06:23
~~Scrap that - still appearing to happen in some cases.  Will keep working on it.~~

**Comment by jtaala** [comment] 2023-11-12 06:57
~~Okay, should be good to go.  I can non longer reproduce this issue - but please give it a test on your side.~~

**Comment by jtaala** [comment] 2023-11-12 07:03
Ahhh... wil get back to you on this :-(

**Comment by jtaala** [comment] 2023-11-12 10:43
Okay, finally found the issue.  Was indeed a window position layout calculation.

Please test.

**Comment by tobias-haenel** [comment] 2023-11-12 19:10
The original issue seems to be fixed.

But I noticed another problem, there seems to be another temporary layout issue whenever I copy something to the system clipboard from inside my terminal (under Wayland). Should I open another issue for this?

This might be due to GNOMEs weird handling of clipboard events under Wayland. Apparently wl-clipboard creates a hidden window that temporarily steals the focus whenever I copy something to the clipboard. Here is another screencast of this situation. 
[Screencast from 2023-11-12 20-07-38.webm](https://github.com/paperwm/PaperWM/assets/6195791/7d3e20d2-cf4f-4a0c-8318-7b42fdd1ec57)

**Comment by jtaala** [comment] 2023-11-12 19:51
> The original issue seems to be fixed.

thanks for testing!

**Comment by jtaala** [comment] 2023-11-12 20:03
> But I noticed another problem, there seems to be another temporary layout issue whenever I copy something to the system clipboard from inside my terminal (under Wayland). Should I open another issue for this?
> 
> This might be due to GNOMEs weird handling of clipboard events under Wayland. Apparently wl-clipboard creates a hidden window that temporarily steals the focus whenever I copy something to the clipboard. Here is another screencast of this situation. [Screencast from 2023-11-12 20-07-38.webm](https://github.com/paperwm/PaperWM/assets/6195791/7d3e20d2-cf4f-4a0c-8318-7b42fdd1ec57)

Well, you're right in that it's an upstream gnome/mutter issue (not PaperWM), see this comment:
https://github.com/paperwm/PaperWM/issues/466

See this comment for avoiding it causing a paperwm layouting issue (note: can't do anything re the focus issue as that's how `wl-copy` works in gnome/mutter due to need for that workaround):

https://github.com/paperwm/PaperWM/issues/466#issuecomment-1399223112

**Comment by jtaala** [comment] 2023-11-12 20:09
I was going to say you could submit an issue for this to gnome/mutter, but it already has been (and was closed):

https://github.com/bugaevc/wl-clipboard/issues/90#issuecomment-653054552

**Comment by tobias-haenel** [comment] 2023-11-12 20:45
Thanks for your effort! Looking forward to the merge.

**Closed as completed** 2023-11-14 10:28 UTC
Labels: bug, PR READY
